function prefspanel
%PREFSPANEL Registers a Filter Design Toolbox preferences control panel.
%   PREFSPANEL registers a Preferences Control panel with the MATLAB IDE.

%   Author: P. Costa
%   Copyright 1999-2003 The MathWorks, Inc.
%   $Revision: 1.4.4.2 $  $Date: 2004/04/12 23:25:41 $

% Register Object-based context menus items in the Workspace Browser.

% MFILT subclass names
mfiltsubcls = {'mfilt.cicdecim'; ...
        'mfilt.cicdecimzerolat'; ...
        'mfilt.cicinterp'; ...
        'mfilt.cicinterpzerolat'; ...
        'mfilt.fftfirinterp'; ...
        'mfilt.firdecim'; ...
        'mfilt.firfracdecim'; ...
        'mfilt.firfracinterp'; ...
        'mfilt.firinterp'; ...
        'mfilt.firsrc'; ...
        'mfilt.firtdecim'; ...
        'mfilt.holdinterp'; ...
        'mfilt.linearinterp'};

% ADAPTFILT subclass names
adaptfiltsubcls = {'adaptfilt.lms',...		
        'adaptfilt.nlms',...
        'adaptfilt.dlms',...
        'adaptfilt.blms',...	
        'adaptfilt.blmsfft',...
        'adaptfilt.ss',...	
        'adaptfilt.se',...		
        'adaptfilt.sd',...		
        'adaptfilt.filtxlms',...	
        'adaptfilt.adjlms',...	
        'adaptfilt.lsl',...		
        'adaptfilt.qrdlsl',...	
        'adaptfilt.gal',...		
        'adaptfilt.tdafdft',...	
        'adaptfilt.tdafdct',...
        'adaptfilt.rls',...
        'adaptfilt.hrls',...
        'adaptfilt.swrls',...
        'adaptfilt.hswrls',...
        'adaptfilt.qrdrls',...
        'adaptfilt.ftf',...
        'adaptfilt.swftf',...
        'adaptfilt.ap',...
        'adaptfilt.bap',...	
        'adaptfilt.apru'};

analyses = {'Magnitude Response',...
        'Phase Response',...
        'Magnitude and Phase Response',...
        'Group Delay',...
        'Impulse Response',...
        'Step Response',...
        'Pole/Zero Plot',...
        'Filter Coefficients',...
        'Filter Information'};

fvtcalls = {'fvtool($1);',...
    'fvtool($1,''phase'');',...
    'fvtool($1,''freq'');',...
    'fvtool($1,''grpdelay'');',...
    'fvtool($1,''impulse'');',...
    'fvtool($1,''step'');',...
    'fvtool($1,''polezero'');',...
    'fvtool($1,''coefficients'');',...
    'fvtool($1,''info'');'};


%   Methods of MatlabObjectMenuRegistry are unsupported.  Calls to these
%   methods will become errors in future releases.
com.mathworks.mlwidgets.workspace.MatlabCustomClassRegistry.registerClassCallbacks(...
    {'qfilt'},...
    'Analyze',...
    {analyses{:},...
        'Magnitude Response Estimate',...
        'Round-off Noise Power Spectrum'},...
    {fvtcalls{:},...
        'fvtool($1,''magestimate'');',...
        'fvtool($1,''noisepower'');'});


com.mathworks.mlwidgets.workspace.MatlabCustomClassRegistry.registerClassCallbacks(...
    mfiltsubcls,...
    'Analyze',...
    {analyses{:}},...
    {fvtcalls{:}});

com.mathworks.mlwidgets.workspace.MatlabCustomClassRegistry.registerClassCallbacks(...
    adaptfiltsubcls,...
    'Analyze',...
    {analyses{:}},...
    {fvtcalls{:}});

% [EOF]
