/*
 * @(#)buf_copy_input_to_output_1ch_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:35 2004
 *
 *		built from:	buf_copy_input_to_output_1ch_rt.c
 */

#ifndef buf_copy_input_to_output_1ch_rt_h
#define buf_copy_input_to_output_1ch_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_Buf_CopyInputToOutput_1ch(
    const byte_T *u,
    byte_T       *y,
    int32_T      *cnt,
    const int_T   bytesPerElement,
    const int_T   nBytesToCopy,
    const int_T   F,
    const int_T   N
);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* buf_copy_input_to_output_1ch_rt_h */
