/*
 * @(#)flip_vector_op_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:24 2004
 *
 *		built from:	flip_vector_op_rt.c
 */

#ifndef flip_vector_op_rt_h
#define flip_vector_op_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_FlipVectorOP(const byte_T *u,
                        byte_T       *y,
                        int_T        numRows,
                        int_T        numCols,
                        int_T        bytesPerElement);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* flip_vector_op_rt_h */
