// ParallelAdaptor.idl : IDL source for ParallelAdaptor.dll
//
// Copyright 1998-2003 The MathWorks, Inc. 
// $Revision: 1.1.6.2 $  $Date: 2003/12/04 18:40:14 $
//
// This file will be processed by the MIDL tool to
// produce the type library (ParallelAdaptor.tlb) and marshalling code.

import "daqmex.idl";

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(87708F04-48EA-4C25-8D71-27F3E29FB83D),
	version(1.0),
	helpstring("ParallelAdaptor 1.0 Type Library")
]
library PARALLELADAPTORLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(890C55F6-1DEF-4719-B1A6-5C3726DC054F),
		helpstring("ParallelAdapt Class")
	]
	coclass ParallelAdapt
	{
		[default] interface ImwAdaptor;
	};
	[
		uuid(42B1047E-5A2D-4BB1-9646-361C6A53D9F1),
		helpstring("ParallelDio Class")
	]
	coclass ParallelDio
	{
		[default] interface ImwDIO;
	};
};
