function message = i_convert_to_matlab(j_message)
%I_CONVERT_TO_MATLAB
% Convert the java message to a matlab structure

%   Copyright 2001-2002 The MathWorks, Inc.
%   $Revision: 1.10.4.1 $
%   $Date: 2004/04/19 01:19:34 $

      message = i_bean2struct(j_message, ...
            {
               'dataIsExternal',    ...
               'DbFilePath',        ...
               'id',                ...
               'idType',            ...
               'length',            ...
               'messageName',       ...
            });
      if j_message.getSize == 0
         message.signals = [];
      end

      for i=1:j_message.getSize
         signal = j_message.getElementAt(i-1);
         message.signals.signal(i) = i_bean2struct(signal, ...
               {  'byteLayout'   ...
                  'dataType'     ...
                  'factor'       ...
                  'length'       ...
                  'modeValue'    ...
                  'name'         ...   
                  'offset'       ...   
                  'physicalUnit' ...
                  'signalType'   ...
                  'startBit'     ...
                  });
      end


