function libs = dspliblist
% DSPLIBLIST Return list of Signal Processing Blockset libraries.
%
%   See also DSP_LINKS, DSPBLIST.

% Copyright 1995-2003 The MathWorks, Inc.
% $Revision: 1.12.4.2 $ $Date: 2004/04/12 23:05:19 $


% Signal Processing Blockset Version 2:
libs.dsp2 = {'dspsrcs','dspsnks',...
             'dspelmat','dspvect', 'dspmtrx','dspcmplx','dspstat', ...
             'dspbdsp','dspxfrm','dspbuff','dspswit',...
             'dspspect',...
             'dspddes','dsparch','dspadpt','dspmlti'};

% Signal Processing Blockset Version 3:
libs.dsp3 = {'dspsrcs2','dspsnks2',...
             'dspelem2', 'dspvect2', 'dspmtrx2','dsplinalg','dspstat2', ...
             'dspbdsp2','dspxfrm2','dspbuff2','dspswit2','dspquant',...
             'dspparest2','dspspect2',...
             'dspddes2','dsparch2','dspadpt2','dspmlti2'};

% Signal Processing Blockset Version 4 and 5 :
libs.dsp4 = {'dspsrcs4','dspsnks4','dsparch4',...
             'dspsrcs3','dspsnks3',...
             'dspddes3','dsparch3','dspadpt3','dspmlti3',...
             'dspparest3','dspspect3','dsplp',...
             'dspxfrm3','dspstat3','dspquant2','dspsigops',...
             'dspmathops','dspmtrx3','dspfactors','dspinverses','dspsolvers',...
             'dsppolyfun',...
             'dspswit3','dspbuff3','dspindex','dspsigattribs',...
             'dspwin32','dspmlti4'};

% [EOF] dspliblist.m
