function c=csl_summ_table(varargin)
%Summary Table
%   This component inserts a table which lists several
%   Simulink objects and their properties.
%

%   Copyright 1997-2004 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2004/04/15 00:20:38 $

z=zslmethods;

if ~strncmp(get(0,'lang'),'en',2)
   mdlImg=[];
   sysImg=[];
   blkImg=[];
   sigImg=[];
else
   cdata=getslcdata(z);
   mdlImg=cdata.ModelLarge;
   sysImg=cdata.SystemLarge;
   blkImg=cdata.BlockLarge;
   sigImg=cdata.SignalLarge;
   clear cdata
end

r=rpt_summ_table;

r=set_table(r,...
   'Model',...
   'csl_mdl_loop',...
   'propmodel',...
   {'Name' 'Description' 'FileName'},...
   '',...
   mdlImg);

r=set_table(r,...
   'System',...
   'csl_sys_loop',...
   'propsystem',...
   {'Name' 'Description'},...
   '',...
   sysImg);

r=set_table(r,...
   'Block',...
   'csl_blk_loop',...
   'propblock',...
   {'Name' '%<SplitDialogParameters>'},...
   '',...
   blkImg);

r=set_table(r,...
   'Signal',...
   'csl_sig_loop',...
   'propsignal',...
   {'Name' 'ParentBlock' 'CompiledPortDataType'},...
   '',...
   sigImg);

c=rptgenutil('EmptyComponentStructure','csl_summ_table');
c=class(c,c.comp.Class,rptcomponent,z,r);
c=buildcomponent(c,varargin{:});

if ~isempty(varargin)
   c=refresh_loop_comps(c.rpt_summ_table,c);
end
