/*
 * @(#)unwrap_d_ropf_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:36 2004
 *
 *		built from:	unwrap_d_ropf_rt.c
 */

#ifndef unwrap_d_ropf_rt_h
#define unwrap_d_ropf_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_Unwrap_D_ROPF(const real_T    *u,
                               real_T    *y, 
                               real_T    *prev,
                               real_T    *pcumsum,                          
                         const real_T     cutoff,
                               int_T      inCols,
                               int_T      inRows,
                               boolean_T *firstime
                        );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* unwrap_d_ropf_rt_h */
