/*
 * @(#)allpole_df_a0scale_dd_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:11 2004
 *
 *		built from:	allpole_df_a0scale_dd_rt.c
 */

#ifndef allpole_df_a0scale_dd_rt_h
#define allpole_df_a0scale_dd_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_AllPole_DF_A0Scale_DD( 
                       const real_T      *u,
                       real_T            *y,
                       real_T     * const mem_base,
                       int32_T             *offset_mem,
                       const int_T        numDelays,
                       const int_T        sampsPerChan,
                       const int_T        numChans,
                       const real_T  * const a,
                       const boolean_T    one_fpf);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* allpole_df_a0scale_dd_rt_h */
