/*
 * @(#)2chabank_fr_df_zz_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:23 2004
 *
 *		built from:	2chabank_fr_df_zz_rt.c
 */

#ifndef 2chabank_fr_df_zz_rt_h
#define 2chabank_fr_df_zz_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_2ChABank_Fr_DF_ZZ(
    const creal_T       *u,      
          creal_T       *filtLongOutputBase,
          creal_T       *filtShortOutputBase,            
          creal_T       *tap0,              
          creal_T       *sums,              
    const creal_T *const filtLong,  
    const creal_T *const filtShort,          
          int32_T         *tapIdx,            
          int32_T         *phaseIdx,
    const int_T          numChans,
    const int_T          inFrameSize,
    const int_T          polyphaseFiltLenLong,
    const int_T          polyphaseFiltLenShort
);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* 2chabank_fr_df_zz_rt_h */
