/*
 * @(#)2chsbank_df_zz_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:23 2004
 *
 *		built from:	2chsbank_df_zz_rt.c
 */

#ifndef 2chsbank_df_zz_rt_h
#define 2chsbank_df_zz_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_2ChSBank_DF_ZZ(
    const creal_T        *inputToLongFilt, 
    const creal_T        *inputToShortFilt, 
          creal_T        *out,
          creal_T        *longFiltTapBuf,
          creal_T        *shortFiltTapBuf,              
    const creal_T *const  longFilt,  
    const creal_T *const  shortFilt,          
          int32_T          *longFiltTapIdx, 
          int32_T          *shortFiltTapIdx, 
    const int_T           numChans,
    const int_T           inFrameSize,          
    const int_T           polyphaseLongFiltLen,
    const int_T           polyphaseShortFiltLen
);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* 2chsbank_df_zz_rt_h */
