// advantecherr.h : Advantech error declarations
// Copyright 1998-2004 The MathWorks, Inc.
// Coded by OPTI-NUM solutions (Pty) Ltd.
// $Revision: 1.1.6.2 $  $Date: 2004/04/08 20:49:30 $

#ifndef __ADVANTECHERR_H_
#define __ADVANTECHERR_H_

// Some Advantech-specific macros for returning an error from the Advantech Drivers
// Use MAKE_ADVANTECH_ERROR for Advantech's errors, and DEFINE_ERROR for internal errors.
#define DAQERROR_BASE  (-1000)
#define DEFINE_ERROR(_x) (DAQERROR_BASE+_x)
#define MAKE_ADVANTECH_ERROR(x) DEFINE_ERROR(x+0x100)
#define RETURN_ADVANTECH(call) {HRESULT stat=(HRESULT) call & ((1<<12)-1); if (stat!=0) return MAKE_ADVANTECH_ERROR(stat);}

// Some internal error codes: Their error codes for internal use
#define EA_MemoryAllocateFailed         MAKE_ADVANTECH_ERROR(1)
#define EA_ConfigDataLost               MAKE_ADVANTECH_ERROR(2)
#define EA_InvalidDeviceHandle          MAKE_ADVANTECH_ERROR(3)
#define EA_AIConversionFailed           MAKE_ADVANTECH_ERROR(4)
#define EA_AIScaleFailed                MAKE_ADVANTECH_ERROR(5)
#define EA_SectionNotSupported          MAKE_ADVANTECH_ERROR(6)
#define EA_InvalidChannel               MAKE_ADVANTECH_ERROR(7)
#define EA_InvalidGain                  MAKE_ADVANTECH_ERROR(8)
#define EA_DataNotReady                 MAKE_ADVANTECH_ERROR(9)
#define EA_InvalidInputParam            MAKE_ADVANTECH_ERROR(10)
#define EA_NoExpansionBoardConfig       MAKE_ADVANTECH_ERROR(11)
#define EA_InvalidAnalogOutValue        MAKE_ADVANTECH_ERROR(12)
#define EA_ConfigIoPortFailed           MAKE_ADVANTECH_ERROR(13)
#define EA_CommOpenFailed               MAKE_ADVANTECH_ERROR(14)
#define EA_CommTransmitFailed           MAKE_ADVANTECH_ERROR(15)
#define EA_CommReadFailed               MAKE_ADVANTECH_ERROR(16)
#define EA_CommReceiveFailed            MAKE_ADVANTECH_ERROR(17)
#define EA_CommConfigFailed             MAKE_ADVANTECH_ERROR(18)
#define EA_CommChecksumError            MAKE_ADVANTECH_ERROR(19)
#define EA_InitError                    MAKE_ADVANTECH_ERROR(20)
#define EA_DMABufAllocFailed            MAKE_ADVANTECH_ERROR(21)
#define EA_IllegalSpeed                 MAKE_ADVANTECH_ERROR(22)
#define EA_ChanConflict                 MAKE_ADVANTECH_ERROR(23)
#define EA_BoardIDNotSupported          MAKE_ADVANTECH_ERROR(24)
#define EA_FreqMeasurementFailed        MAKE_ADVANTECH_ERROR(25)
#define EA_CreateFileFailed             MAKE_ADVANTECH_ERROR(26)
#define EA_FunctionNotSupported         MAKE_ADVANTECH_ERROR(27)
#define EA_LoadLibraryFailed            MAKE_ADVANTECH_ERROR(28)
#define EA_GetProcAddressFailed         MAKE_ADVANTECH_ERROR(29)
#define EA_InvalidDriverHandle          MAKE_ADVANTECH_ERROR(30)
#define EA_InvalidModuleType            MAKE_ADVANTECH_ERROR(31)
#define EA_InvalidInputRange            MAKE_ADVANTECH_ERROR(32)
#define EA_InvalidWindowsHandle         MAKE_ADVANTECH_ERROR(33)
#define EA_InvalidCountNumber           MAKE_ADVANTECH_ERROR(34)
#define EA_InvalidInterruptCount        MAKE_ADVANTECH_ERROR(35)
#define EA_InvalidEventCount            MAKE_ADVANTECH_ERROR(36)
#define EA_OpenEventFailed              MAKE_ADVANTECH_ERROR(37)
#define EA_InterruptProcessFailed       MAKE_ADVANTECH_ERROR(38)
#define EA_InvalidDOSetting             MAKE_ADVANTECH_ERROR(39)
#define EA_InvalidEventType             MAKE_ADVANTECH_ERROR(40)
#define EA_EventTimeOut                 MAKE_ADVANTECH_ERROR(41)
#define EA_InvalidDmaChannel            MAKE_ADVANTECH_ERROR(42)
#define EA_IntDamChannelBusy            MAKE_ADVANTECH_ERROR(43)
#define EA_KeInvalidHandleValue         MAKE_ADVANTECH_ERROR(100)
#define EA_KeFileNotFound               MAKE_ADVANTECH_ERROR(101)
#define EA_KeInvalidHandle              MAKE_ADVANTECH_ERROR(102)
#define EA_KeTooManyCmds                MAKE_ADVANTECH_ERROR(103)
#define EA_KeInvalidParameter           MAKE_ADVANTECH_ERROR(104)
#define EA_KeNoAccess                   MAKE_ADVANTECH_ERROR(105)
#define EA_KeUnsuccessful               MAKE_ADVANTECH_ERROR(106)
#define EA_KeConInterruptFailure        MAKE_ADVANTECH_ERROR(107)
#define EA_KeCreateNoteFailure          MAKE_ADVANTECH_ERROR(108)
#define EA_KeInsufficientResources      MAKE_ADVANTECH_ERROR(109)
#define EA_KeHalGetAdapterFailure       MAKE_ADVANTECH_ERROR(110)
#define EA_KeOpenEventFailure           MAKE_ADVANTECH_ERROR(111)
#define EA_KeAllocCommBufFailure        MAKE_ADVANTECH_ERROR(112)
#define EA_KeAllocMdlFailure            MAKE_ADVANTECH_ERROR(113)
#define EA_KeBufferSizeTooSmall         MAKE_ADVANTECH_ERROR(114)
// Internally defined errors.
#define E_DEVCONFIG                     DEFINE_ERROR(1)
#define E_INPRANGE                      DEFINE_ERROR(2)
#define E_CHANCONFIG                    DEFINE_ERROR(3)
#define E_CHANORDER                     DEFINE_ERROR(4)
#define E_CHANDELETE                    DEFINE_ERROR(5)
#define E_INPUNKNOWN                    DEFINE_ERROR(6)
#define E_BUFDRVHANDLE                  DEFINE_ERROR(7)
#define E_ADVALLOCDMA                   DEFINE_ERROR(8)
#define E_INVALID_DEVICE_ID             DEFINE_ERROR(9)
#define E_DEVICE_RUNNING                DEFINE_ERROR(10)
#define E_IT_SNGLDIFF                   DEFINE_ERROR(11)
#define E_PORT_DIR                      DEFINE_ERROR(12)
#define E_TRANSFER_ERROR                DEFINE_ERROR(13)
#define E_DEMOBOARD						DEFINE_ERROR(14)
#define E_AOCHANEXT						DEFINE_ERROR(15)
#define E_AOHWMULTCHAN					DEFINE_ERROR(16)
#define E_AOHWCHANADD					DEFINE_ERROR(17)
#define E_BUFSIZELARGE					DEFINE_ERROR(18)
#define E_BUFDMASIZE					DEFINE_ERROR(19)
#define E_CHANNUM						DEFINE_ERROR(20)
#define E_NOTDMACHAN					DEFINE_ERROR(21)

// No errors in the rc file because those are unsigned...
#endif // __ADVANTECHERR_H_
