// advantech.idl : IDL source for advantech.dll
//
// This file will be processed by the MIDL tool to
// produce the type library (advantech.tlb) and marshalling code.

// Copyright 2002-2003 The MathWorks, Inc.
// $Revision: 1.1.6.2 $  $Date: 2003/12/04 18:39:22 $

import "oaidl.idl";
import "ocidl.idl";
import "daqmex.idl";

[
	object,
	uuid(FACDD47E-089A-4ae2-A951-661F95723898),
	dual,
	helpstring("IadvantechAin Interface"),
	pointer_default(unique)
]
interface  IadvantechAin : IDispatch
{};

[
	object,
	uuid(946FA2DD-F51D-48f7-88CB-50E6F05E6266),
	dual,
	helpstring("IadvantechAout Interface"),
	pointer_default(unique)
]
interface  IadvantechAout : IDispatch
{};

[
	object,
	uuid(5EF1D532-045C-4096-9598-F74966F47AF6),
	dual,
	helpstring("IadvantechDio Interface"),
	pointer_default(unique)
]
interface  IadvantechDio : IUnknown
{};

[
	uuid(62929565-6CA0-457F-997C-FEE270BB6432),
	version(1.0),
	helpstring("advantech 1.0 Type Library")
]

library ADVANTECHLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(98EAB8A1-7BA1-4099-B703-B70C8A507F5F),
		helpstring("advantech Class")
	]
	coclass advantechadapt
	{
		[default] interface ImwAdaptor;
	};

	[
		uuid(8B00CFAD-83C2-49e7-91AB-5833BDE24A2F),
		helpstring("advantechAin Class")
	]
	coclass advantechAin
	{
		[default] interface IadvantechAin;
		interface ImwDevice;
		interface ImwInput;
	};

	[
		uuid(759C2567-9E65-460a-AC04-C7AA93F29B93),
		helpstring("advantechAout Class")
	]
	coclass advantechAout
	{
		[default] interface IadvantechAout;
		interface ImwDevice;
		interface ImwOutput;
	};

	[
		uuid(1D5D1242-C670-4aef-A885-07FBEE0A530A),
		helpstring("advantechDio Class")
	]
	coclass advantechDio
	{
		[default] interface IadvantechDio;
		interface ImwDevice;
		interface ImwDIO;
	};
};
