function str = default_informer_text

% Copyright 2003 The MathWorks, Inc.

    str = [
        '<table>' 10 ...
        '<tr> <td align=center>' 10 ...
        '<h3>Coverage Display Window</h3>' 10 ...
        'Click on a shaded block to see coverage information.' 10 ...
        'Use context menus to toggle between click-based and mouse-over object selection.' 10 ...
        '</td> </tr>' 10 ...
        '</table>' 10 ...
        ];

    
