function name = get_blk_typ_str(index)
%
% Utility function to store and retreive
% a block type from its enumeration
%

%   Copyright 1990-2003 The MathWorks, Inc.
%   $Revision: 1.24.2.8 $  $Date: 2004/05/04 02:02:46 $

  persistent BLOCK_TYPE_STRINGS;
  persistent LENGTH_BLCKS;

  if isempty(BLOCK_TYPE_STRINGS),
    [BLOCK_TYPE_STRINGS, LENGTH_BLCKS] = set_sl_strings;
  end

  if index > LENGTH_BLCKS,
    error('Block name does not exist');
  end

  if (index<0)
    % Special cases
    switch(index)
     case -99
      name = 'EML Script';
     otherwise,
      error(['Invalid index: ' num2str(index)]);
    end
  else
    name = deblank(BLOCK_TYPE_STRINGS(index,:));
  end


function [strs,lngth] = set_sl_strings,

  strs = strvcat( ...
      'Absolute value', ...
      'Action port', ...
      'Actuator', ...
      'ArithShift', ...
      'Assertion', ...
      'Assignment', ...
      'Backlash', ...
      'Bias', ...
      'Bus assignment', ...
      'Bus creator', ...
      'Bus selector', ...
      'Switch-Case', ...
      'Clock', ...
      'Combinatorial logic', ...
      'Complex to magnitude angle', ...
      'Complex to real imag', ...
      'Constant', ...
      'Data store memory', ...
      'Data store read', ...
      'Data store write', ...
      'Data type conv', ...
      'Deadzone', ...
      'Demux', ...
      'Derivative', ...
      'Digital clock', ...
      'Discrete filter', ...
      'Discrete integrator', ...
      'Discrete pulse generator', ...
      'Discrete state space', ...
      'Discrete ck', ...
      'Discrete transfer fcn', ...
      'Discrete zero pole', ...
      'Display', ...
      'Elementary math', ...
      'Enable port', ...
      'For', ...
      'Frame conversion', ...
      'From', ...
      'From file', ...
      'From workspace', ...
      'Function', ...
      'Gain', ...
      'Goto', ...
      'Goto tag visibility', ...
      'Ground', ...
      'Hidden Buffer', ...
      'Hit crossing', ...
      'If', ...
      'Initial condition', ...
      'Inport', ...
      'InportShadow', ...
      'Integrator', ...
      'Logic', ...
      'Lookup', ...
      '2d lookup', ...
      'Magnitude angle to complex', ...
      'Math fcn', ...
      'MATLAB fcn', ...
      'MATLAB scripting', ...
      'Memory', ...
      'Merge', ...
      'Minmax', ...
      'Signal Viewer Scope', ...
      'Model Reference', ...
      'Mpswitch', ...
      'Mux', ...
      'Note', ...
      'Opaque', ...
      'Outport', ...
      'PM Component', ...
      'PM I/O Port', ...
      'Post', ...
      'Probe', ...
      'Product', ...
      'Pulse Generator', ...
      'Quantizer', ...
      'Random number', ...
      'Rate Transition', ...
      'Rate limiter', ...
      'Real imag to complex', ...
      'Reference', ...
      'Relay', ...
      'Relational operator', ...
      'Reset integrator', ...
      'Rounding fcn', ...
      'Saturate', ...
      'Scope', ...
      'Selector', ...
      'Sensor', ...
      'S function', ...
      'Signal generator', ...
      'Signal specification',...
      'Signum', ...
      'Sine wave', ...
      'State space', ...
      'Step', ...
      'Stop', ...
      'Subsystem', ...
      'Sum', ...
      'Switch', ...
      'Terminator', ...
      'To file', ...
      'To workspace', ...
      'Transfer fcn', ...
      'Transport delay', ...
      'Trigger port', ...
      'Trigonometry fcn', ...
      'Uniform random number', ...
      'Unit delay', ...
      'Variable transport delay', ...
      'While', ...
      'Width', ...
      'Zero pole', ...
      'Zoh' ...
      );

  [lngth,c] = size(strs);

