/* $Revision: 1.16.2.2 $ */

/*
 * @(#)PACKAGE.h    generated by: makeheader    Wed Apr 25 13:12:51 1990
 *
 *		built from:	makeheader.c
 */

#ifndef PACKAGE_h
#define PACKAGE_h

#if defined(MSWIND) && defined(_MSC_VER)
#if defined(EXPORT)
#undef EXPORT
#endif
#if 0
#define IMPORT __declspec(dllimport)
#define EXPORT __declspec(dllexport)
#define EXPORT_ONLY __declspec(dllexport)
#define FRIEND __declspec(dllexport)
#else
#define IMPORT extern
#define EXPORT
#define EXPORT_ONLY
#define FRIEND
#endif
#define IMPORT_CLASS __declspec(dllimport)
#define IMPORT_VAR __declspec(dllimport)
#define FRIEND_CLASS __declspec(dllexport)
#define PUBLISHED_CLASS __declspec(dllexport)
#define EXPORT_CLASS __declspec(dllexport)
#define EXPORT_VAR __declspec(dllexport)
#define EXPORT_FCN __declspec(dllexport)
#define FRIEND_FCN __declspec(dllexport)
#define PUBLISHED_FCN __declspec(dllexport)
#define IMPORT_FCN __declspec(dllimport)
#else
#define IMPORT extern
#define IMPORT_CLASS
#define IMPORT_VAR extern
#define FRIEND
#define EXPORT
#define FRIEND_CLASS
#define PUBLISHED_CLASS
#define EXPORT_CLASS 
#define EXPORT_VAR
#define EXPORT_ONLY
#define EXPORT_FCN
#define PUBLISHED_FCN
#define FRIEND_FCN
#define IMPORT_FCN
#endif



#define PUBLIC
#define PACKAGE
#define PUBLISHED
#define PRIVATE	static

#define BEGIN_EXPORT
#define END_EXPORT

#define BEGIN_FRIEND
#define END_FRIEND

#define BEGIN_EXPORT_ONLY
#define END_EXPORT_ONLY

#define BEGIN_PUBLIC
#define END_PUBLIC

#define BEGIN_PACKAGE
#define END_PACKAGE

#define BEGIN_PUBLISHED
#define END_PUBLISHED

/*
 * Make inline keyword work with older versions of C
 */
#if !defined(__cplusplus) && (__STDC_VERSION__ < 199901L)
#  if defined(__GNUC__)
#    define inline extern __inline__
#  elif defined(__hpux)
#    define inline static __inline
#  elif defined(_MSC_VER)
#    define inline __inline
#  endif
#endif

#endif /* PACKAGE_h */
