/*
 * @(#)isfinite_r_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:28 2004
 *
 *		built from:	isfinite_r_rt.c
 */

#ifndef isfinite_r_rt_h
#define isfinite_r_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN int_T dspIsFinite32(float x);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* isfinite_r_rt_h */
