function names=makenames(prefix, nums)
%MAKENAMES Generate cell array of names for ADDCHANNEL/ADDLINE.
%
%    NAMES = MAKENAMES('PREFIX',INDEX) creates a M-by-1 cell array of 
%    strings, NAMES.  NAMES is generated by appending the string PREFIX 
%    with non-negative integers contained in the array INDEX of length M.
%
%    If used for named referencing, PREFIX must contain only letters, 
%    numbers and underscores and must begin with a letter, otherwise
%    PREFIX can contain any character.
%
%    MAKENAMES is intended for use with the function ADDCHANNEL/ADDLINE. 
%
%    Example:
%     If OBJ is an analog input object, then the following commands 
%     creates three channels named 'Chan1', 'Chan2' and 'Chan3', 
%     assigned to hardware channels [0 1 2]:
%
%       names=makenames('Chan', [1:3]);  
%       addchannel(OBJ, [0:2], names)
%
%    See also DAQHELP, ADDCHANNEL, ADDLINE.
%

%    CP 4-10-98
%    Copyright 1998-2003 The MathWorks, Inc.
%    $Revision: 1.10.2.4 $  $Date: 2003/08/29 04:40:59 $

ArgChkMsg = nargchk(2,2,nargin);
if ~isempty(ArgChkMsg)
    error('daq:makenames:argcheck', ArgChkMsg);
end

lnums=length(nums);

% Ensure that NUMS is a 1-D numerical array.
if ~isnumeric(nums) || any(floor(nums)~=nums) || any(nums<0) || lnums~=numel(nums),
   error('daq:makenames:argcheck', 'INDEX must be a vector consisting of non-negative integers.')
end

% Check for a non-string PREFIX or PREFIX being an array of strings.
if ~ischar(prefix) || size(prefix,1)~=1,
   error('daq:makenames:argcheck', 'PREFIX must be a string.')
end

% Ensure NUMS is always Nx1.
% Then concatenate PREFIX with each NUMS element.
nums=nums(:);

% Preallocate the names cell array.  A column vector is needed so that the output
% can be passed directly to a SET call.
names = cell(lnums,1);
for i=1:lnums,
   names{i}=[prefix int2str(nums(i))];
end