% function [bnds,pert,dc,dri,dcb,drib,dcd,drid,g,y,b] = ...
%   rub(M,K,I,J,opt,numits,contol,Kc,Kr,Ic,Ir,Jc,Jr,Fc,Fr,kc,kr,...
%   ic,ir,jc,sr,fc,fr,sc,sr,csc,csr,csF,nK,nI,nJ,nF,nc,nr,kcK,...
%   icI,jcJ,jrJ,fcF,dcb,drib,y,b,ldc,ldri,lg,lal)
% ユーザは、この関数を呼び出しません。

%   $Revision: 1.6.2.2 $  $Date: 2004/03/10 21:32:31 $
%   Copyright 1991-2002 by MUSYN Inc. and The MathWorks, Inc. 
