function h=scribeuaxes(varargin)
%SCRIBEUAXES creates the scribe underlay axes object
%  H=scribe.SCRIBEUAXES creates a scribeuaxes instance
%
%  See also PLOTEDIT

%   Copyright 1984-2003 The MathWorks, Inc.

if nargin>0 && isa(handle(varargin{1}),'hg.figure')
    fig = varargin{1};
    varargin(1)=[];
    nargs = nargin-1;
else
    fig = gcf;
    nargs = nargin;
end
h = scribe.scribeuaxes('Parent',fig,'Tag','scribeUnderlay');

set(h,'Position',[0,0,1,1], ...
    'Visible','off', ...
    'HandleVisibility','off', ...
    'XLimMode','manual', ...
    'YLimMode','manual', ...
    'ZLimMode','manual', ...
    'NextPlot','add', ...
    'Xlimmode','manual',...
    'Ylimmode','manual',...
    'Zlimmode','manual',...
    'Climmode','manual',...
    'Alimmode','manual');
hasbehavior(double(h),'zoom',false);
hasbehavior(double(h),'rotate',false);
setappdata(double(h),'ScribeGroup',h);
setappdata(double(h),'scribeobject','on');
setappdata(ancestor(h,'figure'),'Scribe_ScribeUnderlay',double(h));