/*
 * @(#)bsub_u_cc_c_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:17 2004
 *
 *		built from:	bsub_u_cc_c_rt.c
 */

#ifndef bsub_u_cc_c_rt_h
#define bsub_u_cc_c_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_BSub_U_CC_C(
        const creal32_T *pU,
        const creal32_T *pb,
              creal32_T  *x,
        const int_T       N,
        const int_T       P
        );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* bsub_u_cc_c_rt_h */
