/*
 * @(#)bsub_u_zz_z_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:18 2004
 *
 *		built from:	bsub_u_zz_z_rt.c
 */

#ifndef bsub_u_zz_z_rt_h
#define bsub_u_zz_z_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_BSub_U_ZZ_Z(
        const creal_T *pU,
        const creal_T *pb,
              creal_T  *x,
        const int_T     N,
        const int_T     P
        );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* bsub_u_zz_z_rt_h */
