/*
 * @(#)fsub_u_zz_z_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:19 2004
 *
 *		built from:	fsub_u_zz_z_rt.c
 */

#ifndef fsub_u_zz_z_rt_h
#define fsub_u_zz_z_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_FSub_U_ZZ_Z(
        const creal_T *pL,
        const creal_T *pb,
              creal_T  *x,
        const int_T     N,
        const int_T     P
        );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* fsub_u_zz_z_rt_h */
