function p_specialTIDatatypes(td)
% Private. Add TI-specific native data types into the typedef list.
% Copyright 2002-2003 The MathWorks, Inc.
%   $Revision: 1.1.4.1 $  $Date: 2003/11/30 23:14:07 $

TI_types = { ...
        'Void', 'void', ...
        'Float', 'float', ...
        'Double', 'double', ...
        'Long', 'long', ...
        'Int', 'int', ...
        'Short', 'short', ...
        'Char', 'char' };

for i=1:length(TI_types)/2
    add(td,TI_types{i*2-1},TI_types{i*2});
end

% [EOF] p_specialTIDatatypes.m