/*
 * @(#)hist_d_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:25 2004
 *
 *		built from:	hist_d_rt.c
 */

#ifndef hist_d_rt_h
#define hist_d_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_HistD(
        const real_T *u_data,
        real_T *y,
        int_T nChans,
        int_T nSamps,
        real_T umin,
        real_T umax, 
        int_T Nbins,
        real_T idelta);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* hist_d_rt_h */
