%DSPSTARTUP Default Simulink model settings for DSP systems.
%   Changes the default Simulink model settings to values
%   more appropriate for DSP systems.
%
%   Include a call to this script in your own startup.m
%   file in order to automatically install these defaults
%   each time you run MATLAB.
%
%   See the Model Parameters section of the Using Simulink
%   manual for more information on model parameter settings.

% Copyright 1995-2004 The MathWorks, Inc.
% $Revision: 1.10.4.2 $ $Date: 2004/04/12 23:05:20 $

set_param(0, ...
	'SingleTaskRateTransMsg','error', ...
	'Solver',                'fixedstepdiscrete', ...
	'SolverMode',            'SingleTasking', ...
	'StartTime',             '0.0', ...
	'StopTime',              'inf', ...
	'FixedStep',             'auto', ...
	'SaveTime',              'off', ...
	'SaveOutput',            'off', ...
	'AlgebraicLoopMsg',      'error', ...
	'InvariantConstants',    'on');
set_param(getActiveConfigSet(0), 'RollThreshold', 2);

fprintf('\nChanged default Simulink settings for DSP systems (dspstartup.m).\n\n');

% [EOF] dspstartup.m
