function hprintbtns = render_sqprintbtns(htoolbar, hMainFig)
%RENDER_SQPRINTBTNS Render the "New", "Open", "Save", "Print" and 
%"Print Preview" toolbar buttons.
%   HPRINTBTNS = RENDER_SPTPRNITBTNS(HTOOLBAR) creates the print portion of a toolbar 
%   on a toolbar parented by HTOOLBAR and return the handles to the buttons.

%   Copyright 1988-2002 The MathWorks, Inc.
%   $Revision: 1.1 $  $Date: 2002/10/25 22:04:10 $ 

%%load sptviewicons;%Load new, print and print preview icons
load mwtoolbaricons;% Load new, open, save, print and print preview icons.

pushbtns = {newdoc,...
            opendoc,...
            savedoc,...
            printdoc,...
            printprevdoc};

tooltips = {'New Session',...
            'Open Session',...
            'Save Session',...
            'Print',...
            'Print Preview'};

tags = {'newsessiontb',...
        'opensessiontb',...
        'savesessiontb',...
        'printresp',...
        'printprev'};

cbs=sqfmenu_callbacks(hMainFig);
btncbs = {cbs.new,...
          cbs.open,...
          cbs.save,...
          cbs.print,...
          cbs.printpreview};

  % Render the PushButtons
for i = 1:length(pushbtns),
   hprintbtns(i) = uipushtool('Cdata',pushbtns{i},...
        'Parent', htoolbar,...
        'ClickedCallback',btncbs{i},...
        'Tag',            tags{i},...
        'Tooltipstring',  tooltips{i});
end

% [EOF]
