function hprintbtns = render_vqprintbtns(htoolbar, hMainFig)
%RENDER_VQPRINTBTNS Render the "New", "Open", "Save", "Print" and 
%   "Print Preview" toolbar buttons.
%
%   Copyright 1988-2003 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $  $Date: 2003/04/11 18:17:46 $ 

%%load sptviewicons;%Load new, print and print preview icons
load mwtoolbaricons;% Load new, open, save, print and print preview icons.

pushbtns = {newdoc,...
            opendoc,...
            savedoc,...
            printdoc,...
            printprevdoc};

tooltips = {'New Session',...
            'Open Session',...
            'Save Session',...
            'Print',...
            'Print Preview'};

tags = {'newsessiontb',...
        'opensessiontb',...
        'savesessiontb',...
        'printresp',...
        'printprev'};

cbs=vqfmenu_callbacks(hMainFig);
btncbs = {cbs.new,...
          cbs.open,...
          cbs.save,...
          cbs.print,...
          cbs.printpreview};

  % Render the PushButtons
for i = 1:length(pushbtns),
   hprintbtns(i) = uipushtool('Cdata',pushbtns{i},...
        'Parent', htoolbar,...
        'ClickedCallback',btncbs{i},...
        'Tag',            tags{i},...
        'Tooltipstring',  tooltips{i});
end

% [EOF]
