function hfile = render_vqfilemenu(hFig, pos)
%RENDER_VQFILEMENU Render the File menu of the VQ DESIGN (GLA) GUI
% Copyright 1988-2003 The MathWorks, Inc.
% $Revision: 1.1.6.1 $  $Date: 2003/04/11 18:17:44 $ 
strs = {xlate('&File'), ...
    xlate('&New Session'), ...
    xlate('&Open Session'), ...
    xlate('&Save Session'), ...
    xlate('Save Session As...'), ...
    xlate('Close'), ...
    xlate('&Export...'), ...
    xlate('Page Setup...'), ...
    xlate('Print Setup...'), ...
    xlate('Print Preview...'), ...
    xlate('Print...'), ...
    xlate('Full View Analysis')};
cb = vqfmenu_callbacks(hFig);
cbs = {'', ...
    cb.new, ...
    cb.open, ...
    cb.save, ...
    cb.saveas, ...
    cb.close, ...  
    cb.export, ...
    cb.pagesetup, ... 
    cb.printsetup, ... 
    cb.printpreview, ...
    cb.print, ...
    cb.printtofigure};
tags = {'file', ...
    'newwindow', ...
    'opensession', ...
    'savesession', ...
    'savesessionas', ...
    'close', ...
    'export', ...
    'pagesetup', ...
    'printsetup', ...
    'printpreview', ...
    'print', ...
    'printtofigure'};
sep = {'off', ...
    'off', ...
    'off', ...
    'off', ...
    'off', ...
    'off', ...
    'on', ...
    'on', ...
    'off', ...
    'off', ...
    'off', ...
    'on'};
accel = {'', ...
    'N', ...
    'O', ...
    'S', ...
    '', ...
    'W', ...
    'E', ...
    '', ...
    '', ...
    '', ...
    'P', ...
    ''};
hfile = addmenu(hFig,pos,strs,cbs,tags,sep,accel);

% % [EOF]
