/*
 * @(#)burg_a_c_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:14 2004
 *
 *		built from:	burg_a_c_rt.c
 */

#ifndef burg_a_c_rt_h
#define burg_a_c_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_Burg_A_C(const int_T      N,             /* Input array length */
                    const int_T      order,         /* Order of estimation */
                    const creal32_T *u,             /* Input pointer */
                          creal32_T *ef,            /* Intermediate variable */
                          creal32_T *eb,            /* Intermediate variable */
                          creal32_T *anew,          /* Intermediate AR coeffients */
                          creal32_T *Acoef,         /* A - Output pointer */
                          real32_T  *Error
                    );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* burg_a_c_rt_h */
