function file = dicom_open_msg(file, mode)
%DICOM_OPEN_MSG  Open the next DICOM message in the pool for processing.
%   FILE = DICOM_OPEN_MSG(FILE, 'r') opens the next DICOM message in the
%   pool for reading.
%
%   FILE = DICOM_OPEN_MSG(FILE, 'w') opens the next DICOM message in the
%   pool for writing.
%
%   Note: The pool of messages is generated by DICOM_GET_MSG.

%   Copyright 1993-2003 The MathWorks, Inc.
%   $Revision: 1.4.4.2 $  $Date: 2003/08/01 18:10:45 $

% Go to next message in the pool.
file.Current_Message = file.Current_Message + 1;

% Open the message.
if (isequal(file.Location, 'Local'))
    
    switch (lower(mode))
    case 'r'
        
        file.FID = fopen(file.Messages{file.Current_Message}, 'r', 'ieee-le');
        
        if (file.FID < 0)
            
            error('Images:dicom_open_msg:fileOpen', ...
                  'Could not open "%s" for reading', ...
                  file.Messages{file.Current_Message});
            
        end
    
    case 'w'

        file.FID = fopen(file.Messages{file.Current_Message}, 'w', 'ieee-le');

        if (file.FID < 0)
            
            error('Images:dicom_open_msg:fileOpen', ...
                  'Could not open "%s" for writing', ...
                  file.Messages{file.Current_Message});
            
        end
        
    otherwise
        
        error('Images:dicom_open_msg:openMode', 'Mode must be either ''r'' or ''w''.')
        
    end
    
    % Set local files to default transfer syntax (for fragments).
    % DICOM_SET_MMETA_ENCODING will change this if appropriate.
    file.Current_Endian = 'ieee-le';
    file.Pixel_Endian = 'ieee-le';
    file.Current_VR = 'Implicit';
    
else
    
    error('Images:dicom_open_msg:localOnly', 'Network messages are not yet supported.')
    
end

