function q = iscpstruct(t)
%ISCPSTRUCT True for control point structure.
%   Q = ISCPSTRUCT(T) returns true if and only if T is a structure array
%   with the standard CPSTRUCT fields produced by CPSELECT.
% 
%   See also CPSELECT, CP2TFORM, CPSTRUCT2PAIRS.

%   Copyright 1993-2003 The MathWorks, Inc.
%   $Revision: 1.4.4.1 $ $Date: 2003/01/26 05:59:55 $

q = isa(t,'struct') ...
    & isfield(t,'inputPoints') ...
    & isfield(t,'basePoints') ...
    & isfield(t,'inputBasePairs') ...
    & isfield(t,'ids') ...
    & isfield(t,'inputIdPairs') ...
    & isfield(t,'baseIdPairs') ...
    & isfield(t,'isInputPredicted') ...
    & isfield(t,'isBasePredicted');
