/*
 * @(#)window_nch_r_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:37 2004
 *
 *		built from:	window_nch_r_rt.c
 */

#ifndef window_nch_r_rt_h
#define window_nch_r_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_WindowNchR(int_T nRows, int_T nChans, real32_T *y, const real32_T *u, real32_T *winPtr);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* window_nch_r_rt_h */
