function specdlg(this)
% Opens and manages the "Desired Response" dialog

%   Author(s): Kamesh Subbarao, P. Gahinet
%   Copyright 1990-2004 The MathWorks, Inc.
Dlg = this.SpecDialog;
if isempty(Dlg) || ~ishandle(Dlg)
   Dlg = LocalCreateDlg(this);
   this.SpecDialog = Dlg;
end
set(Dlg,'Visible','on');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% LOCALCREATEDLG
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function Dlg = LocalCreateDlg(this)
%
DlgH = 21;
DlgW = 78;
UIColor = get(0,'DefaultUIControlBackgroundColor');
Dlg = figure('Name','Desired Response', ...
    'Visible','off', ...
    'Resize','off',...
    'MenuBar','none', ...
    'Units','character',...
    'Position',[0 0 DlgW DlgH], ...
    'Color', UIColor, ...
    'IntegerHandle','off', ...
    'HandleVisibility','off',...
    'NumberTitle','off');
centerfig(Dlg,this.Parent);
set(Dlg,'CloseRequestFcn',{@localHide Dlg})

% Button group
xgap = 2;
BW = 10;  BH = 1.5; Bgap = 1;
X0 = DlgW - xgap - 4*BW - 3*Bgap;
Y0 = 0.5;
Handles.OK = uicontrol('Parent',Dlg, ...
   'Units','character', ...
   'Position',[X0 Y0 BW BH], ...
   'Callback',{@localOK Dlg this},...
   'String','OK');
X0 = X0+BW+Bgap;
uicontrol('Parent',Dlg, ...
   'Units','character', ...
   'Callback','', ...
   'Position',[X0 Y0 BW BH], ...
   'Callback',{@localHide Dlg},...
   'String','Cancel');
X0 = X0+BW+Bgap;
ud.Help = uicontrol('Parent',Dlg, ...
   'Units','character', ...
   'Position',[X0 Y0 BW BH], ...
   'String','Help');
X0 = X0+BW+Bgap;
uicontrol('Parent',Dlg, ...
   'Units','character', ...
   'Position',[X0 0.5 BW BH], ...
   'Callback',{@localApply Dlg this},...
   'String','Apply');

y0 = DlgH-2;
% uicontrol('Parent',Dlg, ...
%    'BackgroundColor',UIColor,...
%    'Style','text', ...
%    'String','Specify desired response as:', ...
%    'HorizontalAlignment','left', ...
%    'Units','character',...
%    'Position',[xgap y0 30 1.2]);
% 
% y0 = y0-1.5;
rb1 = uicontrol('Parent',Dlg, ...
   'Style','radiobutton', ...
   'String','Specify reference signal',...
   'Units','character',...
   'BackgroundColor',UIColor,...
   'Position',[xgap y0 60 1.2],...
   'Callback',{@localShowFrame Dlg 1},...
   'Value',1);
y0 = y0-1.5;
rb2 = uicontrol('Parent',Dlg, ...
   'Style','radiobutton', ...
   'String','Specify step response characteristics',...
   'Units','character',...
   'BackgroundColor',UIColor,...
   'Position',[xgap y0 60 1.2],...
   'Callback',{@localShowFrame Dlg 2},...
   'Value',0);
ud.Radio = [rb1;rb2];

FW = DlgW-2*xgap;
FH = y0-(2.5+BH);
FY = 1+BH;
ud.Frame = uicontrol('Parent',Dlg, ...
   'Style','frame', ...
   'Units','character',...
   'BackgroundColor',UIColor,...
   'Position',[xgap FY FW FH]);
ud.FrameLabel = uicontrol('Parent',Dlg, ...
   'BackgroundColor',UIColor,...
   'Style','text', ...
   'HorizontalAlignment','center', ...
   'Units','character',...
   'Position',[xgap+1 FY+FH-.75 1 1.2]);

% Create custom frame
y0 = FY+FH-3;
x0 = 2*xgap;
EW = DlgW - 2*x0 - 13;
h1 = uicontrol(Dlg, ...
   'Style','text', ...
   'String','Time vector:', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'Position',[x0 y0 12 1.2]);
h2 = uicontrol(Dlg, ...
   'Style','edit', ...
   'BackgroundColor','white', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'Position',[x0+13 y0 EW 1.4]);
y0 = y0-2.2;
h3 = uicontrol(Dlg, ...
   'Style','text', ...
   'String','Amplitude:', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'Position',[x0 y0 12 1.2]);
h4 = uicontrol(Dlg, ...
   'Style','edit', ...
   'BackgroundColor','white', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'Position',[x0+13 y0 EW 1.4]);
ud.CustomFrame = [h1;h2;h3;h4];

% Default step response settings
Xlim = get(getaxes(this),'Xlim');
Ylim = get(getaxes(this),'Ylim');
XScaleFactor = 10^floor(log10(Xlim(2)));
YScaleFactor = 10^floor(log10(diff(Ylim)));
T0 = Xlim(1);
Trise = T0 + 0.25 * XScaleFactor;
Tsettle = T0 + 0.75 * XScaleFactor;
Y0 = 0;
Yf = Y0 + YScaleFactor;

% Create step frame
y0 = FY+FH-3;
x01 = 2*xgap;
x02 = x01 + FW/2;
TW = 15;  
EW = FW/2-2*xgap-TW;
t11 = uicontrol(Dlg, ...
   'Style','text', ...
   'String','Initial value:', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'Position',[x01 y0 TW 1.2]);
e11 = uicontrol(Dlg, ...
   'Style','edit', ...
   'BackgroundColor','white', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'String',num2str(Y0), ...
   'Position',[x01+TW y0 EW 1.4]);
t12 = uicontrol(Dlg, ...
   'Style','text', ...
   'String','Final value:', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'Position',[x02 y0 TW 1.2]);
e12 = uicontrol(Dlg, ...
   'Style','edit', ...
   'BackgroundColor','white', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'String',num2str(Yf), ...
   'Position',[x02+TW y0 EW 1.4]);

y0 = y0-2;
t21 = uicontrol(Dlg, ...
   'Style','text', ...
   'String','Step time:', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'Position',[x01 y0 TW 1.2]);
e21 = uicontrol(Dlg, ...
   'Style','edit', ...
   'BackgroundColor','white', ...
   'HorizontalAlignment','left', ...
   'String',num2str(T0), ...
   'Units','character',...
   'Position',[x01+TW y0 EW 1.4]);

y0 = y0-3;
t31 = uicontrol(Dlg, ...
   'Style','text', ...
   'String','Rise time:', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'Position',[x01 y0 TW 1.2]);
e31 = uicontrol(Dlg, ...
   'Style','edit', ...
   'BackgroundColor','white', ...
   'HorizontalAlignment','left', ...
   'String',num2str(Trise), ...
   'Units','character',...
   'Position',[x01+TW y0 EW 1.4]);
t32 = uicontrol(Dlg, ...
   'Style','text', ...
   'String','% Rise:', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'Position',[x02 y0 TW 1.2]);
e32 = uicontrol(Dlg, ...
   'Style','edit', ...
   'BackgroundColor','white', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'String','90',...
   'Position',[x02+TW y0 EW 1.4]);

y0 = y0-2;
t41 = uicontrol(Dlg, ...
   'Style','text', ...
   'String','Settling time:', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'Position',[x01 y0 TW 1.2]);
e41 = uicontrol(Dlg, ...
   'Style','edit', ...
   'BackgroundColor','white', ...
   'HorizontalAlignment','left', ...
   'String',num2str(Tsettle), ...
   'Units','character',...
   'Position',[x01+TW y0 EW 1.4]);
t42 = uicontrol(Dlg, ...
   'Style','text', ...
   'String','% Settling:', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'Position',[x02 y0 TW 1.2]);
e42 = uicontrol(Dlg, ...
   'Style','edit', ...
   'BackgroundColor','white', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'String','5',...
   'Position',[x02+TW y0 EW 1.4]);

y0 = y0-2;
t51 = uicontrol(Dlg, ...
   'Style','text', ...
   'String','% Overshoot:', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'Position',[x01 y0 TW 1.2]);
e51 = uicontrol(Dlg, ...
   'Style','edit', ...
   'BackgroundColor','white', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'String','20',...
   'Position',[x01+TW y0 EW 1.4]);
t52 = uicontrol(Dlg, ...
   'Style','text', ...
   'String','% Undershoot:', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'Position',[x02 y0 TW 1.2]);
e52 = uicontrol(Dlg, ...
   'Style','edit', ...
   'BackgroundColor','white', ...
   'HorizontalAlignment','left', ...
   'Units','character',...
   'String','2',...
   'Position',[x02+TW y0 EW 1.4]);

ud.StepFrame = [e11;e12;e21;e31;e32;e41;e42;e51;e52;...
   t11;t12;t21;t31;t32;t41;t42;t51;t52];

% Listener to parent deletion
ud.Listener = handle.listener(this,'ObjectBeingDestroyed',{@localDelete Dlg});
% REVISIT: (src,data) delete(Dlg));

set(Dlg,'UserData',ud)

% Activate selected frame
localShowFrame([],[],Dlg,1)


%------------------

function localDelete(eventsrc,eventdata,Dlg)
% Deletes dialog when parent axes go away
delete(Dlg)


function localHide(eventsrc,eventdata,Dlg)
% Deletes dialog when parent axes go away
set(Dlg,'Visible','off')


function localOK(eventsrc,eventdata,Dlg,this)
% Deletes dialog when parent axes go away
Succeed = localApply(eventsrc,eventdata,Dlg,this);
if Succeed
   set(Dlg,'Visible','off')
end


function Succeed = localApply(eventsrc,eventdata,Dlg,this)
% Applies specification
ud = get(Dlg,'UserData');
rbv = get(ud.Radio,{'Value'});
Selection = find([rbv{:}]);
c = this.Constraint;
Succeed = false;
if Selection==1
   % Specifying reference signal
   ErrorTitle = 'Reference Signal Error';
   SignalWidth = prod(this.Constraint.SignalSize);
   % Evaluate time data
   t = localGetValue(ud.CustomFrame(2));  t = t(:);
   if ~isa(t,'double')
      errordlg('Invalid or undefined value for Time.',ErrorTitle,'modal'),return
   elseif any(diff(t)<=0)
      errordlg('Time points must be monotonically increasing.',ErrorTitle,'modal'),return
   end
   % Evaluate amplitude data
   y = localGetValue(ud.CustomFrame(4));
   if ~isa(y,'double')
      errordlg('Invalid or undefined value for Amplitude.',ErrorTitle,'modal'),return
   end
   if isempty(y) || isvector(y)
      y = y(:);
   end
   if size(y,1)~=length(t)
      errordlg('Row size of Amplitude must match length of Time.',ErrorTitle,'modal'),return
   elseif ~any(size(y,2)==[1 SignalWidth])
      errordlg('Column size of Amplitude must match signal width',ErrorTitle,'modal'),return
   end
   % Create transaction to allow for undo/redo
   Transaction = ctrluis.ftransaction('Set Reference');
   Transaction.Undo = {@localSetRef this c.ReferenceX c.ReferenceY this.RefVisible};
   Transaction.Redo = {@localSetRef this t y 'on'};
   % Plot reference
   localSetRef(this,t,y,'on')
   % Log transaction 
   this.Recorder.pushundo(Transaction)
else
   % Evaluate data
   ErrorTitle = 'Step Response Spec Error';
   y0 = localGetValue(ud.StepFrame(1));
   yf = localGetValue(ud.StepFrame(2));
   t0 = localGetValue(ud.StepFrame(3));
   Specs.RiseTime = localGetValue(ud.StepFrame(4));
   Specs.PercentRise = localGetValue(ud.StepFrame(5));
   Specs.SettlingTime = localGetValue(ud.StepFrame(6));
   Specs.PercentSettling = localGetValue(ud.StepFrame(7));
   Specs.OverShoot = localGetValue(ud.StepFrame(8));
   Specs.UnderShoot = localGetValue(ud.StepFrame(9));
   % Push constraint to editor
   Transaction = ctrluis.transaction(c,'Name','Step Constraint',...
      'OperationStore','on','InverseOperationStore','on');
   try
      c.stepspec(t0,y0,yf,Specs);
   catch
      [junk,errmsg]=strtok(lasterr,sprintf('\n'));
      errordlg(errmsg,ErrorTitle,'modal'),return
   end
   commit(Transaction)
   this.Recorder.pushundo(Transaction)
   % Update plot
   update(this)
end
Succeed = true;
   

function localShowFrame(eventsrc,eventdata,Dlg,Selection)
% Toggles frame for "Custom Signal" option
ud = get(Dlg,'UserData');
pos = get(ud.FrameLabel,'Position');
if Selection==1
   set(ud.Radio,{'Value'},{1;0})
   set(ud.StepFrame,'Visible','off')
   set(ud.CustomFrame,'Visible','on')
   pos(3) = 19;
   set(ud.FrameLabel,'String','Reference signal','Position',pos)
   set(ud.Help,'Callback','helpview([docroot ''/toolbox/sloptim/sloptim.map''],''desired_ref'')')
else
   set(ud.Radio,{'Value'},{0;1})
   set(ud.CustomFrame,'Visible','off')
   set(ud.StepFrame,'Visible','on')
   pos(3) = 23;
   set(ud.FrameLabel,'String','Step response specs','Position',pos)
   set(ud.Help,'Callback','helpview([docroot ''/toolbox/sloptim/sloptim.map''],''desired_step'')')
end 


function val = localGetValue(editbox)
% Evaluates string
str = get(editbox,'String');
if length(str)
   val = evalin('base',str,'[]');
else
   val = [];
end


function localSetRef(this,t,y,Vis)
% Store reference data
this.Constraint.ReferenceX = t;
this.Constraint.ReferenceY = y;
this.Constraint.ReferenceWeight = ones(size(t));
% Plot reference signal
refplot(this)
% Set visibility
this.RefVisible = Vis;
% Update limits
if strcmp(Vis,'on')
   this.Axes.send('ViewChanged')
end
