// #$Demo$#.idl : IDL source for #$Demo$#.dll

// Copyright 2002-2003 The MathWorks, Inc.
// $Revision: 1.1.6.3 $  $Date: 2003/08/29 04:44:22 $

// This file will be processed by the MIDL tool to 
// produce the type library (#$Demo$#.tlb) and the 
// adaptor's interface classes.


import "oaidl.idl";
import "ocidl.idl";
import "daqmex.idl";


// #$Demo$# Adaptor Type Library definition
[
	uuid(#$TypeGUID$#),
	version(1.0),
	helpstring("#$demo$# 1.0 Type Library")
]
library #$Demo$#Lib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

// #$Demo$# Adaptor - Adaptor Base class (includes ImwAdaptor interface definition)
	[
		uuid(#$AdaptorGUID$#),
		helpstring("#$Demo$#Adapt Class")
	]
	coclass #$Demo$#Adapt
	{
		[default] interface ImwAdaptor;
	};

#$StartAICut$#
// #$Demo$# Adaptor - Analog Input (includes ImwInput interface definition)
	[
		uuid(#$AnalogInputGUID$#),
		helpstring("#$Demo$#Ain Class")
	]
	coclass #$Demo$#Ain
	{
		[default] interface ImwDevice;
		interface ImwInput;
	};
#$EndAICut$#

#$StartAOCut$#
// #$Demo$# Adaptor - Analog Output (includes ImwOutput interface definition)
	[
		uuid(#$AnalogOutputGUID$#),
		helpstring("#$Demo$#Aout Class")
	]
	coclass #$Demo$#Aout
	{
		[default] interface ImwOutput;
	};
#$EndAOCut$#

#$StartDIOCut$#
// #$Demo$# Adaptor - Digital Input/Output (includes ImwDIO interface definition)
	[
		uuid(#$DigitalIOGUID$#),
		helpstring("#$Demo$#DIO Class")
	]
	coclass #$Demo$#DIO
	{
		[default] interface ImwDIO;
	};
#$EndDIOCut$#

};

