% function [lmata,rmata,pmata,qmata,wmata,smata,hmata,....
%     jmata,cmata,dmata,tmata,lmatb,rmatb,pmatb,qmatb,....
%     wmatb,smatb,hmatb,jmatb,cmatb,dmatb,tmatb,tablex,...
%     tabley,tablez,tablev,dgpoint] = gcnvert(m,v,blk)

%   $Revision: 1.6.2.2 $  $Date: 2004/03/10 21:30:33 $
%   Copyright 1991-2002 by MUSYN Inc. and The MathWorks, Inc. 
