// mwmcc.idl : IDL source for mwcbi.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (mwccc.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "daqmex.idl";
	[
		object,
		uuid(9F4D6A59-3BA3-4ea4-B970-98ED41DE907D),
		dual,
		helpstring("IAin Interface"),
		pointer_default(unique)
	]
	interface IAin : IDispatch
	{
		[id(1), helpstring("method SetConfig")] HRESULT SetConfig(long InfoType,long DevNum,long ConfigItem,long ConfigVal);
		[id(2), helpstring("method GetConfig")] HRESULT GetConfig(long InfoType,long DevNum,long ConfigItem,[out,retval] long *ConfigVal);
		[id(3), helpstring("method AIn")] HRESULT AIn(long Channel, long  Range,[out,retval] unsigned short *DataValue);
		[id(4), helpstring("method C8254Config")] HRESULT C8254Config(long CounterNum, long Config);
		[id(5), helpstring("method CLoad")] HRESULT CLoad(VARIANT RegName, unsigned long LoadValue);
	};
	[
		object,
		uuid(507734E3-669D-4aab-A019-5C9D049CF7D5),
		dual,
	
		helpstring("IAout Interface"),
		pointer_default(unique)
	]
	interface IAout : IUnknown
	{
	};
	[
		object,
		uuid(335866FD-353C-4995-B5D6-093EC7D3F815),
	
		helpstring("IDio Interface"),
		pointer_default(unique)
	]
	interface IDio : IUnknown
	{
	};

[
	uuid(66012BAA-FB52-4019-8D00-FFF7BE759DA7),
	version(1.0),
	helpstring("mwmcc 1.0 Type Library")
]
library MWMCCLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(F22FC4CC-E10A-4b61-9D55-E62283C5E8E2),
		helpstring("Ain Class")
	]
	coclass Ain
	{
		[default] interface IAin;
		interface ImwDevice;
		interface ImwInput;

	};
	[
		uuid(5753AE23-22D7-4181-892E-CB18C118ED4E),
		helpstring("Aout Class")
	]
	coclass Aout
	{
		[default] interface IAout;
		interface ImwDevice;
		interface ImwOutput;
	};
	[
		uuid(1078DD6C-E4C2-4309-A0EC-27A09FAB215C),
		helpstring("Dio Class")
	]
	coclass Dio
	{
		[default] interface IDio;
		interface ImwDevice;
		interface ImwDIO;
	};
};
