function idcmdld
% IDCMDLD Set up System Identification demos for MATLAB Demo.

%   Copyright 1986-2003 The MathWorks, Inc.
%   $Revision: 1.7.4.1 $  $Date: 2004/04/10 23:19:20 $

labelList = str2mat( ...
       'Build simple models', ...
       'Compare methods', ...
       'Data and model objects',...
       'Multivariable systems',...
       'Structured models',...
       'Model structures', ...
       'Multiple experiments',...
       'Spectrum estimation', ...
       'Adaptive/Recursive', ...
       'Process Models',...
       'Frequency Domain Data',...
       'Case studies');

nameList = str2mat( ...
       'iddemo1', ...
       'iddemo2', ...
       'iddemo6', ...
       'iddemo9', ...
       'iddemo7', ...
       'iddemo3', ...
       'iddemo8', ...
       'iddemo4', ...
       'iddemo5', ...
       'iddemopr',...
       'iddemofr',...
       'cs');

cmdlnwin(labelList,nameList);