function initialize(this,Axes)
%INITIALIZE  Initialization for @MarginPlotCharView class

%  Author(s): John Glass
%  Copyright 1986-2004 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2004/04/11 00:18:53 $

ax = Axes(1,:);

% Magnitude
this.MagVLine = handle(line([NaN,NaN],[NaN,NaN],[-10,-10],...
    'Parent',ax(1,1),...
    'Visible','off',...
    'LineStyle','-',...
    'Selected','off',...
    'HandleVisibility','off',...
    'HitTest','off',...
    'XlimInclude','off', 'YlimInclude','off',...
    'Color',[0 0 0]));

this.MagAxVLine = handle(line([NaN,NaN],[NaN,NaN],[-10,-10],...
    'Parent',ax(1,1),...
    'Visible','off',...
    'Selected','off',...
    'HandleVisibility','off',...
    'HitTest','off',...
    'XlimInclude','off', 'YlimInclude','off',...
    'LineStyle',':',...
    'Color',[0 0 0]));

this.Mag180VLine = handle(line([NaN,NaN],[NaN,NaN],[-10,-10],...
    'Parent',ax(1,1),...
    'Visible','off',...
    'Selected','off',...
    'HandleVisibility','off',...
    'HitTest','off',...
    'XlimInclude','off', 'YlimInclude','off',...
    'LineStyle',':',...
    'Color',[0 0 0]));

this.ZeroDBLine = handle(line([NaN,NaN],[NaN,NaN],[-10,-10],...
    'Parent',ax(1,1),...
    'Visible','off',...
    'Selected','off',...
    'HandleVisibility','off',...
    'HitTest','off',...
    'XlimInclude','off', 'YlimInclude','off',...
    'LineStyle',':',...
    'Color',[0 0 0]));

% Phase
this.PhaseVLine = handle(line([NaN,NaN],[NaN,NaN],[-10,-10],...
    'Parent',ax(1,2),...
    'Visible','off',...
    'LineStyle','-',...
    'Selected','off',...
    'HandleVisibility','off',...
    'HitTest','off',...
    'XlimInclude','off', 'YlimInclude','off',...
    'Color',[0 0 0]));

this.PhaseAxVLine = handle(line([NaN,NaN],[NaN,NaN],[-10,-10],...
    'Parent',ax(1,2),...
    'Visible','off',...
    'Selected','off',...
    'HandleVisibility','off',...
    'HitTest','off',...
    'XlimInclude','off', 'YlimInclude','off',...
    'LineStyle',':',...
    'Color',[0 0 0]));

this.Phase0DBVLine = handle(line([NaN,NaN],[NaN,NaN],[-10,-10],...
    'Parent',ax(1,2),...
    'Visible','off',...
    'Selected','off',...
    'HandleVisibility','off',...
    'HitTest','off',...
    'XlimInclude','off', 'YlimInclude','off',...
    'LineStyle',':',...
    'Color',[0 0 0]));

this.PhaseCrossLine = handle(line([NaN,NaN],[NaN,NaN],[-10,-10],...
    'Parent',ax(1,2),...
    'Visible','off',...
    'Selected','off',...
    'HandleVisibility','off',...
    'HitTest','off',...
    'XlimInclude','off', 'YlimInclude','off',...
    'LineStyle',':',...
    'Color',[0 0 0]));
