/*
 * @(#)ic_copy_channel_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:25 2004
 *
 *		built from:	ic_copy_channel_rt.c
 */

#ifndef ic_copy_channel_rt_h
#define ic_copy_channel_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_CopyChannelICs( byte_T       *dstBuff, 
                           const byte_T *ICBuff, 
                           int_T         numChans, 
                           const int_T   sampsPerChan,
                           const int_T   bytesPerElem );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* ic_copy_channel_rt_h */
