// mwwinsound.idl : IDL source for mwwinsound.dll
// For DAQ Partners, mwexample.idl and mwexample.dll

// This file will be processed by the MIDL tool to
// produce the type library (mwwinsound.tlb (mwexample.tlb) ) and marshalling code.

// ;Copyright 1998-2004 The MathWorks, Inc.
// $Revision: 1.1.6.3 $  $Date: 2004/04/08 20:49:48 $

import "oaidl.idl";
import "ocidl.idl";
import "daqmex.idl";
		
[
	//For DAQ Partners, comment out the following line
	uuid(602F20F1-DF66-11D1-A21D-00A024E7DC56),
	// For DAQ Partners, uncomment the following line
		//uuid(3D48EE07-D88D-11D2-B249-00A0C9F223E0),

	version(1.0),
	// For DAQ Partners, change mwwinsound to mwexample
	helpstring("mwwinsound 1.0 Type Library")
]

library MWWINSOUNDLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(E3A3FC7A-B3CE-11D3-B32F-00A0C9F223E0),
		helpstring("Adaptor Class")
	]
	coclass Adaptor
	{
		[default] interface ImwAdaptor;
	};

	
	[
		//For DAQ Partners, comment out the following line
		uuid(93DA44DC-C20F-11d3-A53E-00902757EA8D),
		// For DAQ Partners, uncomment the following line
	    //uuid(F4FE5FD0-D183-11d2-A2C5-00A024E7DC56),

		helpstring("SoundAD Class")
	]
	coclass SoundAD
	{
		[default] interface IUnknown;		
	};

	
	[
		//For DAQ Partners, comment out the following line
		uuid(93DA44DB-C20F-11d3-A53E-00902757EA8D),
		// For DAQ Partners, uncomment the following line
		//uuid(F4FE5FD1-D183-11d2-A2C5-00A024E7DC56),
		
		helpstring("SoundDA Class")
	]
	coclass SoundDA
	{
		[default] interface ImwDevice;
		interface ImwOutput;
	};

};
