function setLegendInfo(this)
%SETLEGENDINFO Set legendinfo 

%   Copyright 1984-2003 The MathWorks, Inc. 

% determine marker face color
c = this.markerfacecolor;
if strcmp(c,'auto')
    edge = get(this,'markeredgecolor');
    if strcmp(edge,'auto')
        edge = get(get(this,'MarkerHandle'),'color');
    end
    mfacecolor = edge;
else
    mfacecolor = c;
end

lis.type = 'hggroup';
lisc(1).type = 'line';
lisc(1).props = {...
    'Color',this.Color,...
    'LineWidth',this.LineWidth,...
    'LineStyle',this.LineStyle,...
    'Marker','none',...
    'XData',[0 .7],...
    'YData',[.5 .5]};
lisc(2).type = 'line';
lisc(2).props = {...
    'Color',this.Color,...
    'LineStyle',this.LineStyle,...
    'Marker',this.Marker,...
    'MarkerEdgeColor',this.MarkerEdgeColor,...
    'MarkerFaceColor',mfacecolor,...
    'MarkerSize',this.MarkerSize,...
    'XData',.7,...
    'YData',.5};
lis.children = lisc;
legendinfo(this,lis);
setappdata(double(this),'LegendLegendType','line');