/*
 * @(#)chol_c_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:14 2004
 *
 *		built from:	chol_c_rt.c
 */

#ifndef chol_c_rt_h
#define chol_c_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_Chol_C(creal32_T *A, int_T n);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* chol_c_rt_h */
