/*
 * @(#)bq5_df2t_1fpf_nsos_zd_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:13 2004
 *
 *		built from:	bq5_df2t_1fpf_nsos_zd_rt.c
 */

#ifndef bq5_df2t_1fpf_nsos_zd_rt_h
#define bq5_df2t_1fpf_nsos_zd_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_BQ5_DF2T_1fpf_Nsos_ZD (const creal_T *u,
                                  creal_T *y,
                                  creal_T *state,
                                  const real_T *coeffs,
                                  const int_T sampsPerChan,
                                  const int_T numChans,
                                  const int_T numSections);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* bq5_df2t_1fpf_nsos_zd_rt_h */
