void   MDIActivate(HWND hwnd, BOOL fActive, HWND hwndActivate, HWND hwndDeactivate); 
BOOL   MDICascade(HWND hwnd, UINT cmd);
HWND   MDICreate(HWND hwnd, const LPMDICREATESTRUCT lpmcs);
void   MDIDestroy(HWND hwnd, HWND hwndDestroy); 
HWND   MDIGetActive(HWND hwnd); 
void   MDIIconArrange(HWND hwnd);
void   MDIMaximize(HWND hwnd, HWND hwndMaximize); 
HWND   MDINext(HWND hwnd, HWND hwndCur, BOOL fPrev); 
void   MDIRestore(HWND hwnd, HWND hwndRestore);
HMENU  MDISetMenu(HWND hwnd, BOOL fRefresh, HMENU hmenuFrame, HMENU hmenuWindow); 
BOOL   MDITile(HWND hwnd, UINT cmd); 
void   OnActivate(HWND hwnd, UINT state, HWND hwndActDeact, BOOL fMinimized);
void   OnActivateApp(HWND hwnd, BOOL fActivate, DWORD dwThreadId);
void   OnAskCBFormatName(HWND hwnd, int cchMax, LPTSTR rgchName);
void   OnCancelMode(HWND hwnd);
void   OnChangeCBChain(HWND hwnd, HWND hwndRemove, HWND hwndNext);
void   OnChar(HWND hwnd, TCHAR ch, int cRepeat);
int    OnCharToItem(HWND hwnd, UINT ch, HWND hwndListbox, int iCaret); 
void   OnChildActivate(HWND hwnd); 
void   OnClear(HWND hwnd);
void   OnClose(HWND hwnd);
void   OnCommand(HWND hwnd, int id, HWND hwndCtl, UINT codeNotify); 
void   OnCommNotify(HWND hwnd, int cid, UINT flags);
void   OnCompacting(HWND hwnd, UINT compactRatio);
int    OnCompareItem(HWND hwnd, const COMPAREITEMSTRUCT * lpCompareItem); 
void   OnCopy(HWND hwnd);
BOOL   OnCreate(HWND hwnd, LPCREATESTRUCT lpCreateStruct);
HBRUSH OnCtlColorBtn(HWND hwnd, HDC hdc, HWND hwndChild, int type);
HBRUSH OnCtlColorDlg(HWND hwnd, HDC hdc, HWND hwndChild, int type);
HBRUSH OnCtlColorEdit(HWND hwnd, HDC hdc, HWND hwndChild, int type);
HBRUSH OnCtlColorListBox(HWND hwnd, HDC hdc, HWND hwndChild, int type);
HBRUSH OnCtlColorMsgBox(HWND hwnd, HDC hdc, HWND hwndChild, int type); 
HBRUSH OnCtlColorScrollBar(HWND hwnd, HDC hdc, HWND hwndChild, int type);
HBRUSH OnCtlColorStatic(HWND hwnd, HDC hdc, HWND hwndChild, int type);
void   OnCut(HWND hwnd);
void   OnDeadChar(HWND hwnd, TCHAR ch, int cRepeat);
void   OnDeleteItem(HWND hwnd, const DELETEITEMSTRUCT * lpDeleteItem);
void   OnDestroy(HWND hwnd);
void   OnDestroyClipboard(HWND hwnd); 
void   OnDevModeChange(HWND hwnd, LPCTSTR lpszDeviceName);
void   OnDrawClipboard(HWND hwnd);
void   OnDrawItem(HWND hwnd, const DRAWITEMSTRUCT * lpDrawItem); 
void   OnDropFiles(HWND hwnd, HDROP hdrop);
void   OnEnable(HWND hwnd, BOOL fEnable);
void   OnEndSession(HWND hwnd, BOOL fEnding);
void   OnEnterIdle(HWND hwnd, UINT source, HWND hwndSource); 
BOOL   OnEraseBkgnd(HWND hwnd, HDC hdc);
void   OnFontChange(HWND hwnd);
UINT   OnGetDlgCode(HWND hwnd, LPMSG lpmsg); 
HFONT  OnGetFont(HWND hwnd);
void   OnGetMinMaxInfo(HWND hwnd, LPMINMAXINFO lpMinMaxInfo);
INT    OnGetText(HWND hwnd, int cchTextMax, LPTSTR lpszText);
INT    OnGetTextLength(HWND hwnd);
void   OnHScroll(HWND hwnd, HWND hwndCtl, UINT code, int pos); 
void   OnHScrollClipboard(HWND hwnd, HWND hwndCBViewer, UINT code, int pos); 
BOOL   OnIconEraseBkgnd(HWND hwnd, HDC hdc);
BOOL   OnInitDialog(HWND hwnd, HWND hwndFocus, LPARAM lParam); 
void   OnInitMenu(HWND hwnd, HMENU hMenu); 
void   OnInitMenuPopup(HWND hwnd, HMENU hMenu, UINT item, BOOL fSystemMenu);
void   OnKeyDown(HWND hwnd, UINT vk, BOOL fDown, int cRepeat, UINT flags);
void   OnKeyUp(HWND hwnd, UINT vk, BOOL fDown, int cRepeat, UINT flags);
void   OnKillFocus(HWND hwnd, HWND hwndNewFocus);
void   OnLButtonDblclk(HWND hwnd, BOOL fDoubleClick, int x, int y, UINT keyFlags);
void   OnLButtonDown(HWND hwnd, BOOL fDoubleClick, int x, int y, UINT keyFlags);
void   OnLButtonUp(HWND hwnd, int x, int y, UINT keyFlags);
void   OnMButtonDblclk(HWND hwnd, BOOL fDoubleClick, int x, int y, UINT keyFlags);
void   OnMButtonDown(HWND hwnd, BOOL fDoubleClick, int x, int y, UINT keyFlags); 
void   OnMButtonUp(HWND hwnd, int x, int y, UINT flags); 
void   OnMeasureItem(HWND hwnd, MEASUREITEMSTRUCT * lpMeasureItem); 
DWORD  OnMenuChar(HWND hwnd, UINT ch, UINT flags, HMENU hmenu); 
void   OnMenuSelect(HWND hwnd, HMENU hmenu, int item, HMENU hmenuPopup, UINT flags); 
int    OnMouseActivate(HWND hwnd, HWND hwndTopLevel, UINT codeHitTest, UINT msg); 
void   OnMouseMove(HWND hwnd, int x, int y, UINT keyFlags);
void   OnMove(HWND hwnd, int x, int y);
BOOL   OnNCActivate(HWND hwnd, BOOL fActive, HWND hwndActDeact, BOOL fMinimized);
UINT   OnNCCalcSize(HWND hwnd, BOOL fCalcValidRects, NCCALCSIZE_PARAMS * lpcsp);
BOOL   OnNCCreate(HWND hwnd, LPCREATESTRUCT lpCreateStruct);
void   OnNCDestroy(HWND hwnd);
UINT   OnNCHitTest(HWND hwnd, int x, int y);
void   OnNCLButtonDblclk(HWND hwnd, BOOL fDoubleClick, int x, int y, UINT codeHitTest); 
void   OnNCLButtonDown(HWND hwnd, BOOL fDoubleClick, int x, int y, UINT codeHitTest);
void   OnNCLButtonUp(HWND hwnd, int x, int y, UINT codeHitTest);
void   OnNCMButtonDblclk(HWND hwnd, BOOL fDoubleClick, int x, int y, UINT codeHitTest); 
void   OnNCMButtonDown(HWND hwnd, BOOL fDoubleClick, int x, int y, UINT codeHitTest);
void   OnNCMButtonUp(HWND hwnd, int x, int y, UINT codeHitTest);
void   OnNCMouseMove(HWND hwnd, int x, int y, UINT codeHitTest);
void   OnNCPaint(HWND hwnd, HRGN hrgn);
void   OnNCRButtonDblclk(HWND hwnd, BOOL fDoubleClick, int x, int y, UINT codeHitTest); 
void   OnNCRButtonDown(HWND hwnd, BOOL fDoubleClick, int x, int y, UINT codeHitTest);
void   OnNCRButtonUp(HWND hwnd, int x, int y, UINT codeHitTest);
HWND   OnNextDlgCtl(HWND hwnd, HWND hwndSetFocus, BOOL fNext);
void   OnPaint(HWND hwnd);
void   OnPaintClipboard(HWND hwnd, HWND hwndCBViewer, const LPPAINTSTRUCT lpPaintStruct); 
void   OnPaletteChanged(HWND hwnd, HWND hwndPaletteChange);
void   OnPaletteIsChanging(HWND hwnd, HWND hwndPaletteChange);
void   OnParentNotify(HWND hwnd, UINT msg, HWND hwndChild, int idChild); 
void   OnPaste(HWND hwnd);
void   OnPower(HWND hwnd, int code);
HICON  OnQueryDragIcon(HWND hwnd);
BOOL   OnQueryEndSession(HWND hwnd);
BOOL   OnQueryNewPalette(HWND hwnd);
BOOL   OnQueryOpen(HWND hwnd);
void   OnQueueSync(HWND hwnd); 
void   OnQuit(HWND hwnd, int exitCode);
void   OnRButtonDblclk(HWND hwnd, BOOL fDoubleClick, int x, int y, UINT keyFlags); 
void   OnRButtonDown(HWND hwnd, BOOL fDoubleClick, int x, int y, UINT keyFlags);
void   OnRButtonUp(HWND hwnd, int x, int y, UINT flags);
void   OnRenderAllFormats(HWND hwnd);
HANDLE OnRenderFormat(HWND hwnd, UINT fmt);
BOOL   OnSetCursor(HWND hwnd, HWND hwndCursor, UINT codeHitTest, UINT msg);
void   OnSetFocus(HWND hwnd, HWND hwndOldFocus);
void   OnSetFont(HWND hwndCtl, HFONT hfont, BOOL fRedraw); 
void   OnSetRedraw(HWND hwnd, BOOL fRedraw);
void   OnSetText(HWND hwnd, LPCTSTR lpszText);
void   OnShowWindow(HWND hwnd, BOOL fShow, UINT status);
void   OnSize(HWND hwnd, UINT state, int cx, int cy);
void   OnSizeClipboard(HWND hwnd, HWND hwndCBViewer, const LPRECT lprc);
void   OnSpoolerStatus(HWND hwnd, UINT status, int cJobInQueue);
void   OnSysChar(HWND hwnd, TCHAR ch, int cRepeat);
void   OnSysColorChange(HWND hwnd);
void   OnSysCommand(HWND hwnd, UINT cmd, int x, int y); 
void   OnSysDeadChar(HWND hwnd, TCHAR ch, int cRepeat);
void   OnSysKeyDown(HWND hwnd, UINT vk, BOOL fDown, int cRepeat, UINT flags);
void   OnSysKeyUp(HWND hwnd, UINT vk, BOOL fDown, int cRepeat, UINT flags);
void   OnTimeChange(HWND hwnd);
void   OnTimer(HWND hwnd, UINT id); 
void   OnUndo(HWND hwnd);
int    OnVkeyToItem(HWND hwnd, UINT vk, HWND hwndListbox, int iCaret); 
void   OnVScroll(HWND hwnd, HWND hwndCtl, UINT code, int pos)
void   OnVScrollClipboard(HWND hwnd, HWND hwndCBViewer, UINT code, int pos);
void   OnWindowPosChanged(HWND hwnd, const LPWINDOWPOS lpwpos);
BOOL   OnWindowPosChanging(HWND hwnd, LPWINDOWPOS lpwpos);
void   OnWinIniChange(HWND hwnd, LPCTSTR lpszSectionName);
