/*
 * @(#)copy_and_zero_pad_cc_nchan_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:10 2004
 *
 *		built from:	copy_and_zero_pad_cc_nchan_rt.c
 */

#ifndef copy_and_zero_pad_cc_nchan_rt_h
#define copy_and_zero_pad_cc_nchan_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_Copy_and_ZeroPad_CC_Nchan(const creal32_T *u, const int_T Nu, creal32_T *y, const int_T Ny, int_T Nchan);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* copy_and_zero_pad_cc_nchan_rt_h */
