function xpctgscope(varargin)
% XPCTGSCOPE - xPC Target Target Scope GUI
%
%    XPCSETUP opens the xPC Target Target Scope window which allows you
%    to define scopes of type target, to choose signals and control the
%    acquisition process.
%
%    See also XPCSCOPE

% Copyright 1996-2004 The MathWorks, Inc.
% $Revision: 1.14.6.1 $ $Date: 2004/01/22 18:36:44 $

if nargin
  flag = varargin{1};
end
maxscopes = 10;

h_main = withhiddenhandles('get', 0, 'Children');
opened = strmatch('xPC Target: Target Manager', get(h_main, 'Name'));

modelname = xpcgate('getname');

if ~isempty(opened)
  targetmanager = get(h_main(opened), 'UserData');
else
  targetmanager.dispmsg = 0;
end

if strcmp(modelname,'loader')
  errordlg('No Model on Target');
  if ~isempty(opened)
    targetmanager.dispmsg = 1;
    set(targetmanager.figure, 'UserData', targetmanager);
    xpctgscope(-8);
  end
  return
end

if ~exist([modelname,'bio.m'])
  errordlg('Current Directory is not Project Directory');
  return
end

if isempty(opened) & nargin == 0
  set(0,'ShowHiddenHandles','on');

  targetmanager.handles.xpctgscwin(1:30)=-1;

  hnew=xpctargetscfigure;
  targetmanager.figure=findobj(hnew,'Tag','tgscfigure');

  targetmanager.tgmenu.newscope=findobj(hnew,'Tag','tgfilemenu1');
  targetmanager.tgmenu.delete=findobj(hnew,'Tag','tgfilemenu2');
  targetmanager.tgmenu.load=findobj(hnew,'Tag','tgfilemenu3');
  targetmanager.tgmenu.save=findobj(hnew,'Tag','tgfilemenu4');
  targetmanager.tgmenu.closetgscopes=findobj(hnew,'Tag','tgfilemenu5');
  targetmanager.tgmenu.deletetgscopes=findobj(hnew,'Tag','tgfilemenu6');
  targetmanager.tgscpb(1)=findobj(hnew,'Tag','tgscpb1');
  targetmanager.tgscpb(2)=findobj(hnew,'Tag','tgscpb2');
  targetmanager.tgscpb(3)=findobj(hnew,'Tag','tgscpb3');
  targetmanager.tgscpb(4)=findobj(hnew,'Tag','tgscpb4');
  targetmanager.tgscpb(5)=findobj(hnew,'Tag','tgscpb5');
  targetmanager.tgscpb(6)=findobj(hnew,'Tag','tgscpb6');
  targetmanager.tgscpb(7)=findobj(hnew,'Tag','tgscpb7');
  targetmanager.tgscpb(8)=findobj(hnew,'Tag','tgscpb8');
  targetmanager.tgscpb(9)=findobj(hnew,'Tag','tgscpb9');
  targetmanager.tgscpb(10)=findobj(hnew,'Tag','tgscpb10');
  targetmanager.tgscpb(11)=findobj(hnew,'Tag','tgscpb11');
  targetmanager.tgscpb(12)=findobj(hnew,'Tag','tgscpb12');
  targetmanager.multiplepb=findobj(hnew,'Tag','multiplepb');
  targetmanager.tgaxis=findobj(hnew,'Tag','tgaxis');
  %targetmanager.frame=findobj(hnew,'Tag','frame');
  %targetmanager.frametitle=findobj(hnew,'Tag','frametitle');

  for i = 1:12
    set(targetmanager.tgscpb(i),'UserData',i,'CallBack','xpctgscope(-1)');
  end


  scrsize = get(0,'ScreenSize');
  set(targetmanager.figure, 'Position', ...
                    [(scrsize(3)-50)*0.25,(scrsize(4)-50)*0.25,200,200], ...
                    'Closerequestfcn','xpctgscope(-8)');

  targetmanager.numoftgscopes = 12;

  targetmanager = create_patches(targetmanager);
  targetmanager = create_pushbutton(targetmanager);
  targetmanager = create_contextmenupb(targetmanager);
  targetmanager = create_contextmenupatches(targetmanager);

  set(targetmanager.tgmenu.newscope, 'CallBack', 'xpctgscope(-7)');
  set(targetmanager.tgmenu.delete,   'CallBack', 'xpctgscope(-8)');
  set(targetmanager.tgmenu.load,     'CallBack', 'xpctgscope(-13)', ...
                    'Enable','on');
  set(targetmanager.tgmenu.save,     'CallBack', 'xpctgscope(-14)', ...
                    'Enable','on');
  set(targetmanager.tgmenu.closetgscopes,  'CallBack', 'xpctgscope(-11)');
  set(targetmanager.tgmenu.deletetgscopes, 'CallBack', 'xpctgscope(-12)');

  position=get(targetmanager.figure,'Position');
  set(targetmanager.tgaxis,'Position',[0, 0, position(3), position(4)]);
  set(gca,'XlimMode','manual','YlimMode','manual','Units','pixels','XLim',[0 position(3)],'YLim',[0 position(4)]);


  %-----------------------------------
  numoftgscopes=xpcgate('getscopes','target');          %(1) ----> tgscopes
  targetmanager.numoftgscopes=length(numoftgscopes);
  targetmanager=create_pushbutton(targetmanager);
  for i=1:targetmanager.numoftgscopes
    set(targetmanager.tgscpb(i),'UserData',numoftgscopes(i),'String',['Scope ',num2str(numoftgscopes(i))]);
    set(targetmanager.patch(i),'UserData',numoftgscopes(i));
    if isempty(xpcgate('getscsignals',numoftgscopes(i)))
      set(targetmanager.menu(i).startstop,'Enable','off');
    else
      set(targetmanager.menu(i).startstop,'Enable','on');
    end
    if xpcgate('getscstate',numoftgscopes(i))~=4
      set(targetmanager.menu(i).startstop,'Label','Stop');
    else
      set(targetmanager.menu(i).startstop,'Label','Start');
    end
  end

  targetmanager.handles.targetstart=1;

  set(hnew,'UserData',targetmanager);

else

  set(0,'ShowHiddenHandles','on');
  if nargin > 1
    mgrH = varargin{2};
    targetmanager=get(mgrH,'UserData');
  end
%   else
%     mgrH = gcbf;
%   end
%   targetmanager=get(mgrH,'UserData');

  if nargin==0

    figure(h_main(opened));

    %-------------------------------------------------------------------------

  elseif flag==-1               %mode single
    targetnumber=get(gcbo,'UserData');
    pbtag=get(gcbo,'Tag');
    % Tag is of the form tgscpb4 (one or two digits)
    pbnum = str2num(pbtag(7:end));
    xpcgate('settgscviewmode',targetnumber);
    set(targetmanager.patch,'FaceColor','b');
    set(targetmanager.patch(pbnum),'FaceColor','r');

    %-------------------------------------------------------------------------

  elseif flag==-2       %mode multiple
    xpcgate('settgscviewmode',0);
    set(targetmanager.patch,'FaceColor','b');

    %------------------------------------------------------------------------

  elseif flag==-3       %open properties window
    targetnumber = get(gco,'UserData');
    xpctgscwin(0,targetnumber);
    targetmanager = get(targetmanager.figure,'UserData');

    set(0,'ShowHiddenHandles','on');
    %show Add/Remove window
    h_main=get(0, 'Children');
    opened=strmatch(['xPC Target: Add/Remove Signals for Target Scope ',num2str(targetnumber)], get(h_main, 'Name'));
    if ~isempty(opened)
      figure(h_main(opened));
    end

    %show trigger window
    h_main=get(0, 'Children');
    opened=strmatch(['xPC Target: Trigger for Target Scope ',num2str(targetnumber)], get(h_main, 'Name'));
    if ~isempty(opened)
      figure(h_main(opened));
    end

    %show window target scope
    h_main=get(0, 'Children');
    opened=strmatch(['xPC Target: Target Scope ',num2str(targetnumber)], get(h_main, 'Name'));
    if ~isempty(opened)
      figure(h_main(opened));
    end

    set(0,'ShowHiddenHandles','off');

    %-------------------------------------------------------------------------

  elseif flag==-4       %change start/stop
    if nargin > 2
      obj = varargin{3};
    else
      obj = gco;
    end
    targetnumber = get(obj,'UserData');
    tag          = get(obj,'Tag');
    number       = str2num(tag);
    startstop=get(targetmanager.menu(number).startstop,'Label');
    if strcmp(startstop,'Start')
      xpcgate('scstart',targetnumber);
      set(targetmanager.menu(number).startstop,'Label','Stop');
      if xpcgate('getsctriggermode',targetnumber)==1
        set(targetmanager.menu(number).softtrig,'Enable','on');
      else
        set(targetmanager.menu(number).softtrig,'Enable','off');
      end
    else
      xpcgate('scstop',targetnumber);
      set(targetmanager.menu(number).startstop,'Label','Start');
      set(targetmanager.menu(number).softtrig,'Enable','off');
    end

    %-------------------------------------------------------------------------

  elseif flag==-5       %softtrig

    targetnumber=get(gco,'UserData');
    xpcgate('scstop',targetnumber);
    xpcgate('scstart',targetnumber);
    xpcgate('softtrig',targetnumber);

    %-------------------------------------------------------------------------

  elseif flag==-6       %delete target scope & pushbutton

    %----------------------------------------------------------------------  
    % determine the Object where delete event came from to process the
    % delete request.
    if strcmp(get(gcbf,'name'),'xPC Target Remote Control Tool')
        scopnumcell=get(get(gco,'userdata'),'userdata');
        scopeval=get(get(gco,'userdata'),'value');
%         if (length(scopnumcell) == scopeval+1)
%             scopeval=scopeval+1;
%         end
        scnumstr=scopnumcell{scopeval};
        scNum=str2num(scnumstr(1:find(scnumstr==' ')-1));
        fvisibiltystat=get(0,'showhiddenhandles');
        set(0,'showhiddenhandles','on');
        fighandletg=findobj(0,'type','figure','Name','xPC Target: Target Manager');
        set(0,'showhiddenhandles',fvisibiltystat);
        ph=findobj(fighandletg,'type','patch','visible','on');
        pacell=get(ph,'userdata');
        if length(pacell)==1
            pacell={pacell};
        end
        pavec=cat(1,pacell{:});
        patObj=ph(find(pavec==scNum));
    else
        patObj=gco;        
    end
    %----------------------------------------------------------------------  
    targetnumber=get(patObj,'UserData');
    xpcgate('delscope',targetnumber);

    set(0,'ShowHiddenHandles','on');

    %delete window target scope
    h_main=get(0, 'Children');
    opened=strmatch(['xPC Target: Target Scope ',num2str(targetnumber)], get(h_main, 'Name'));
    if ~isempty(opened)
      delete(h_main(opened));
      %targetmanager.handles.xpctgscwin(usrdata.edit.targetnumber)=-1;
      targetmanager.handles.xpctgscwin(targetnumber)=-1;

    end

    %delete Add/Remove window
    h_main=get(0, 'Children');
    opened=strmatch(['xPC Target: Add/Remove Signals for Target Scope ',num2str(targetnumber)], get(h_main, 'Name'));
    if ~isempty(opened)
      delete(h_main(opened));
    end

    %delete trigger window
    h_main=get(0, 'Children');
    opened=strmatch(['xPC Target: Trigger for Target Scope ',num2str(targetnumber)], get(h_main, 'Name'));
    if ~isempty(opened)
      delete(h_main(opened));
    end

    %delete y-scaling window
    h_main=get(0, 'Children');
    opened=strmatch('Define Y-Axis Scaling', get(h_main, 'Name'));
    if ~isempty(opened)
      delete(h_main(opened));
    end

    %-----------------------------------
    numoftgscopes=xpcgate('getscopes','target');  %(1) ----> tgscopes
    targetmanager.numoftgscopes=length(numoftgscopes);
    targetmanager=create_pushbutton(targetmanager);
    for i=1:targetmanager.numoftgscopes
      set(targetmanager.tgscpb(i),'UserData',numoftgscopes(i),'String',['Scope ',num2str(numoftgscopes(i))]);
      set(targetmanager.patch(i),'UserData',numoftgscopes(i));

      h_main=get(0, 'Children');
      opened=strmatch(['xPC Target: Target Scope ',num2str(numoftgscopes(i))], get(h_main, 'Name'));
      if ~isempty(opened)
        usrdata=get(h_main(opened),'UserData');
        usrdata=refresh_tgscope(usrdata);
        set(h_main(opened),'UserData',usrdata);
      end
    end
    set(0,'ShowHiddenHandles','off');


    %-------------------------------------------------------------------------

  elseif flag==-7       %create target scope & pushbutton

    set(0,'ShowHiddenHandles','on');

    if targetmanager.numoftgscopes==maxscopes;
      errordlg('scope structure full');
      return
    end
    targetnumber=xpcgate('defscope','target');
    %xpcgate('setsctype',targetnumber,2);
    %-----------------------------------
    numoftgscopes=xpcgate('getscopes','target');                %(1) ----> tgscopes
    targetmanager.numoftgscopes=length(numoftgscopes);
    targetmanager=create_pushbutton(targetmanager);
    for i=1:targetmanager.numoftgscopes
      set(targetmanager.tgscpb(i),'UserData',numoftgscopes(i),'String',['Scope ',num2str(numoftgscopes(i))]);
      set(targetmanager.patch(i),'UserData',numoftgscopes(i));
    end


    for i=1:targetmanager.numoftgscopes
      h_main=get(0, 'Children');
      opened=strmatch(['xPC Target: Target Scope ',num2str(numoftgscopes(i))], get(h_main, 'Name'));
      if ~isempty(opened)
        usrdata=get(h_main(opened),'UserData');
        usrdata=refresh_tgscope(usrdata);
        set(h_main(opened),'UserData',usrdata);
      end
    end
    set(0,'ShowHiddenHandles','off');

    %-------------------------------------------------------------------------

  elseif flag==-8       %delete manager

    set(0,'ShowHiddenHandles','on');

    if ~strcmp(modelname,'loader')
      if ~isempty(xpcgate('getscopes','target'))
        answer=questdlg('Save before closing', ...
                        'Save ?', ...
                        'Yes','No','Yes');

        switch answer,
         case 'Yes',
          xpctgscope(-14);
        end % switch
      end
    end


    %delete windows target scope
    h_main = get(0, 'Children');
    opened = strmatch('xPC Target: Target Scope', get(h_main, 'Name'));
    for i=1:length(opened)
      delete(h_main(opened(i)));
    end

    %delete Add/Remove windows
    h_main=get(0, 'Children');
    opened=strmatch('xPC Target: Add/Remove Signals for Target Scope', get(h_main, 'Name'));
    for i=1:length(opened)
      delete(h_main(opened(i)));
    end

    %delete trigger windows
    h_main=get(0, 'Children');
    opened=strmatch('xPC Target: Trigger for Target Scope', get(h_main, 'Name'));
    for i=1:length(opened)
      delete(h_main(opened(i)));
    end

    %delete y-scaling window
    h_main=get(0, 'Children');
    opened=strmatch('Define Y-Axis Scaling', get(h_main, 'Name'));
    if ~isempty(opened)
      delete(h_main(opened));
    end

    %delete target manager
    delete(targetmanager.figure);
    %set(0,'ShowHiddenHandles','off');

    %xpcgate('delscope');



    %-------------------------------------------------------------------------

  elseif flag==-11      %delete all open windows

    set(0,'ShowHiddenHandles','on');

    %delete windows target scope
    h_main=get(0, 'Children');
    opened=strmatch('xPC Target: Target Scope', get(h_main, 'Name'));
    for i=1:length(opened)
      delete(h_main(opened(i)));
    end

    %delete Add/Remove windows
    h_main=get(0, 'Children');
    opened=strmatch('xPC Target: Add/Remove Signals for Target Scope', get(h_main, 'Name'));
    for i=1:length(opened)
      delete(h_main(opened(i)));
    end

    %delete trigger windows
    h_main=get(0, 'Children');
    opened=strmatch('xPC Target: Trigger for Target Scope', get(h_main, 'Name'));
    for i=1:length(opened)
      delete(h_main(opened(i)));
    end

    %delete y-scaling window
    h_main=get(0, 'Children');
    opened=strmatch('Define Y-Axis Scaling', get(h_main, 'Name'));
    if ~isempty(opened)
      delete(h_main(opened));
    end

    set(0,'ShowHiddenHandles','off');

    %-------------------------------------------------------------------------

  elseif flag==-12      %delete tgscopes

    set(0,'ShowHiddenHandles','on');

    %delete windows target scope
    h_main=get(0, 'Children');
    opened=strmatch('xPC Target: Target Scope', get(h_main, 'Name'));
    for i=1:length(opened)
      delete(h_main(opened(i)));
    end

    %delete Add/Remove windows
    h_main=get(0, 'Children');
    opened=strmatch('xPC Target: Add/Remove Signals for Target Scope', get(h_main, 'Name'));
    for i=1:length(opened)
      delete(h_main(opened(i)));
    end

    %delete trigger windows
    h_main=get(0, 'Children');
    opened=strmatch('xPC Target: Trigger for Target Scope', get(h_main, 'Name'));
    for i=1:length(opened)
      delete(h_main(opened(i)));
    end

    targetmanager.numoftgscopes=0;
    targetmanager=create_pushbutton(targetmanager);

    set(0,'ShowHiddenHandles','off');

    xpcgate('delscope',xpcgate('getscopes','target'));

    %----------------------------------
    % load
    %----------------------------------

  elseif flag==-13

    xpctgscope(-8);
    xpcgate('delscope',xpcgate('getscopes','target'));
    xpctgscope;
    %scopemanager=get(h_main(opened), 'UserData');

    set(0,'ShowHiddenHandles','on');

    [filename, path] = uigetfile('*.mat', 'Load Target Scope Windows');

    if filename ~= 0
      load([path, filename]);
    else
      return
    end

    h_main=get(0, 'Children');
    opened=strmatch('xPC Target: Target Manager', get(h_main, 'Name'));
    targetmanager=get(h_main(opened), 'UserData');

    for i=1:length(data)

      usrdata.edit=data{i};

      if ~exist([modelname,'bio.m'])
        errordlg('Current Directory is not Project Directory');
        return
      end

      scno=usrdata.edit.state.scopeno;
      xpcgate('defscope','target',scno);
      if ~isempty(usrdata.edit.state.signals)
        xpcgate('addsig',scno,usrdata.edit.state.signals);
      end
      xpcgate('setscnosamples',scno,usrdata.edit.state.nosamples);
      xpcgate('setscnoprepostsamples',scno,usrdata.edit.state.noprepostsamples);
      xpcgate('setscinterleave',scno,usrdata.edit.state.interleave);
      xpcgate('setsctriggermode',scno,usrdata.edit.state.triggermode);
      if ~(usrdata.edit.state.triggersignal==-1)
          xpcgate('setsctriggersignal',scno,usrdata.edit.state.triggersignal);
      end
      xpcgate('setsctriggerscope',scno,usrdata.edit.state.triggerscope);
      xpcgate('setsctriggerlevel',scno,usrdata.edit.state.triggerlevel);
      xpcgate('setsctriggerslope',scno,usrdata.edit.state.triggerslope);

      xpcgate('settgscylimits',usrdata.edit.state.scopeno,[usrdata.edit.target.yaxis.min,usrdata.edit.target.yaxis.max]);

      xpcgate('settgscgrid',usrdata.edit.state.scopeno,usrdata.edit.target.grid);
      xpcgate('settgscmode',usrdata.edit.state.scopeno,usrdata.edit.target.mode);

      if targetmanager.numoftgscopes==maxscopes;
        errordlg('scope structure full');
        return
      end

      numoftgscopes=xpcgate('getscopes','target');              %(1) ----> tgscopes
      targetmanager.numoftgscopes=length(numoftgscopes);
      targetmanager=create_pushbutton(targetmanager);
      for i=1:targetmanager.numoftgscopes
        set(targetmanager.tgscpb(i),'UserData',numoftgscopes(i),'String',['Scope ',num2str(numoftgscopes(i))]);
        set(targetmanager.patch(i),'UserData',numoftgscopes(i));
        if isempty(xpcgate('getscsignals',numoftgscopes(i)))
          set(targetmanager.menu(i).startstop,'Enable','off');
        else
          set(targetmanager.menu(i).startstop,'Enable','on');
        end
      end

      if(usrdata.edit.win.target~=-1)
        xpctgscwin(0,usrdata.edit.state.scopeno);
        set(0,'ShowHiddenHandles','on');
        h_target=get(0, 'Children');
        opened=strmatch(['xPC Target: Target Scope ',num2str(usrdata.edit.state.scopeno)], get(h_target, 'Name'));
        if ~isempty(opened)
          set(h_target(opened), 'Position',usrdata.edit.win.target_pos);
          if(usrdata.edit.win.addrem~=-1)
            xpctgscsignalwin(h_target(opened));
            set(0,'ShowHiddenHandles','on');
            h_addrem=get(0, 'Children');
            opened_addrem=strmatch(['xPC Target: Add/Remove Signals for Target Scope ',num2str(usrdata.edit.state.scopeno)], get(h_addrem, 'Name'));
            if ~isempty(opened_addrem)
              set(h_addrem(opened_addrem), 'Position',usrdata.edit.win.addrem_pos);
            end
          end
          if(usrdata.edit.win.trigger~=-1)
            xpctgsctriggerwin(0,h_target(opened));
            xpctgsctriggerwin(-1,h_target(opened));
            set(0,'ShowHiddenHandles','on');
            h_trigger=get(0, 'Children');
            opened_trigger=strmatch(['xPC Target: Trigger for Target Scope ',num2str(usrdata.edit.state.scopeno)], get(h_trigger, 'Name'));
            if ~isempty(opened_trigger)
              set(h_trigger(opened_trigger), 'Position',usrdata.edit.win.trigger_pos);
            end
          end
        end
      end

      h_main=get(0, 'Children');
      opened=strmatch(['xPC Target: Target Scope ',num2str(numoftgscopes(i))], get(h_main, 'Name'));
      for i=1:targetmanager.numoftgscopes
        if ~isempty(opened)
          usrdata=get(h_main(opened),'UserData');
          usrdata=refresh_tgscope(usrdata);
          set(h_main(opened),'UserData',usrdata);
        end
      end

    end

    %----------------------------------
    % save
    %----------------------------------

  elseif flag==-14

    [filename, path] = uiputfile('*.mat', 'Save Scope Windows');

    j=1;

    targetscopes=xpcgate('getscopes','target');

    if filename ~= 0
      for k=1:length(targetscopes)
        usrdata.edit.state=xpcgate('getscope',targetscopes(k));
        j=j+1;

        limits=xpcgate('gettgscylimits',targetscopes(k));
        usrdata.edit.target.yaxis.min=limits(1);
        usrdata.edit.target.yaxis.max=limits(2);

        usrdata.edit.target.grid=xpcgate('gettgscgrid',targetscopes(k));
        usrdata.edit.target.mode=xpcgate('gettgscmode',targetscopes(k));

        %save window target scope if open
        h_main=get(0, 'Children');
        opened=strmatch(['xPC Target: Target Scope ',num2str(usrdata.edit.state.scopeno)], get(h_main, 'Name'));
        if ~isempty(opened)
          usrdata.edit.win.target=1;
          usrdata.edit.win.target_pos=get(h_main(opened), 'Position');
        else
          usrdata.edit.win.target=-1;
        end

        %save add/rem window if open
        h_main=get(0, 'Children');
        opened=strmatch(['xPC Target: Add/Remove Signals for Target Scope ',num2str(usrdata.edit.state.scopeno)], get(h_main, 'Name'));
        if ~isempty(opened)
          usrdata.edit.win.addrem=1;
          usrdata.edit.win.addrem_pos=get(h_main(opened), 'Position');
        else
          usrdata.edit.win.addrem=-1;
        end

        %save trigger window if open
        h_main=get(0, 'Children');
        opened=strmatch(['xPC Target: Trigger for Target Scope ',num2str(usrdata.edit.state.scopeno)], get(h_main, 'Name'));
        if ~isempty(opened)
          usrdata.edit.win.trigger=1;
          usrdata.edit.win.trigger_pos=get(h_main(opened), 'Position');
        else
          usrdata.edit.win.trigger=-1;
        end

        data{k}=usrdata.edit;
      end
      save([path, filename], 'data');
    end

  end

  if nargin~=0 & flag~=-8
    set(targetmanager.figure,'UserData',targetmanager);
  end
end
set(0,'ShowHiddenHandles','off');

function targetmanager=create_pushbutton(targetmanager)

pbdim_x=90;
pbdim_y=40;
offset=8;

scrsize=get(0,'ScreenSize');

set(targetmanager.tgscpb, 'Visible', 'off');
set(targetmanager.patch,  'Visible', 'off');

% make it as close to square as possible
switch targetmanager.numoftgscopes
 case {1,2}
  columns = 1;
 case {3,4,5,6}
  columns = 2;
 case {7,8,9,10,11,12}
  columns = 3;
 otherwise
  columns = 1;
end
rows = columns;
if (rows * columns < targetmanager.numoftgscopes)
  rows = rows + 1;
end

oldpos =   get(targetmanager.figure,'Position');
position = [oldpos(1), oldpos(2), ...
            (pbdim_x + 30) * columns, ...
            pbdim_y * rows + 150 - 30 / rows + 5 * rows];
set(targetmanager.figure,'Position',position,'Visible','off');
set(targetmanager.multiplepb,'Position',[position(3)/2-45,position(4)-60,90,40],'Visible','on','CallBack','xpctgscope(-2)');
%set(targetmanager.frame,'Position',[5,10,(pbdim_x+30)*columns-10,(pbdim_y*rows+150-30/rows+5*rows)-80]);
%set(targetmanager.frametitle,'Position',[15,(pbdim_y*rows+150-30/rows+5*rows)-85,80,20]);

if targetmanager.numoftgscopes==0
  position=[oldpos(1),oldpos(2),(pbdim_x+30)*columns,pbdim_y*rows+40];
  set(targetmanager.figure,'Position',position);
end
if targetmanager.numoftgscopes==1
  position=[oldpos(1),oldpos(2),(pbdim_x+30)*columns,pbdim_y*rows+40];
  set(targetmanager.figure,'Position',position);
  set(targetmanager.tgscpb(1),'Position',[position(3)/2-pbdim_x/2,position(4)-60,pbdim_x,pbdim_y]);
  set(targetmanager.patch(1), ...
      'XData',[position(3)/2-pbdim_x/2-offset,...
               position(3)/2-pbdim_x/2+offset+pbdim_x,...
               position(3)/2-pbdim_x/2+offset+pbdim_x,...
               position(3)/2-pbdim_x/2-offset],...
      'YData',[position(4)-60-offset,...
               position(4)-60-offset,...
               position(4)-60+offset+pbdim_y,...
               position(4)-60+offset+pbdim_y],'FaceColor','b',...
      'Tag','1','EraseMode','normal');

  set(targetmanager.multiplepb,'Visible','off');
  set(targetmanager.tgscpb(1),'Visible','on');
  set(targetmanager.patch(1),'Visible','on');
end

if targetmanager.numoftgscopes==2
  set(targetmanager.tgscpb(1),'Position',[(position(3)/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.tgscpb(1),'Position',[position(3)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(1),...
      'XData',[position(3)/2-pbdim_x/2-offset,...
               position(3)/2-pbdim_x/2+offset+pbdim_x,...
               position(3)/2-pbdim_x/2+offset+pbdim_x,...
               position(3)/2-pbdim_x/2-offset],...
      'YData',[position(4)-130-offset,...
               position(4)-130-offset,...
               position(4)-130+offset+pbdim_y,...
               position(4)-130+offset+pbdim_y],'FaceColor','b',...
      'Tag','1','EraseMode','normal');
  set(targetmanager.tgscpb(2),'Position', ...
                    [position(3)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(2), ...
      'XData',[position(3)/2-pbdim_x/2-offset,...
               position(3)/2-pbdim_x/2+offset+pbdim_x,...
               position(3)/2-pbdim_x/2+offset+pbdim_x,...
               position(3)/2-pbdim_x/2-offset],...
      'YData',[position(4)-190-offset,...
               position(4)-190-offset,...
               position(4)-190+offset+pbdim_y,...
               position(4)-190+offset+pbdim_y],'FaceColor','b',...
      'Tag','2','EraseMode','normal');

  for i=1:2
    set(targetmanager.tgscpb(i),'Visible','on');
    set(targetmanager.patch(i),'Visible','on');
  end
end

if targetmanager.numoftgscopes==3
  set(targetmanager.tgscpb(1),'Position',[(position(3)/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(1),'XData',[(position(3)/2)/2-pbdim_x/2-offset,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','1','EraseMode','normal');
  set(targetmanager.tgscpb(2),'Position',[(position(3)/2)+(position(3)/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(2),'XData',[(position(3)/2)+(position(3)/2)/2-pbdim_x/2-offset,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','2','EraseMode','normal');

  set(targetmanager.tgscpb(3),'Position',[(position(3)/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(3),'XData',[(position(3)/2)/2-pbdim_x/2-offset,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','3','EraseMode','normal');
  for i=1:3
    set(targetmanager.tgscpb(i),'Visible','on');
    set(targetmanager.patch(i),'Visible','on');
  end
end

if targetmanager.numoftgscopes==4
  set(targetmanager.tgscpb(1),'Position',[(position(3)/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(1),'XData',[(position(3)/2)/2-pbdim_x/2-offset,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','1','EraseMode','normal');
  set(targetmanager.tgscpb(2),'Position', ...
                    [(position(3)/2)+(position(3)/2)/2-pbdim_x/2, ...
                     position(4)-130, pbdim_x, pbdim_y]);
  set(targetmanager.patch(2),'XData', ...
                    [(position(3)/2)+(position(3)/2)/2-pbdim_x/2-offset, ...
                     (position(3)/2)+(position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','2','EraseMode','normal');

  set(targetmanager.tgscpb(3),'Position',[(position(3)/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(3),'XData',[(position(3)/2)/2-pbdim_x/2-offset,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','3','EraseMode','normal');
  set(targetmanager.tgscpb(4),'Position',[(position(3)/2)+(position(3)/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(4),'XData',[(position(3)/2)+(position(3)/2)/2-pbdim_x/2-offset,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','4','EraseMode','normal');
  for i=1:4
    set(targetmanager.tgscpb(i),'Visible','on');
    set(targetmanager.patch(i),'Visible','on');
  end
end

if targetmanager.numoftgscopes==5
  set(targetmanager.tgscpb(1),'Position',[(position(3)/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(1),'XData',[(position(3)/2)/2-pbdim_x/2-offset,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','1','EraseMode','normal');
  set(targetmanager.tgscpb(2),'Position',[(position(3)/2)+(position(3)/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(2),'XData',[(position(3)/2)+(position(3)/2)/2-pbdim_x/2-offset,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','2','EraseMode','normal');

  set(targetmanager.tgscpb(3),'Position',[(position(3)/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(3),'XData',[(position(3)/2)/2-pbdim_x/2-offset,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','3','EraseMode','normal');
  set(targetmanager.tgscpb(4),'Position',[(position(3)/2)+(position(3)/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(4),'XData',[(position(3)/2)+(position(3)/2)/2-pbdim_x/2-offset,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','4','EraseMode','normal');
  set(targetmanager.tgscpb(5),'Position',[(position(3)/2)/2-pbdim_x/2,position(4)-250,pbdim_x,pbdim_y]);
  set(targetmanager.patch(5),'XData',[(position(3)/2)/2-pbdim_x/2-offset,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-250-offset,...
                      position(4)-250-offset,...
                      position(4)-250+offset+pbdim_y,...
                      position(4)-250+offset+pbdim_y],'FaceColor','b',...
                    'Tag','5','EraseMode','normal');
  for i=1:5
    set(targetmanager.tgscpb(i),'Visible','on');
    set(targetmanager.patch(i),'Visible','on');
  end
end

if targetmanager.numoftgscopes==6
  set(targetmanager.tgscpb(1),'Position',[(position(3)/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(1),'XData',[(position(3)/2)/2-pbdim_x/2-offset,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','1','EraseMode','normal');
  set(targetmanager.tgscpb(2),'Position',[(position(3)/2)+(position(3)/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(2),'XData',[(position(3)/2)+(position(3)/2)/2-pbdim_x/2-offset,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','2','EraseMode','normal');

  set(targetmanager.tgscpb(3),'Position',[(position(3)/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(3),'XData',[(position(3)/2)/2-pbdim_x/2-offset,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','3','EraseMode','normal');
  set(targetmanager.tgscpb(4),'Position',[(position(3)/2)+(position(3)/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(4),'XData',[(position(3)/2)+(position(3)/2)/2-pbdim_x/2-offset,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','4','EraseMode','normal');
  set(targetmanager.tgscpb(5),'Position',[(position(3)/2)/2-pbdim_x/2,position(4)-250,pbdim_x,pbdim_y]);
  set(targetmanager.patch(5),'XData',[(position(3)/2)/2-pbdim_x/2-offset,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-250-offset,...
                      position(4)-250-offset,...
                      position(4)-250+offset+pbdim_y,...
                      position(4)-250+offset+pbdim_y],'FaceColor','b',...
                    'Tag','5','EraseMode','normal');
  set(targetmanager.tgscpb(6),'Position',[(position(3)/2)+(position(3)/2)/2-pbdim_x/2,position(4)-250,pbdim_x,pbdim_y]);
  set(targetmanager.patch(6),'XData',[(position(3)/2)+(position(3)/2)/2-pbdim_x/2-offset,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)+(position(3)/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-250-offset,...
                      position(4)-250-offset,...
                      position(4)-250+offset+pbdim_y,...
                      position(4)-250+offset+pbdim_y],'FaceColor','b',...
                    'Tag','6','EraseMode','normal');
  for i=1:6
    set(targetmanager.tgscpb(i),'Visible','on');
    set(targetmanager.patch(i),'Visible','on');
  end
end

if targetmanager.numoftgscopes==7
  set(targetmanager.tgscpb(1),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(1),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','1','EraseMode','normal');
  set(targetmanager.tgscpb(2),'Position',[(position(3)/2)-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(2),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','2','EraseMode','normal');
  set(targetmanager.tgscpb(3),'Position',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(3),'XData',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','3','EraseMode','normal');
  set(targetmanager.tgscpb(4),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(4),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','4','EraseMode','normal');
  set(targetmanager.tgscpb(5),'Position',[(position(3)/2)-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(5),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','5','EraseMode','normal');
  set(targetmanager.tgscpb(6),'Position',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(6),'XData',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','6','EraseMode','normal');
  set(targetmanager.tgscpb(7),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-250,pbdim_x,pbdim_y]);
  set(targetmanager.patch(7),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-250-offset,...
                      position(4)-250-offset,...
                      position(4)-250+offset+pbdim_y,...
                      position(4)-250+offset+pbdim_y],'FaceColor','b',...
                    'Tag','7','EraseMode','normal');
  for i=1:7
    set(targetmanager.tgscpb(i),'Visible','on');
    set(targetmanager.patch(i),'Visible','on');
  end
end

if targetmanager.numoftgscopes==8
  set(targetmanager.tgscpb(1),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(1),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','1','EraseMode','normal');
  set(targetmanager.tgscpb(2),'Position',[(position(3)/2)-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(2),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','2','EraseMode','normal');
  set(targetmanager.tgscpb(3),'Position',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(3),'XData',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','3','EraseMode','normal');
  set(targetmanager.tgscpb(4),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(4),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','4','EraseMode','normal');
  set(targetmanager.tgscpb(5),'Position',[(position(3)/2)-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(5),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','5','EraseMode','normal');
  set(targetmanager.tgscpb(6),'Position',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(6),'XData',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','6','EraseMode','normal');
  set(targetmanager.tgscpb(7),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-250,pbdim_x,pbdim_y]);
  set(targetmanager.patch(7),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-250-offset,...
                      position(4)-250-offset,...
                      position(4)-250+offset+pbdim_y,...
                      position(4)-250+offset+pbdim_y],'FaceColor','b',...
                    'Tag','7','EraseMode','normal');
  set(targetmanager.tgscpb(8),'Position',[(position(3)/2)-pbdim_x/2,position(4)-250,pbdim_x,pbdim_y]);
  set(targetmanager.patch(8),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-250-offset,...
                      position(4)-250-offset,...
                      position(4)-250+offset+pbdim_y,...
                      position(4)-250+offset+pbdim_y],'FaceColor','b',...
                    'Tag','8','EraseMode','normal');
  for i=1:8
    set(targetmanager.tgscpb(i),'Visible','on');
    set(targetmanager.patch(i),'Visible','on');
  end
end

if targetmanager.numoftgscopes==9
  set(targetmanager.tgscpb(1),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(1),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','1','EraseMode','normal');
  set(targetmanager.tgscpb(2),'Position',[(position(3)/2)-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(2),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','2','EraseMode','normal');
  set(targetmanager.tgscpb(3),'Position',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(3),'XData',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','3','EraseMode','normal');
  set(targetmanager.tgscpb(4),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(4),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','4','EraseMode','normal');
  set(targetmanager.tgscpb(5),'Position',[(position(3)/2)-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(5),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','5','EraseMode','normal');
  set(targetmanager.tgscpb(6),'Position',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(6),'XData',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','6','EraseMode','normal');
  set(targetmanager.tgscpb(7),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-250,pbdim_x,pbdim_y]);
  set(targetmanager.patch(7),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-250-offset,...
                      position(4)-250-offset,...
                      position(4)-250+offset+pbdim_y,...
                      position(4)-250+offset+pbdim_y],'FaceColor','b',...
                    'Tag','7','EraseMode','normal');
  set(targetmanager.tgscpb(8),'Position',[(position(3)/2)-pbdim_x/2,position(4)-250,pbdim_x,pbdim_y]);
  set(targetmanager.patch(8),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-250-offset,...
                      position(4)-250-offset,...
                      position(4)-250+offset+pbdim_y,...
                      position(4)-250+offset+pbdim_y],'FaceColor','b',...
                    'Tag','8','EraseMode','normal');
  set(targetmanager.tgscpb(9),'Position',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-250,pbdim_x,pbdim_y]);
  set(targetmanager.patch(9),'XData',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-250-offset,...
                      position(4)-250-offset,...
                      position(4)-250+offset+pbdim_y,...
                      position(4)-250+offset+pbdim_y],'FaceColor','b',...
                    'Tag','9','EraseMode','normal');
  for i=1:9
    set(targetmanager.tgscpb(i),'Visible','on');
    set(targetmanager.patch(i),'Visible','on');
  end
end

if targetmanager.numoftgscopes==10
  set(targetmanager.tgscpb(1),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(1),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','1','EraseMode','normal');
  set(targetmanager.tgscpb(2),'Position',[(position(3)/2)-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(2),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','2','EraseMode','normal');
  set(targetmanager.tgscpb(3),'Position',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(3),'XData',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','3','EraseMode','normal');
  set(targetmanager.tgscpb(4),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(4),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','4','EraseMode','normal');
  set(targetmanager.tgscpb(5),'Position',[(position(3)/2)-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(5),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','5','EraseMode','normal');
  set(targetmanager.tgscpb(6),'Position',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(6),'XData',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','6','EraseMode','normal');
  set(targetmanager.tgscpb(7),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-250,pbdim_x,pbdim_y]);
  set(targetmanager.patch(7),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-250-offset,...
                      position(4)-250-offset,...
                      position(4)-250+offset+pbdim_y,...
                      position(4)-250+offset+pbdim_y],'FaceColor','b',...
                    'Tag','7','EraseMode','normal');
  set(targetmanager.tgscpb(8),'Position',[(position(3)/2)-pbdim_x/2,position(4)-250,pbdim_x,pbdim_y]);
  set(targetmanager.patch(8),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-250-offset,...
                      position(4)-250-offset,...
                      position(4)-250+offset+pbdim_y,...
                      position(4)-250+offset+pbdim_y],'FaceColor','b',...
                    'Tag','8','EraseMode','normal');
  set(targetmanager.tgscpb(9),'Position',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-250,pbdim_x,pbdim_y]);
  set(targetmanager.patch(9),'XData',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-250-offset,...
                      position(4)-250-offset,...
                      position(4)-250+offset+pbdim_y,...
                      position(4)-250+offset+pbdim_y],'FaceColor','b',...
                    'Tag','9','EraseMode','normal');
  set(targetmanager.tgscpb(10),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-310,pbdim_x,pbdim_y]);
  set(targetmanager.patch(10),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-310-offset,...
                      position(4)-310-offset,...
                      position(4)-310+offset+pbdim_y,...
                      position(4)-310+offset+pbdim_y],'FaceColor','b',...
                    'Tag','10','EraseMode','normal');
  for i=1:10
    set(targetmanager.tgscpb(i),'Visible','on');
    set(targetmanager.patch(i),'Visible','on');
  end
end

if targetmanager.numoftgscopes==11
  set(targetmanager.tgscpb(1),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(1),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','1','EraseMode','normal');
  set(targetmanager.tgscpb(2),'Position',[(position(3)/2)-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(2),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','2','EraseMode','normal');
  set(targetmanager.tgscpb(3),'Position',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(3),'XData',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','3','EraseMode','normal');
  set(targetmanager.tgscpb(4),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(4),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','4','EraseMode','normal');
  set(targetmanager.tgscpb(5),'Position',[(position(3)/2)-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(5),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','5','EraseMode','normal');
  set(targetmanager.tgscpb(6),'Position',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(6),'XData',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','6','EraseMode','normal');
  set(targetmanager.tgscpb(7),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-250,pbdim_x,pbdim_y]);
  set(targetmanager.patch(7),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-250-offset,...
                      position(4)-250-offset,...
                      position(4)-250+offset+pbdim_y,...
                      position(4)-250+offset+pbdim_y],'FaceColor','b',...
                    'Tag','7','EraseMode','normal');
  set(targetmanager.tgscpb(8),'Position',[(position(3)/2)-pbdim_x/2,position(4)-250,pbdim_x,pbdim_y]);
  set(targetmanager.patch(8),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-250-offset,...
                      position(4)-250-offset,...
                      position(4)-250+offset+pbdim_y,...
                      position(4)-250+offset+pbdim_y],'FaceColor','b',...
                    'Tag','8','EraseMode','normal');
  set(targetmanager.tgscpb(9),'Position',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-250,pbdim_x,pbdim_y]);
  set(targetmanager.patch(9),'XData',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-250-offset,...
                      position(4)-250-offset,...
                      position(4)-250+offset+pbdim_y,...
                      position(4)-250+offset+pbdim_y],'FaceColor','b',...
                    'Tag','9','EraseMode','normal');
  set(targetmanager.tgscpb(10),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-310,pbdim_x,pbdim_y]);
  set(targetmanager.patch(10),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-310-offset,...
                      position(4)-310-offset,...
                      position(4)-310+offset+pbdim_y,...
                      position(4)-310+offset+pbdim_y],'FaceColor','b',...
                    'Tag','10','EraseMode','normal');
  set(targetmanager.tgscpb(11),'Position',[(position(3)/2)-pbdim_x/2,position(4)-310,pbdim_x,pbdim_y]);
  set(targetmanager.patch(11),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-310-offset,...
                      position(4)-310-offset,...
                      position(4)-310+offset+pbdim_y,...
                      position(4)-310+offset+pbdim_y],'FaceColor','b',...
                    'Tag','11','EraseMode','normal');
  for i=1:11
    set(targetmanager.tgscpb(i),'Visible','on');
    set(targetmanager.patch(i),'Visible','on');
  end
end

if targetmanager.numoftgscopes==12
  set(targetmanager.tgscpb(1),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(1),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','1','EraseMode','normal');
  set(targetmanager.tgscpb(2),'Position',[(position(3)/2)-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(2),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','2','EraseMode','normal');
  set(targetmanager.tgscpb(3),'Position',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-130,pbdim_x,pbdim_y]);
  set(targetmanager.patch(3),'XData',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-130-offset,...
                      position(4)-130-offset,...
                      position(4)-130+offset+pbdim_y,...
                      position(4)-130+offset+pbdim_y],'FaceColor','b',...
                    'Tag','3','EraseMode','normal');
  set(targetmanager.tgscpb(4),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(4),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','4','EraseMode','normal');
  set(targetmanager.tgscpb(5),'Position',[(position(3)/2)-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(5),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','5','EraseMode','normal');
  set(targetmanager.tgscpb(6),'Position',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-190,pbdim_x,pbdim_y]);
  set(targetmanager.patch(6),'XData',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-190-offset,...
                      position(4)-190-offset,...
                      position(4)-190+offset+pbdim_y,...
                      position(4)-190+offset+pbdim_y],'FaceColor','b',...
                    'Tag','6','EraseMode','normal');
  set(targetmanager.tgscpb(7),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-250,pbdim_x,pbdim_y]);
  set(targetmanager.patch(7),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-250-offset,...
                      position(4)-250-offset,...
                      position(4)-250+offset+pbdim_y,...
                      position(4)-250+offset+pbdim_y],'FaceColor','b',...
                    'Tag','7','EraseMode','normal');
  set(targetmanager.tgscpb(8),'Position',[(position(3)/2)-pbdim_x/2,position(4)-250,pbdim_x,pbdim_y]);
  set(targetmanager.patch(8),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-250-offset,...
                      position(4)-250-offset,...
                      position(4)-250+offset+pbdim_y,...
                      position(4)-250+offset+pbdim_y],'FaceColor','b',...
                    'Tag','8','EraseMode','normal');
  set(targetmanager.tgscpb(9),'Position',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-250,pbdim_x,pbdim_y]);
  set(targetmanager.patch(9),'XData',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-250-offset,...
                      position(4)-250-offset,...
                      position(4)-250+offset+pbdim_y,...
                      position(4)-250+offset+pbdim_y],'FaceColor','b',...
                    'Tag','9','EraseMode','normal');
  set(targetmanager.tgscpb(10),'Position',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-310,pbdim_x,pbdim_y]);
  set(targetmanager.patch(10),'XData',[((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      ((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-310-offset,...
                      position(4)-310-offset,...
                      position(4)-310+offset+pbdim_y,...
                      position(4)-310+offset+pbdim_y],'FaceColor','b',...
                    'Tag','10','EraseMode','normal');
  set(targetmanager.tgscpb(11),'Position',[(position(3)/2)-pbdim_x/2,position(4)-310,pbdim_x,pbdim_y]);
  set(targetmanager.patch(11),'XData',[(position(3)/2)-pbdim_x/2-offset,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2)-pbdim_x/2-offset],...
                    'YData',[position(4)-310-offset,...
                      position(4)-310-offset,...
                      position(4)-310+offset+pbdim_y,...
                      position(4)-310+offset+pbdim_y],'FaceColor','b',...
                    'Tag','11','EraseMode','normal');
  set(targetmanager.tgscpb(12),'Position',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2,position(4)-310,pbdim_x,pbdim_y]);
  set(targetmanager.patch(12),'XData',[(position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2+offset+pbdim_x,...
                      (position(3)/2+pbdim_x/2)+((position(3)/2)-pbdim_x/2)/2-pbdim_x/2-offset],...
                    'YData',[position(4)-310-offset,...
                      position(4)-310-offset,...
                      position(4)-310+offset+pbdim_y,...
                      position(4)-310+offset+pbdim_y],'FaceColor','b',...
                    'Tag','12','EraseMode','normal');
  for i=1:12
    set(targetmanager.tgscpb(i),'Visible','on');
    set(targetmanager.patch(i),'Visible','on');
  end
end
%hand;e top of screen resizing
scdata=get(0,'Screensize');
yscmax=scdata(4);
scopedata=get(targetmanager.figure,'Position');
ydelta=scopedata(4);
scmngrypos=position(2)+ ydelta;
if (scmngrypos > yscmax)
    set(targetmanager.figure,'Position',[scopedata(1) yscmax-ydelta-40 scopedata(3) scopedata(4)]);
end
%---------------------------
set(targetmanager.figure,'Visible','on');


function targetmanager=create_contextmenupb(targetmanager)

set(0,'currentfigure',targetmanager.figure)
for i=1:12

  targetmanager.contextmenu(i)=uicontextmenu;

  targetmanager.menu(i).properties = ...
      uimenu(targetmanager.contextmenu(i), ...
             'Label','Properties', ...
             'CallBack', 'xpctgscope(-3)', ...
             'UserData', get(targetmanager.tgscpb(i),'UserData'),...
             'Tag','Subuimenu1');

  targetmanager.menu(i).startstop = ...
      uimenu(targetmanager.contextmenu(i), ...
             'Label','Start', ...
             'Separator','on', ...
             'Enable','off',...
             'CallBack', 'xpctgscope(-4)', ...
             'Tag','Subuimenu1');

  targetmanager.menu(i).softtrig = ...
      uimenu(targetmanager.contextmenu(i), ...
             'Label','Software Trigger', ...
             'Separator','on', ...
             'Enable','off',...
             'CallBack', 'xpctgscope(-5)', ...
             'Tag','Subuimenu1');

  targetmanager.menu(i).delete = ...
      uimenu(targetmanager.contextmenu(i), ...
             'Label','Delete', ...
             'Separator','on', ...
             'CallBack', 'xpctgscope(-6)', ...
             'Tag','Subuimenu1');

  set(targetmanager.tgscpb(i),'UIContextMenu',  targetmanager.contextmenu(i));
end

function targetmanager = create_contextmenupatches(targetmanager)
for i = 1 : 12
  set(targetmanager.patch(i), 'UIContextMenu', targetmanager.contextmenu(i));
end

function targetmanager=create_patches(targetmanager)
pb = targetmanager.tgscpb;
for i = 1:12
  targetmanager.patch(i) = patch('UserData', get(pb(i), 'UserData'), ...
                                 'Tag', num2str(i));
end
