// mwhpe1432.idl : IDL source for mwwinsound.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (mwwinsound.tlb) and marshalling code.

// Copyright 1998-2003 The MathWorks, Inc. 
// $Revision: 1.1.6.2 $  $Date: 2003/12/04 18:39:29 $


import "oaidl.idl";
import "ocidl.idl";
		
[
	uuid(B426BC63-9E77-11d2-A134-444553540000),
	version(1.0),
	helpstring("mwhpxvi 1.0 Type Library")
]
library MWHPVXILib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	
	[
		uuid(7A842F2A-B3F6-11d3-B32F-00A0C9F223E2),
		helpstring("MATLAB hpe1432 Analog input")
	]
	coclass hpvxiAD
	{
		[default] interface IUnknown;		
	};

	
	[
		uuid(7A842F2B-B3F6-11d3-B32F-00A0C9F223E2),
		helpstring("MATLAB hpe1432 Analog output")
	]
	coclass hpvxiDA
	{
		[default] interface IUnknown;
	};

};
