/*
 * @(#)randsrc_gc_d_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:34 2004
 *
 *		built from:	randsrc_gc_d_rt.c
 */

#ifndef randsrc_gc_d_rt_h
#define randsrc_gc_d_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_RandSrc_GC_D(real64_T *y,          /* output signal */            
                        const real64_T *mean, /* vector of means */          
                        int_T meanLen,        /* length of mean vector */    
                        const real64_T *std,  /* vector of xformed-std-devs*/
                        int_T stdLen,         /* length of std vector */     
                        real64_T *state,      /* state vectors */            
                        int_T nChans,         /* number of channels */       
                        int_T nSamps,         /* number of samples per chan*/
                        real64_T* cltVec,     /* work space for uniform 
                                               * variates */
                        int_T cltLen);         /* length of clt vector */

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* randsrc_gc_d_rt_h */
