/*
 * @(#)randsrcinitstate_u_64_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:34 2004
 *
 *		built from:	randsrcinitstate_u_64_rt.c
 */

#ifndef randsrcinitstate_u_64_rt_h
#define randsrcinitstate_u_64_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_RandSrcInitState_U_64(const uint32_T *seed,  /* seed value vector */
                                 real64_T       *state, /* state vectors */
                                 int_T          nChans); /* number of channels */

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* randsrcinitstate_u_64_rt_h */
