/*
 * @(#)randsrccreateseeds_64_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:34 2004
 *
 *		built from:	randsrccreateseeds_64_rt.c
 */

#ifndef randsrccreateseeds_64_rt_h
#define randsrccreateseeds_64_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_RandSrcCreateSeeds_64(uint32_T  initSeed,
                                 uint32_T *seedArray,
                                 uint32_T  numSeeds);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* randsrccreateseeds_64_rt_h */
