/*
 * @(#)lu_d_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:29 2004
 *
 *		built from:	lu_d_rt.c
 */

#ifndef lu_d_rt_h
#define lu_d_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_lu_D(
          real_T    *A,       /* Input Pointer */ 
          real_T    *piv,     /* Ouyput (P) Pointer */
    const int_T      n,       /* P-port width */ 
          boolean_T *singular /* Singularity of input */
    );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* lu_d_rt_h */
