function copy_target_props(srcTarget,dstTarget)
%COPY_TARGET_PROPS(SRCTARGETID,DSTTARGETID)

%   Copyright 1995-2003 The MathWorks, Inc.
%   $Revision: 1.5.2.2 $  $Date: 2004/04/15 00:56:27 $

sf('set',dstTarget,...
   '.description',sf('get',srcTarget,'.description')...
   ,'.customCode',sf('get',srcTarget,'.customCode')...
   ,'.reservedNames',sf('get',srcTarget,'.reservedNames')...
   ,'.customInitializer',sf('get',srcTarget,'.customInitializer')...
   ,'.customTerminator',sf('get',srcTarget,'.customTerminator')...
   ,'.codeFlags',sf('get',srcTarget,'.codeFlags')...
   ,'.makeCommand',sf('get',srcTarget,'.makeCommand')...
   ,'.targetFunction',sf('get',srcTarget,'.targetFunction')...
   ,'.codegenDirectory',sf('get',srcTarget,'.codegenDirectory')...
   ,'.userSources',sf('get',srcTarget,'.userSources')...
   ,'.userIncludeDirs',sf('get',srcTarget,'.userIncludeDirs')...
   ,'.userLibraries',sf('get',srcTarget,'.userLibraries')...
   ,'.userMakefiles',sf('get',srcTarget,'.userMakefiles')...
   ,'.applyToAllLibs',sf('get',srcTarget,'.applyToAllLibs')...
   ,'.document',sf('get',srcTarget,'.document'));
   