function [fig, c] = dlg_figure( objectId, dlgfunc, tag )
%[FIG, CONSTANTS] = DLG_FIGURE( OBJECTID, DLGFUNC, TAG )

%   E.Mehran Mestchian
%   Copyright 1995-2002 The MathWorks, Inc.
%   $Revision: 1.19.2.1 $  $Date: 2004/04/15 00:56:54 $

	defColor = get(0,'defaultuicontrolbackground');
	c.backColor = defColor;
	c.controlColor = c.backColor;
   closeFcn = ['sf(''Private'',''' dlgfunc ''',''cancel'',' sprintf('%d',objectId) ');'];

	fig = figure(...
       'NumberTitle','off'...
      ,'Menu','none'...
	  ,'Toolbar', 'none' ...
      ,'Tag', tag...
      ,'HandleVisibility', 'callback'...
      ,'Visible','off'...
      ,'Color',c.backColor...
      ,'Resize','on'...
      ,'CloseRequestFcn',closeFcn...
      ,'DeleteFcn',''...
      ,'WindowButtonDown',['sf(''Private'',''' dlgfunc ''');']...
      ,'WindowButtonMotion',''...EMM to be used later!['sf(''Private'',''dlg_mouse'');']...
      ,'Units','points'...
      ,'IntegerHandle','off'...
      ,'DefaultUiControlUnits','points'...
      ,'DefaultUiControlCallback',['sf(''Private'',''' dlgfunc ''');']...
      ,'DefaultUiControlClipping','off'...
      ,'DefaultUiControlHorizontalAlign','left'...
      ,'DefaultUiControlEnable','on'...
      ,'Interruptible','off'...
      ,'BusyAction','cancel'...
	);



