function sf_demo_disclaimer
% SF_DEMO_DISCLAIMER
%	produces an error dialog with an appropriate 
%   Stateflow Demonstration Version disclaimer message.
%

%   Copyright 1995-2004 The MathWorks, Inc.
%   $Revision: 1.5.4.2 $  $Date: 2004/04/15 00:59:27 $

    if(exist(fullfile(matlabroot,'toolbox','stateflow','stateflow','Contents.m')))
        errordlg(...
            ['Maximum number of users reached for Stateflow.',10,...
             'Defaulting to a demonstration version of Stateflow.',10 ...
            ,'You can LOAD and SIMULATE Stateflow DEMO diagrams only. Saving',10 ...
            ,'Simulink models containing Stateflow blocks is prohibited.'], 'Unsupported operation for Stateflow Demo License.' ...
        );
    else
        errordlg(...
            ['Stateflow license could not be checked out.',10,...
             'Defaulting to a demonstration version of Stateflow.',10 ...
            ,'You can LOAD and SIMULATE Stateflow DEMO diagrams only. Saving',10 ...
            ,'Simulink models containing Stateflow blocks is prohibited.'], 'Unsupported operation for Stateflow Demo License.' ...
        );
    end