// Copyright 1998-2003 The MathWorks, Inc. 
// $Revision: 1.4.4.5 $  $Date: 2003/12/04 18:39:56 $


// mwnidaq.idl : IDL source for mwnidaq.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (mwnidaq.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "daqmex.idl";
	
	
	[
		object,
		uuid(D96CE0F1-066A-11D4-A55A-00902757EA8D),
		dual,
		helpstring("IniDisp Interface"),
		pointer_default(unique)
	]
	interface IniDisp : IDispatch
	{
		[id(1), helpstring("method Select_Signal")] HRESULT Select_Signal(unsigned long signal,unsigned long source,unsigned long sourceSpec);
		[id(2), helpstring("method Calibrate_1200")] HRESULT Calibrate_1200(short calOP,short saveNewCal,short EEPROMloc,short calRevChan,short gndRefChan,short DAC0chan,short DAC1chan,double calRefVolts,double gain);
		[id(3), helpstring("method Calibrate_DSA")] HRESULT Calibrate_DSA(unsigned long operation,double refVoltage);
		[id(4), helpstring("method Calibrate_E_Series")] HRESULT Calibrate_E_Series(unsigned long calOP,unsigned long setOfCalConst,double calRefVolts);
		[id(5), helpstring("method AO_Calibrate")] HRESULT AO_Calibrate(short operation,short EEPROMloc);
		[id(6), helpstring("method AI_Change_Parameter")] HRESULT AI_Change_Parameter(short channel, unsigned long paramID, unsigned long paramValue);
	};
	
[
	uuid(D0C329C1-E0FF-11D1-A21F-00A024E7DC56),
	version(1.0),
	helpstring("mwnidaq 2.1 Type Library")
]
library MWNIDAQLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(8BEEFAC3-E54A-11d3-A551-00902757EA8D),
		helpstring("niAdaptor Class")
	]
	coclass CniAdaptor
	{
		[default] interface ImwAdaptor;
	};
	
	[
		uuid(F4A40AF4-BC90-11d3-A53C-00902757EA8D),
		helpstring("nia2d Class"),
		noncreatable
	]
	coclass Cnia2d
	{
		[default] interface IniDisp;
		interface ImwDevice;
		interface ImwInput;
	};

	
	[
		uuid(F4A40AF5-BC90-11d3-A53C-00902757EA8D),
		helpstring("nid2a Class"),
		noncreatable
	]
	coclass Cnid2a
	{
		[default] interface IniDisp;
		interface ImwDevice;
		interface ImwOutput;

	};

	
	[
		uuid(F4A40AF6-BC90-11d3-A53C-00902757EA8D),
		helpstring("niDIO Class")
	]
	coclass niDIO
	{
		[default] interface IniDisp;
		interface ImwDevice;
		interface ImwDIO;
	};
	
	[
		uuid(D96CE0F2-066A-11D4-A55A-00902757EA8D),
		helpstring("niDisp Class")
	]
	coclass niDisp
	{
		[default] interface IniDisp;
	};
};
