/*
 * @(#)fir_tdf_zd_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:24 2004
 *
 *		built from:	fir_tdf_zd_rt.c
 */

#ifndef fir_tdf_zd_rt_h
#define fir_tdf_zd_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_FIR_TDF_ZD(const creal_T         *u,
                      creal_T               *y,
                      creal_T * const       mem_base,
                      const int_T           numDelays,
                      const int_T           sampsPerChan,
                      const int_T           numChans,
                      const real_T * const  num,
                      const int_T           ordNUM,
                      const boolean_T       one_fpf);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* fir_tdf_zd_rt_h */
