function fig = xpcsetupfig()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.


%   Copyright 1999-2004 The MathWorks, Inc.
%   $Revision: 1.7.2.4 $  $Date: 2004/04/08 21:04:44 $

load xpxsetupfig

h0 = figure('Color',get(0,'DefaultUicontrolBackgroundColor'), ...
	'Colormap',mat0, ...
	'FileName','D:\Work\rlwork\xpctarget\xpc\private\xpcsetupfig.m', ...
	'MenuBar','none', ...
	'Name','xPC Target Setup', ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'Position',[528 424 620 460], ...
   'Visible','off',...
   'HandleVis','off',...
	'Tag','setupfigure', ...
	'ToolBar','none');
h1 = uimenu('Parent',h0, ...
	'Label','File', ...
	'Tag','uimenu1');
h2 = uimenu('Parent',h1, ...
	'Label','Load Settings', ...
	'Tag','menuload');
h2 = uimenu('Parent',h1, ...
	'Label','Save Settings', ...
	'Tag','menusave');
h2 = uimenu('Parent',h1, ...
	'Label','Close', ...
	'Separator','on', ...
	'Tag','menuclose');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[7.5 92.25 447 39], ...
	'Style','frame',...
	'Tag','Frame2');
%    'BackGroundColor', get(0,'DefaultUicontrolBackgroundColor'),...
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[7.5 143.25 447 189.75], ...
	'Style','frame', ...
	'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[14.25 306 67.5 12.75], ...
	'String','Version:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[237 307.5 74.25 12.75], ...
	'String','RS232HostPort:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[237 291.75 67.5 11.25], ...
	'String','RS232BaudRate:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[237 275.25 86.25 11.25], ...
	'String','TcpIpTargetAddress:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[237 150.75 87.75 12.75], ...
	'String','TcpIpTargetISAIRQ:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[237 168.75 97.5 12.75], ...
	'String','TcpIpTargetISAMemPort:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[237 186.75 78.75 12.75], ...
	'String','TcpIpTargetBusType:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[237 204 75.75 12.75], ...
	'String','TcpIpTargetDriver:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[237 222 67.5 12.75], ...
	'String','TcpIpGateway:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[237 240 75.75 12.75], ...
	'String','TcpIpSubNetMask:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[237 257.25 67.5 12.75], ...
	'String','TcpIpTargetPort:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[24.75 324.75 59.25 13.5], ...
	'String','xPC Target', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','rl32envgui(-1)', ...
	'ListboxTop',0, ...
	'Position',[41.25 9 69.75 19.5], ...
	'String','Update', ...
	'Tag','pb_update');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[333.75 204 84.75 15], ...
	'String',['NE2000  ';'SMC91C9X';'I82559  ';'RTLANCE '], ...
	'Style','popupmenu', ...
	'Tag','pop_tcpiptargetdriver', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[333.75 309 84.75 15], ...
	'String',['COM1';'COM2'], ...
	'Style','popupmenu', ...
	'Tag','pop_rs232hostport', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[333.75 291.75 84.75 15], ...
	'String',{'115200','57600','38400','19200','9600','4800','2400','1200'}, ...
	'Style','popupmenu', ...
	'Tag','pop_rs232baudrate', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','off', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[333.75 274.5 84.75 15], ...
	'String','255.255.255.255', ...
	'Style','edit', ...
	'Tag','ed_tcpiptargetaddress', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','off', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[333.75 256.5 84.75 15], ...
	'String','22222', ...
	'Style','edit', ...
	'Tag','ed_tcpiptargetport', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','off', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[333.75 239.25 84.75 15], ...
	'String','255.255.255.255', ...
	'Style','edit', ...
	'Tag','ed_tcpipsubnetmask', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','off', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[333.75 222 84.75 15], ...
	'String','255.255.255.255', ...
	'Style','edit', ...
	'Tag','ed_tcpipgateway', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','off', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[333.75 169.5 84.75 15], ...
	'String','0x300', ...
	'Style','edit', ...
	'Tag','ed_tcpiptargetisamemport', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[333.75 151.5 84.75 15], ...
	'String',mat1, ...
	'Style','popupmenu', ...
	'Tag','pop_tcpiptargetisairq', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','off', ...
	'ListboxTop',0, ...
	'Position',[333.75 186.75 84.75 15], ...
	'String',['ISA';'PCI'], ...
	'Style','popupmenu', ...
	'Tag','pop_tcpiptargetbustype', ...
	'Value',2);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[14.25 289.5 74.25 12.75], ...
	'String','CCompiler:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[14.25 254.25 70.5 12.75], ...
	'String','TargetRAMSizeMB:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[14.25 185.25 67.5 12.75], ...
	'String','HostTargetComm:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[14.25 201 67.5 12.75], ...
	'String','CANLibrary:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[14.25 218.25 67.5 12.75], ...
	'String','SystemFontSize:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[14.25 236.25 67.5 12.75], ...
	'String','MaxModelSize:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[14.25 271.5 67.5 12.75], ...
	'String','CompilerPath:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','on', ...
	'ListboxTop',0, ...
	'Position',[91.5 289.5 84.75 15], ...
	'String',['Watcom ';'VisualC'], ...
	'Style','popupmenu', ...
	'Tag','pop_compiler', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[91.5 271.5 84.75 15], ...
	'String','c:\watcom', ...
	'Style','edit', ...
	'Tag','ed_wccompilerpath');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[91.5 254.25 84.75 15], ...
	'String',['Auto  ';'Manual'], ...
	'Style','popupmenu', ...
	'Tag','pop_targetramsizemb', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[91.5 219 84.75 15], ...
	'String',['Small';'Large'], ...
	'Style','popupmenu', ...
	'Tag','pop_systemfontsize', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[91.5 201.75 84.75 15], ...
	'String',['None       ';'200 ISA    ';'527 ISA    ';'1000 PCI   ';'1000 MB PCI';'PC104      '], ...
	'Style','popupmenu', ...
	'Tag','pop_canlibrary', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[91.5 185.25 84.75 15], ...
	'String',['RS232 ';'TCP/IP'], ...
	'Style','popupmenu', ...
	'Tag','pop_hosttargetcomm', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[179.25 254.25 45 15], ...
	'Style','edit', ...
	'Tag','ed_targetramsizemb');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[91.5 236.25 84.75 15], ...
	'String',['1MB ';'4MB ';'16MB'], ...
	'Style','popupmenu', ...
	'Tag','pop_maxmodelsize', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[91.5 309 72 8.25], ...
	'String','3.0', ...
	'Style','text', ...
	'Tag','txt_rlver');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[91.5 168 84.75 15], ...
	'String',['Disabled';'Enabled '], ...
	'Style','popupmenu', ...
	'Tag','pop_targetscope', ...
	'Value',2);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[25.5 123.75 125.25 12.75], ...
	'String','xPC Target Embedded Option', ...
	'Style','text', ...
	'Tag','xPCTgEmbeddedOpt');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[14.25 168.75 60 12.75], ...
	'String','TargetScope:', ...
	'Style','text', ...
	'Tag','txt_targetscope');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[147 9 70.5 19.5], ...
	'String','Revert', ...
	'Tag','pb_revert');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[359.25 9 69.75 19.5], ...
	'String','Close', ...
	'Tag','pb_close');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[253.5 9 69.75 19.5], ...
	'String','BootDisk', ...
	'Tag','pb_bootdisk');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[14.25 152.25 60 12.75], ...
	'String','TargetMouse:', ...
	'Style','text', ...
	'Tag','txt_targetmouse');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[91.5 151.5 84.75 15], ...
	'String',['None      ';'PS2       ';'RS232 COM1';'RS232 COM2'], ...
	'Style','popupmenu', ...
	'Tag','pop_targetmouse', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[14.25 102 60 12.75], ...
	'String','TargetBoot:', ...
	'Style','text', ...
	'Tag','txt_targetboot');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[91.5 101.25 84.75 15], ...
	'String',['BootFloppy';'DOSLoader ';'StandAlone'], ...
	'Style','popupmenu', ...
	'Tag','pop_targetboot', ...
	'Value',1);

if nargout > 0, fig = h0; end
