function fig = xpctgscwinfig()

% XPCTGSCWINFIG - XPTGCSCOPE Helper Function

% Copyright 1996-2002 The MathWorks, Inc.
% $Revision: 1.7 $ $Date: 2002/03/25 04:22:21 $


h0 = figure('Color',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'MenuBar','none', ...
	'Name','xPC Target: Target Scope', ...
	'NumberTitle','off', ...
   'PaperType','a4letter', ...
   'HandleVisibility','off',...
	'Position',[523 561 254 197], ...
	'Tag','xpctgscwinfig');
setxpcfont(h0,8,9);                   
h1 = uimenu('Parent',h0, ...
	'Label','Plot', ...
	'Tag','plot');
h2 = uimenu('Parent',h1, ...
	'Label','Y-Axis', ...
	'Tag','plotmenu1');
h3 = uimenu('Parent',h2, ...
	'Label','Auto', ...
	'Tag','plotsubmenu1');
h3 = uimenu('Parent',h2, ...
	'Label','Manual', ...
	'Tag','plotsubmenu2');
h2 = uimenu('Parent',h1, ...
	'Label','Grid', ...
	'Separator','on', ...
	'Tag','plotmenu2');
h2 = uimenu('Parent',h1, ...
	'Label','Scope Mode', ...
	'Separator','on', ...
	'Tag','plotmenu4');
h3 = uimenu('Parent',h2, ...
	'Label','Numerical', ...
	'Tag','plotsubmenu30');
h3 = uimenu('Parent',h2, ...
	'Label','Graphical (redraw)', ...
	'Tag','plotsubmenu31');
h3 = uimenu('Parent',h2, ...
	'Label','Graphical (sliding)', ...
	'Tag','plotsubmenu32');
h3 = uimenu('Parent',h2, ...
	'Label','Graphical (rolling)', ...
	'Tag','plotsubmenu33');
h2 = uimenu('Parent',h1, ...
	'Label','Set X-Axis', ...
   'Separator','on', ...
   'Enable','off',...
	'Tag','plotmenu5');
h2 = uimenu('Parent',h1, ...
   'Label','Set Y-Axis', ...
   'Enable','off',...
	'Tag','plotmenu6');
h2 = uimenu('Parent',h1, ...
	'Label','Close ', ...
	'Separator','on', ...
	'Tag','plotmenu3');
h1 = uicontrol('Parent',h0, ...
	'ListboxTop',0, ...
	'Position',[9 91 100 80], ...
	'Style','frame', ...
	'Tag','frm_signal');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'ListboxTop',0, ...
	'Position',[8 8 230 70], ...
	'Style','frame', ...
	'Tag','frm_trigger');
h1 = uicontrol('Parent',h0, ...
	'ListboxTop',0, ...
	'Position',[118 92 120 80], ...
	'Style','frame', ...
	'Tag','frm_mode');
h1 = uicontrol('Parent',h0, ...
	'ListboxTop',0, ...
	'Position',[19 115 80 25], ...
	'String','Add/Remove', ...
	'Tag','pb_add_remove');
h1 = uicontrol('Parent',h0, ...
	'ListboxTop',0, ...
	'Position',[19 162 60 15], ...
	'String','SIGNALS', ...
	'Style','text', ...
	'Tag','ftl_signals');
h1 = uicontrol('Parent',h0, ...
	'ListboxTop',0, ...
	'Position',[17 70 70 15], ...
	'String','TRIGGER', ...
	'Style','text', ...
	'Tag','ftl_trigger');
h1 = uicontrol('Parent',h0, ...
	'ListboxTop',0, ...
	'Position',[129 165 60 15], ...
	'String','TRACING', ...
	'Style','text', ...
	'Tag','ftl_mode');
h1 = uicontrol('Parent',h0, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[13 49 70 15], ...
	'String','Trigger Signal:', ...
	'Style','text', ...
	'Tag','txt_triggersignal1');
h1 = uicontrol('Parent',h0, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[86 49 145 15], ...
	'String','FreeRun', ...
	'Style','text', ...
	'Tag','txt_triggersignal2');
h1 = uicontrol('Parent',h0, ...
	'ListboxTop',0, ...
	'Position',[82 19 80 25], ...
	'String','Define Trigger', ...
	'Tag','pb_definetrigger');
h1 = uicontrol('Parent',h0, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[126 142 60 15], ...
	'String','Samples', ...
	'Style','text', ...
	'Tag','txt_samples');
h1 = uicontrol('Parent',h0, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[127 106 60 15], ...
	'String','Interleave', ...
	'Style','text', ...
	'Tag','txt_interleave');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[188 107 40 18], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','ed_interleave');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[188 142 40 18], ...
	'String','250', ...
	'Style','edit', ...
	'Tag','ed_samples');
if nargout > 0, fig = h0; end
