// oct-conf.h.in
/*

Copyright (C) 1996-2012 John W. Eaton

This file is part of Octave.

Octave is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

Octave is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with Octave; see the file COPYING.  If not, see
<http://www.gnu.org/licenses/>.

*/

#if !defined (octave_conf_h)
#define octave_conf_h 1

#ifndef OCTAVE_CONF_ALL_CFLAGS
#define OCTAVE_CONF_ALL_CFLAGS ""
#endif

#ifndef OCTAVE_CONF_ALL_CXXFLAGS
#define OCTAVE_CONF_ALL_CXXFLAGS ""
#endif

#ifndef OCTAVE_CONF_ALL_FFLAGS
#define OCTAVE_CONF_ALL_FFLAGS "-O -mieee-fp"
#endif

#ifndef OCTAVE_CONF_ALL_LDFLAGS
#define OCTAVE_CONF_ALL_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_AMD_CPPFLAGS
#define OCTAVE_CONF_AMD_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_AMD_LDFLAGS
#define OCTAVE_CONF_AMD_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_AMD_LIBS
#define OCTAVE_CONF_AMD_LIBS "-lamd"
#endif

#ifndef OCTAVE_CONF_ARFLAGS
#define OCTAVE_CONF_ARFLAGS "cru "
#endif

#ifndef OCTAVE_CONF_AR
#define OCTAVE_CONF_AR "ar"
#endif

#ifndef OCTAVE_CONF_ARPACK_CPPFLAGS
#define OCTAVE_CONF_ARPACK_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_ARPACK_LDFLAGS
#define OCTAVE_CONF_ARPACK_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_ARPACK_LIBS
#define OCTAVE_CONF_ARPACK_LIBS "-larpack"
#endif

#ifndef OCTAVE_CONF_BLAS_LIBS
#define OCTAVE_CONF_BLAS_LIBS "-lblas"
#endif

#ifndef OCTAVE_CONF_CAMD_CPPFLAGS
#define OCTAVE_CONF_CAMD_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_CAMD_LDFLAGS
#define OCTAVE_CONF_CAMD_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_CAMD_LIBS
#define OCTAVE_CONF_CAMD_LIBS "-lcamd"
#endif

#ifndef OCTAVE_CONF_CARBON_LIBS
#define OCTAVE_CONF_CARBON_LIBS ""
#endif

#ifndef OCTAVE_CONF_CC
#define OCTAVE_CONF_CC "gcc -shared-libgcc"
#endif

#ifndef OCTAVE_CONF_CC_VERSION
#define OCTAVE_CONF_CC_VERSION "4.6.2 (GCC) "
#endif

#ifndef OCTAVE_CONF_CCOLAMD_CPPFLAGS
#define OCTAVE_CONF_CCOLAMD_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_CCOLAMD_LDFLAGS
#define OCTAVE_CONF_CCOLAMD_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_CCOLAMD_LIBS
#define OCTAVE_CONF_CCOLAMD_LIBS "-lccolamd"
#endif

#ifndef OCTAVE_CONF_CFLAGS
#define OCTAVE_CONF_CFLAGS "-g -O2 "
#endif

#ifndef OCTAVE_CONF_CHOLMOD_CPPFLAGS
#define OCTAVE_CONF_CHOLMOD_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_CHOLMOD_LDFLAGS
#define OCTAVE_CONF_CHOLMOD_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_CHOLMOD_LIBS
#define OCTAVE_CONF_CHOLMOD_LIBS "-lcholmod"
#endif

#ifndef OCTAVE_CONF_COLAMD_CPPFLAGS
#define OCTAVE_CONF_COLAMD_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_COLAMD_LDFLAGS
#define OCTAVE_CONF_COLAMD_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_COLAMD_LIBS
#define OCTAVE_CONF_COLAMD_LIBS "-lcolamd"
#endif

#ifndef OCTAVE_CONF_CPICFLAG
#define OCTAVE_CONF_CPICFLAG ""
#endif

#ifndef OCTAVE_CONF_CPPFLAGS
#define OCTAVE_CONF_CPPFLAGS "-I/c/OctaveB/gplibs/include -I/c/OctaveB/OctaveLibs/include -I/c/OctaveB/GnuWin32/include"
#endif

#ifndef OCTAVE_CONF_CURL_CPPFLAGS
#define OCTAVE_CONF_CURL_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_CURL_LDFLAGS
#define OCTAVE_CONF_CURL_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_CURL_LIBS
#define OCTAVE_CONF_CURL_LIBS "-lcurl"
#endif

#ifndef OCTAVE_CONF_CXSPARSE_CPPFLAGS
#define OCTAVE_CONF_CXSPARSE_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_CXSPARSE_LDFLAGS
#define OCTAVE_CONF_CXSPARSE_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_CXSPARSE_LIBS
#define OCTAVE_CONF_CXSPARSE_LIBS "-lcxsparse"
#endif

#ifndef OCTAVE_CONF_CXXCPP
#define OCTAVE_CONF_CXXCPP "g++ -shared-libgcc -E"
#endif

#ifndef OCTAVE_CONF_CXXFLAGS
#define OCTAVE_CONF_CXXFLAGS "-g -O2"
#endif

#ifndef OCTAVE_CONF_CXXPICFLAG
#define OCTAVE_CONF_CXXPICFLAG ""
#endif

#ifndef OCTAVE_CONF_CXX
#define OCTAVE_CONF_CXX "g++ -shared-libgcc"
#endif

#ifndef OCTAVE_CONF_CXX_VERSION
#define OCTAVE_CONF_CXX_VERSION "4.6.2"
#endif

#ifndef OCTAVE_CONF_DEFAULT_PAGER
#define OCTAVE_CONF_DEFAULT_PAGER "less"
#endif

#ifndef OCTAVE_CONF_DEFS
#define OCTAVE_CONF_DEFS "-DPACKAGE_NAME=\"GNU Octave\" -DPACKAGE_TARNAME=\"octave\" -DPACKAGE_VERSION=\"3.6.4\" -DPACKAGE_STRING=\"GNU Octave 3.6.4\" -DPACKAGE_BUGREPORT=\"http://octave.org/bugs.html\" -DPACKAGE_URL=\"http://www.gnu.org/software/octave/\" -DPACKAGE=\"octave\" -DVERSION=\"3.6.4\" -DOCTAVE_SOURCE=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_DARWIN_C_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DSEPCHAR=';' -DSEPCHAR_STR=\";\" -DOCTAVE_IDX_TYPE=int -D__NO_MATH_INLINES=1 -DCXX_NEW_FRIEND_TEMPLATE_DECL=1 -DCXX_ISO_COMPLIANT_LIBRARY=1 -DHAVE_ALLOCA=1 -DHAVE_GETCWD=1 -DHAVE_BTOWC=1 -DHAVE_ISBLANK=1 -DHAVE_ISWCTYPE=1 -DHAVE_MBSRTOWCS=1 -DHAVE_WMEMCHR=1 -DHAVE_WMEMCPY=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MBSINIT=1 -DHAVE_MBRTOWC=1 -DHAVE_MPROTECT=1 -DHAVE_STRDUP=1 -DHAVE_TZSET=1 -DHAVE_SNPRINTF=1 -DHAVE_ISWCNTRL=1 -DDOUBLE_SLASH_IS_DISTINCT_ROOT=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DIRENT_H=1 -DHAVE_WCTYPE_H=1 -DHAVE_GETOPT_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_MATH_H=1 -DHAVE_WCHAR_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_DECL_STRERROR_R=0 -DHAVE_DECL_FCHDIR=0 -DHAVE_WORKING_O_NOATIME=0 -DHAVE_WORKING_O_NOFOLLOW=0 -DHAVE_DECL_STRMODE=0 -DHAVE_MBSTATE_T=1 -DHAVE_DECL_FSEEKO=0 -DHAVE_DECL_FTELLO=0 -DHAVE_DECL_GETCWD=1 -DHAVE_DECL_GETLOGIN_R=0 -DHAVE_DECL_GETLOGIN=0 -DHAVE_GETOPT_H=1 -DHAVE_GETOPT_LONG_ONLY=1 -D__GETOPT_PREFIX=rpl_ -DHAVE_DECL_GETENV=1 -Drestrict=__restrict -DHAVE_WINSOCK2_H=1 -DHAVE_RAW_DECL_GETTIMEOFDAY=1 -DDBL_EXPBIT0_WORD=1 -DDBL_EXPBIT0_BIT=20 -DFLT_EXPBIT0_WORD=0 -DFLT_EXPBIT0_BIT=23 -DHAVE_DECL_GETC_UNLOCKED=0 -DHAVE_STDLIB_H=1 -DMALLOC_0_IS_NONNULL=1 -DHAVE_UNSIGNED_LONG_LONG_INT=1 -DHAVE_LONG_LONG_INT=1 -DHAVE_DECL_MEMRCHR=0 -DHAVE_WINSOCK2_H=1 -DHAVE_WINSOCK2_H=1 -DWINDOWS_SOCKETS=1 -DPROMOTED_MODE_T=int -DHAVE_SIGSET_T=1 -Duid_t=int -Dgid_t=int -DHAVE_WS2TCPIP_H=1 -DHAVE__BOOL=1 -DHAVE_WCHAR_T=1 -DHAVE_DECL_STRDUP=1 -DHAVE_DECL_TZNAME=1 -DHAVE_TZNAME=1 -DHAVE_RAW_DECL_STRDUP=1 -DHAVE_RAW_DECL_STRNCAT=1 -DHAVE_RAW_DECL_STRPBRK=1 -DHAVE_RAW_DECL_STRCASECMP=1 -DHAVE_RAW_DECL_STRNCASECMP=1 -DHAVE_DECL_LOCALTIME_R=0 -DHAVE_WINT_T=1 -DHAVE_INTTYPES_H_WITH_UINTMAX=1 -DHAVE_STDINT_H_WITH_UINTMAX=1 -DHAVE_INTMAX_T=1 -DHAVE_SNPRINTF=1 -DHAVE_WCSLEN=1 -DHAVE_MBRTOWC=1 -DHAVE_WCRTOMB=1 -DHAVE_DECL__SNPRINTF=1 -DHAVE_SNPRINTF_RETVAL_C99=1 -DGNULIB_CANONICALIZE_LGPL=1 -DGNULIB_TEST_CANONICALIZE_FILE_NAME=1 -DGNULIB_TEST_REALPATH=1 -DGNULIB_TEST_CHDIR=1 -DGNULIB_TEST_CLOEXEC=1 -DHAVE_WINSOCK2_H=1 -DGNULIB_TEST_CLOSE=1 -DHAVE_CLOSEDIR=1 -DGNULIB_TEST_CLOSEDIR=1 -DGNULIB_TEST_COPYSIGN=1 -DGNULIB_TEST_COPYSIGNF=1 -DD_INO_IN_DIRENT=1 -DHAVE_RAW_DECL_CLOSEDIR=1 -DHAVE_RAW_DECL_OPENDIR=1 -DHAVE_RAW_DECL_READDIR=1 -DHAVE_RAW_DECL_REWINDDIR=1 -DHAVE_DECL_DIRFD=0 -DGNULIB_TEST_DIRFD=1 -DDOUBLE_SLASH_IS_DISTINCT_ROOT=1 -DGNULIB_TEST_DUP=1 -DHAVE_DUP2=1 -DGNULIB_TEST_DUP2=1 -DREPLACE_FCHDIR=1 -DREPLACE_OPEN_DIRECTORY=1 -DGNULIB_TEST_FCHDIR=1 -DGNULIB_TEST_FCLOSE=1 -DGNULIB_TEST_FCNTL=1 -DHAVE_DECL_FDOPENDIR=0 -DGNULIB_TEST_FDOPENDIR=1 -DGNULIB_FDOPENDIR=1 -DGNULIB_FFLUSH=1 -DGNULIB_TEST_FFLUSH=1 -DGNULIB_TEST_FLOOR=1 -Dfnmatch=posix_fnmatch -DHAVE_DECL_ISBLANK=1 -DFOPEN_TRAILING_SLASH_BUG=1 -DGNULIB_TEST_FOPEN=1 -DHAVE_DECL_FPURGE=0 -DGNULIB_TEST_FPURGE=1 -DGNULIB_TEST_FSEEK=1 -DGNULIB_TEST_FSEEKO=1 -DGNULIB_TEST_FSTAT=1 -DGNULIB_FSTATAT=1 -DGNULIB_TEST_FSTATAT=1 -DGNULIB_TEST_FTELL=1 -DGNULIB_TEST_FTELLO=1 -DHAVE_MINIMALLY_WORKING_GETCWD=1 -DGNULIB_GETCWD=1 -DGNULIB_TEST_GETCWD=1 -DGNULIB_TEST_GETCWD=1 -DGNULIB_TEST_GETDTABLESIZE=1 -DHAVE_WINSOCK2_H=1 -DHOST_NAME_MAX=256 -DGNULIB_TEST_GETHOSTNAME=1 -DGNULIB_TEST_GETLOGIN_R=1 -DGNULIB_TEST_GETOPT_GNU=1 -D__GETOPT_PREFIX=rpl_ -DGETTIMEOFDAY_TIMEZONE=void -DGNULIB_TEST_GETTIMEOFDAY=1 -DGNULIB_TEST_ISATTY=1 -DHAVE_ISNAND_IN_LIBC=1 -DHAVE_ISNANF_IN_LIBC=1 -DLDBL_EXPBIT0_WORD=2 -DLDBL_EXPBIT0_BIT=0 -DGNULIB_TEST_LINK=1 -DLSEEK_PIPE_BROKEN=1 -DGNULIB_TEST_LSEEK=1 -DGNULIB_TEST_LSTAT=1 -DGNULIB_TEST_MALLOC_POSIX=1 -DHAVE_RAW_DECL_ACOSF=1 -DHAVE_RAW_DECL_ACOSL=1 -DHAVE_RAW_DECL_ASINF=1 -DHAVE_RAW_DECL_ASINL=1 -DHAVE_RAW_DECL_ATANF=1 -DHAVE_RAW_DECL_ATANL=1 -DHAVE_RAW_DECL_CEILF=1 -DHAVE_RAW_DECL_CEILL=1 -DHAVE_RAW_DECL_COPYSIGN=1 -DHAVE_RAW_DECL_COPYSIGNF=1 -DHAVE_RAW_DECL_COPYSIGNL=1 -DHAVE_RAW_DECL_COSF=1 -DHAVE_RAW_DECL_COSL=1 -DHAVE_RAW_DECL_COSHF=1 -DHAVE_RAW_DECL_EXPF=1 -DHAVE_RAW_DECL_EXPL=1 -DHAVE_RAW_DECL_FABSF=1 -DHAVE_RAW_DECL_FLOORF=1 -DHAVE_RAW_DECL_FLOORL=1 -DHAVE_RAW_DECL_FMA=1 -DHAVE_RAW_DECL_FMAF=1 -DHAVE_RAW_DECL_FMAL=1 -DHAVE_RAW_DECL_FMODF=1 -DHAVE_RAW_DECL_FREXPF=1 -DHAVE_RAW_DECL_FREXPL=1 -DHAVE_RAW_DECL_LDEXPF=1 -DHAVE_RAW_DECL_LDEXPL=1 -DHAVE_RAW_DECL_LOGB=1 -DHAVE_RAW_DECL_LOGF=1 -DHAVE_RAW_DECL_LOGL=1 -DHAVE_RAW_DECL_LOG10F=1 -DHAVE_RAW_DECL_MODFF=1 -DHAVE_RAW_DECL_POWF=1 -DHAVE_RAW_DECL_RINT=1 -DHAVE_RAW_DECL_RINTF=1 -DHAVE_RAW_DECL_RINTL=1 -DHAVE_RAW_DECL_ROUND=1 -DHAVE_RAW_DECL_ROUNDF=1 -DHAVE_RAW_DECL_ROUNDL=1 -DHAVE_RAW_DECL_SINF=1 -DHAVE_RAW_DECL_SINL=1 -DHAVE_RAW_DECL_SINHF=1 -DHAVE_RAW_DECL_SQRTF=1 -DHAVE_RAW_DECL_SQRTL=1 -DHAVE_RAW_DECL_TANF=1 -DHAVE_RAW_DECL_TANL=1 -DHAVE_RAW_DECL_TANHF=1 -DHAVE_RAW_DECL_TRUNC=1 -DHAVE_RAW_DECL_TRUNCF=1 -DHAVE_RAW_DECL_TRUNCL=1 -DMBRTOWC_RETVAL_BUG=1 -DGNULIB_TEST_MBRTOWC=1 -DGNULIB_TEST_MBSINIT=1 -DGNULIB_TEST_MBSRTOWCS=1 -DGNULIB_TEST_MEMCHR=1 -DGNULIB_TEST_MEMPCPY=1 -DGNULIB_TEST_MEMRCHR=1 -DFUNC_MKDIR_DOT_BUG=1 -DGNULIB_TEST_MKFIFO=1 -DGNULIB_MKOSTEMP=1 -DGNULIB_TEST_MKOSTEMP=1 -DGNULIB_TEST_MKSTEMP=1 -DGNULIB_TEST_MKTIME=1 -DGNULIB_TEST_NANOSLEEP=1 -DHAVE_SYS_PARAM_H=1 -DGNULIB_TEST_OPEN=1 -DGNULIB_OPENAT=1 -DGNULIB_TEST_OPENAT=1 -DHAVE_OPENDIR=1 -DGNULIB_TEST_OPENDIR=1 -DHAVE_DECL_PROGRAM_INVOCATION_NAME=0 -DHAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME=0 -DHAVE_RAISE=1 -DGNULIB_TEST_RAISE=1 -DHAVE_READDIR=1 -DGNULIB_TEST_READDIR=1 -DGNULIB_TEST_READLINK=1 -DGNULIB_TEST_REALLOC_POSIX=1 -DRENAME_TRAILING_SLASH_DEST_BUG=1 -DRENAME_DEST_EXISTS_BUG=1 -DGNULIB_TEST_RENAME=1 -DHAVE_REWINDDIR=1 -DGNULIB_TEST_REWINDDIR=1 -DGNULIB_TEST_RMDIR=1 -DHAVE_DECL_ROUND=1 -DGNULIB_TEST_ROUND=1 -DHAVE_DECL_ROUNDF=1 -DGNULIB_TEST_ROUNDF=1 -DGNULIB_TEST_SELECT=1 -DGNULIB_TEST_SIGACTION=1 -DGNULIB_TEST_SIGNBIT=1 -DGNULIB_TEST_SIGPROCMASK=1 -DHAVE_STDINT_H=1 -DHAVE_DECL_SLEEP=0 -DGNULIB_TEST_SLEEP=1 -DHAVE_WINSOCK2_H=1 -DWINDOWS_SOCKETS=1 -DREPLACE_FUNC_STAT_DIR=1 -DGNULIB_TEST_STAT=1 -DHAVE_RAW_DECL_GETS=1 -DHAVE_RAW_DECL_PCLOSE=1 -DHAVE_RAW_DECL_POPEN=1 -DHAVE_RAW_DECL_SNPRINTF=1 -DHAVE_RAW_DECL_TMPFILE=1 -DHAVE_RAW_DECL_VSNPRINTF=1 -DHAVE_RAW_DECL__EXIT=1 -DHAVE_RAW_DECL_ATOLL=1 -DHAVE_RAW_DECL_STRTOD=1 -DHAVE_RAW_DECL_STRTOLL=1 -DHAVE_RAW_DECL_STRTOULL=1 -DHAVE_STRCASECMP=1 -DHAVE_STRNCASECMP=1 -DHAVE_DECL_STRNCASECMP=1 -DGNULIB_TEST_STRDUP=1 -DGNULIB_STRERROR=1 -DGNULIB_TEST_STRERROR=1 -DHAVE_WINSOCK2_H=1 -Dmy_strftime=nstrftime -DGNULIB_TEST_STRPTIME=1 -DGNULIB_TEST_SYMLINK=1 -DHAVE_WINSOCK2_H=1 -DHAVE_STRUCT_SOCKADDR_STORAGE=1 -DHAVE_STRUCT_SOCKADDR_STORAGE_SS_FAMILY=1 -DHAVE_WINSOCK2_H=1 -Dnlink_t=int -DHAVE_RAW_DECL_FSTAT=1 -DHAVE_RAW_DECL_STAT=1 -DGNULIB_TEST_TIME_R=1 -DGNULIB_TEST_TMPFILE=1 -DHAVE_DECL_TRUNC=1 -DGNULIB_TEST_TRUNC=1 -DHAVE_DECL_TRUNCF=1 -DGNULIB_TEST_TRUNCF=1 -DHAVE_RAW_DECL_CHDIR=1 -DHAVE_RAW_DECL_DUP=1 -DHAVE_RAW_DECL_DUP2=1 -DHAVE_RAW_DECL_FTRUNCATE=1 -DHAVE_RAW_DECL_GETCWD=1 -DHAVE_RAW_DECL_ISATTY=1 -DHAVE_RAW_DECL_LSEEK=1 -DHAVE_RAW_DECL_RMDIR=1 -DHAVE_RAW_DECL_UNLINK=1 -DHAVE_RAW_DECL_USLEEP=1 -DGNULIB_TEST_UNLINK=1 -DGNULIB_TEST_VASPRINTF=1 -DHAVE_RAW_DECL_BTOWC=1 -DHAVE_RAW_DECL_WCTOB=1 -DHAVE_RAW_DECL_MBSINIT=1 -DHAVE_RAW_DECL_MBRTOWC=1 -DHAVE_RAW_DECL_MBRLEN=1 -DHAVE_RAW_DECL_MBSRTOWCS=1 -DHAVE_RAW_DECL_WCRTOMB=1 -DHAVE_RAW_DECL_WCSRTOMBS=1 -DHAVE_RAW_DECL_WMEMCHR=1 -DHAVE_RAW_DECL_WMEMCMP=1 -DHAVE_RAW_DECL_WMEMCPY=1 -DHAVE_RAW_DECL_WMEMMOVE=1 -DHAVE_RAW_DECL_WMEMSET=1 -DHAVE_RAW_DECL_WCSLEN=1 -DHAVE_RAW_DECL_WCSCPY=1 -DHAVE_RAW_DECL_WCSNCPY=1 -DHAVE_RAW_DECL_WCSCAT=1 -DHAVE_RAW_DECL_WCSNCAT=1 -DHAVE_RAW_DECL_WCSCMP=1 -DHAVE_RAW_DECL_WCSNCMP=1 -DHAVE_RAW_DECL_WCSCOLL=1 -DHAVE_RAW_DECL_WCSXFRM=1 -DHAVE_RAW_DECL_WCSDUP=1 -DHAVE_RAW_DECL_WCSCHR=1 -DHAVE_RAW_DECL_WCSRCHR=1 -DHAVE_RAW_DECL_WCSCSPN=1 -DHAVE_RAW_DECL_WCSSPN=1 -DHAVE_RAW_DECL_WCSPBRK=1 -DHAVE_RAW_DECL_WCSSTR=1 -DHAVE_RAW_DECL_WCSTOK=1 -DHAVE_TOWLOWER=1 -DHAVE_RAW_DECL_WCTYPE=1 -DHAVE_RAW_DECL_ISWCTYPE=1 -DHAVE_RAW_DECL_WCTRANS=1 -DHAVE_RAW_DECL_TOWCTRANS=1 -DHAVE_STDINT_H=1 -DHAVE_PTHREAD=1 -DFLOAT_TRUNCATE=volatile -DHAVE_LIBM=1 -DF77_FUNC(name,NAME)=name ## _ -DF77_FUNC_(name,NAME)=name ## _ -DHAVE_IEEE754_DATA_FORMAT=1 -DHAVE_CXX_COMPLEX_SETTERS=1 -DHAVE_CXX_COMPLEX_REFERENCE_ACCESSORS=1 -DHAVE_LIBQHULL_LIBQHULL_H=1 -DHAVE_QHULL=1 -DHAVE_PCRE_H=1 -DHAVE_PCRE_COMPILE=1 -DHAVE_ZLIB_H=1 -DHAVE_Z=1 -DHAVE_HDF5_H=1 -DHAVE_HDF5=1 -DHAVE_FFTW3_H=1 -DHAVE_FFTW3=1 -DHAVE_FFTW3_H=1 -DHAVE_FFTW3F=1 -DHAVE_GLPK_H=1 -DHAVE_GLPK=1 -DHAVE_CURL_CURL_H=1 -DHAVE_CURL=1 -DHAVE_MAGICK=1 -DHAVE_WINDOWS_H=1 -DHAVE_GL_GL_H=1 -DHAVE_GL_GLU_H=1 -DHAVE_OPENGL=1 -DHAVE_FREETYPE=1 -DHAVE_FONTCONFIG=1 -DHAVE_FLTK=1 -DLT_OBJDIR=\".libs/\" -DHAVE_QRUPDATE=1 -DHAVE_QRUPDATE_LUU=1 -DHAVE_SUITESPARSE_AMD_H=1 -DHAVE_AMD=1 -DHAVE_SUITESPARSE_CAMD_H=1 -DHAVE_CAMD=1 -DHAVE_SUITESPARSE_COLAMD_H=1 -DHAVE_COLAMD=1 -DHAVE_SUITESPARSE_CCOLAMD_H=1 -DHAVE_CCOLAMD=1 -DHAVE_SUITESPARSE_CHOLMOD_H=1 -DHAVE_CHOLMOD=1 -DHAVE_SUITESPARSE_CS_H=1 -DHAVE_CXSPARSE=1 -DHAVE_SUITESPARSE_UMFPACK_H=1 -DHAVE_UMFPACK=1 -DUMFPACK_SEPARATE_SPLIT=1 -DHAVE_ARPACK=1 -Duid_t=int -Dgid_t=int -DHAVE_DEV_T=1 -DHAVE_INO_T=1 -DHAVE_LONG_LONG_INT=1 -DHAVE_UNSIGNED_LONG_LONG_INT=1 -DSIZEOF_SHORT=2 -DSIZEOF_INT=4 -DSIZEOF_LONG=4 -DSIZEOF_LONG_LONG=8 -DHAVE_ALLOCA=1 -DHAVE_PLACEMENT_DELETE=1 -DHAVE_DYNAMIC_AUTO_ARRAYS=1 -DHAVE_FAST_INT_OPS=1 -DSIZEOF_LONG_DOUBLE=12 -DHAVE_DIRENT_H=1 -DHAVE_CURSES_H=1 -DHAVE_DIRECT_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_LOCALE_H=1 -DHAVE_MEMORY_H=1 -DHAVE_NCURSES_H=1 -DHAVE_PTHREAD_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_TERMCAP_H=1 -DHAVE_SSTREAM=1 -DHAVE_TR1_UNORDERED_MAP=1 -DUSE_UNORDERED_MAP_WITH_TR1=1 -DHAVE_CONIO_H=1 -DHAVE_BASENAME=1 -DHAVE_CHMOD=1 -DHAVE_DUP2=1 -DHAVE_EXECVP=1 -DHAVE_EXPM1=1 -DHAVE_EXPM1F=1 -DHAVE_GETPID=1 -DHAVE__KBHIT=1 -DHAVE_LGAMMA=1 -DHAVE_LGAMMAF=1 -DHAVE_LOG1P=1 -DHAVE_LOG1PF=1 -DHAVE_PUTENV=1 -DHAVE_ROUNDL=1 -DHAVE_SETLOCALE=1 -DHAVE_SETVBUF=1 -DHAVE_TEMPNAM=1 -DHAVE_TGAMMAF=1 -DHAVE_UMASK=1 -DHAVE_UTIME=1 -DHAVE__CHMOD=1 -DHAVE_DECL_EXP2=1 -DHAVE_DECL_ROUND=1 -DHAVE_DECL_TGAMMA=1 -DHAVE_EXP2=1 -DHAVE_ROUND=1 -DHAVE_TGAMMA=1 -DHAVE_MKSTEMPS=1 -D_WIN32_WINNT=0x0403 -DHAVE_LOADLIBRARY_API=1 -DENABLE_DYNAMIC_LINKING=1 -DHAVE_CMATH_ISNAN=1 -DHAVE_CMATH_ISNANF=1 -DHAVE_CMATH_ISINF=1 -DHAVE_CMATH_ISINFF=1 -DHAVE_CMATH_ISFINITE=1 -DHAVE_CMATH_ISFINITEF=1 -DHAVE_FINITE=1 -DHAVE_ISNAN=1 -DHAVE_SIGNBIT=1 -DHAVE__FINITE=1 -DHAVE__ISNAN=1 -DHAVE_DECL_SIGNBIT=1 -DHAVE_ACOSH=1 -DHAVE_ACOSHF=1 -DHAVE_ASINH=1 -DHAVE_ASINHF=1 -DHAVE_ATANH=1 -DHAVE_ATANHF=1 -DHAVE_ERF=1 -DHAVE_ERFF=1 -DHAVE_ERFC=1 -DHAVE_ERFCF=1 -DHAVE_EXP2F=1 -DHAVE_LOG2=1 -DHAVE_LOG2F=1 -DHAVE_HYPOTF=1 -DHAVE_CBRT=1 -DHAVE_CBRTF=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DHAVE_DECL_TZNAME=1 -DHAVE_TZNAME=1 -DUSE_READLINE=1 -DHAVE_DECL_SYS_SIGLIST=0"
#endif

#ifndef OCTAVE_CONF_DL_LD
#define OCTAVE_CONF_DL_LD "g++ -shared-libgcc"
#endif

#ifndef OCTAVE_CONF_DL_LDFLAGS
#define OCTAVE_CONF_DL_LDFLAGS "-shared -Wl,--export-all-symbols -Wl,--enable-auto-import -Wl,--enable-runtime-pseudo-reloc"
#endif

#ifndef OCTAVE_CONF_DL_LIBS
#define OCTAVE_CONF_DL_LIBS ""
#endif

#ifndef OCTAVE_CONF_EXEEXT
#define OCTAVE_CONF_EXEEXT ".exe"
#endif

#ifndef OCTAVE_CONF_F77
#define OCTAVE_CONF_F77 "gfortran -shared-libgcc"
#endif

#ifndef OCTAVE_CONF_F77_FLOAT_STORE_FLAG
#define OCTAVE_CONF_F77_FLOAT_STORE_FLAG "-ffloat-store"
#endif

#ifndef OCTAVE_CONF_F77_INTEGER_8_FLAG
#define OCTAVE_CONF_F77_INTEGER_8_FLAG ""
#endif

#ifndef OCTAVE_CONF_FC
#define OCTAVE_CONF_FC "gfortran -shared-libgcc"
#endif

#ifndef OCTAVE_CONF_FFLAGS
#define OCTAVE_CONF_FFLAGS "-O -mieee-fp"
#endif

#ifndef OCTAVE_CONF_FFTW3_CPPFLAGSS
#define OCTAVE_CONF_FFTW3_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_FFTW3_LDFLAGSS
#define OCTAVE_CONF_FFTW3_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_FFTW3_LIBS
#define OCTAVE_CONF_FFTW3_LIBS "-lfftw3"
#endif

#ifndef OCTAVE_CONF_FFTW3F_CPPFLAGSS
#define OCTAVE_CONF_FFTW3F_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_FFTW3F_LDFLAGSS
#define OCTAVE_CONF_FFTW3F_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_FFTW3F_LIBS
#define OCTAVE_CONF_FFTW3F_LIBS "-lfftw3f"
#endif

#ifndef OCTAVE_CONF_FLIBS
#define OCTAVE_CONF_FLIBS "-Lc:/OctaveB/gplibs/lib -Lc:/OctaveB/OctaveLibs/lib -Lc:/OctaveB/GnuWin32/lib -Lc:/octaveb/mingw/bin/../lib/gcc/mingw32/4.6.2 -Lc:/octaveb/mingw/bin/../lib/gcc -Lc:/octaveb/mingw/bin/../lib/gcc/mingw32/4.6.2/../../../../mingw32/lib -Lc:/octaveb/mingw/bin/../lib/gcc/mingw32/4.6.2/../../.. -lm -lpthread -lgfortran -llapack -lmingw32 -lmoldname -lmingwex -lmsvcrt -lquadmath -ladvapi32 -lshell32 -luser32 -lkernel32"
#endif

#ifndef OCTAVE_CONF_FPICFLAG
#define OCTAVE_CONF_FPICFLAG ""
#endif

#ifndef OCTAVE_CONF_FT2_LIBS
#define OCTAVE_CONF_FT2_LIBS "-LC:/OctaveB/gplibs/lib -lfreetype  "
#endif

#ifndef OCTAVE_CONF_GLPK_CPPFLAGS
#define OCTAVE_CONF_GLPK_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_GLPK_LDFLAGS
#define OCTAVE_CONF_GLPK_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_GLPK_LIBS
#define OCTAVE_CONF_GLPK_LIBS "-lglpk"
#endif

#ifndef OCTAVE_CONF_GNUPLOT
#define OCTAVE_CONF_GNUPLOT "gnuplot"
#endif

#ifndef OCTAVE_CONF_GRAPHICS_LIBS
#define OCTAVE_CONF_GRAPHICS_LIBS "-L/c/OctaveB/OctaveLibs/lib  -L/c/OctaveB/gplibs/lib -Wl,--allow-multiple-definition -Wl,--enable-auto-import -Wl,--enable-runtime-pseudo-reloc-v2 -Wl,--stack,10485760 -Wl,--enable-auto-import -Wl,--enable-runtime-pseudo-reloc -lfltk_gl -lglu32 -lopengl32 -lfltk -lole32 -luuid -lcomctl32"
#endif

#ifndef OCTAVE_CONF_HDF5_CPPFLAGS
#define OCTAVE_CONF_HDF5_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_HDF5_LDFLAGS
#define OCTAVE_CONF_HDF5_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_HDF5_LIBS
#define OCTAVE_CONF_HDF5_LIBS "-lhdf5"
#endif

#ifndef OCTAVE_CONF_INCFLAGS
#define OCTAVE_CONF_INCFLAGS ""
#endif

#ifndef OCTAVE_CONF_INCLUDEDIR
#define OCTAVE_CONF_INCLUDEDIR "/c/OctaveB/octave-3.6.4/include"
#endif

#ifndef OCTAVE_CONF_LAPACK_LIBS
#define OCTAVE_CONF_LAPACK_LIBS "-llapack"
#endif

#ifndef OCTAVE_CONF_LDFLAGS
#define OCTAVE_CONF_LDFLAGS "-L/c/OctaveB/gplibs/lib -L/c/OctaveB/OctaveLibs/lib -L/c/OctaveB/GnuWin32/lib -Wl,--allow-multiple-definition -Wl,--enable-auto-import -Wl,--enable-runtime-pseudo-reloc-v2"
#endif

#ifndef OCTAVE_CONF_LD_CXX
#define OCTAVE_CONF_LD_CXX "g++ -shared-libgcc"
#endif

#ifndef OCTAVE_CONF_LD_STATIC_FLAG
#define OCTAVE_CONF_LD_STATIC_FLAG ""
#endif

#ifndef OCTAVE_CONF_LEXLIB
#define OCTAVE_CONF_LEXLIB ""
#endif

#ifndef OCTAVE_CONF_LEX
#define OCTAVE_CONF_LEX "flex"
#endif

#ifndef OCTAVE_CONF_LFLAGS
#define OCTAVE_CONF_LFLAGS "-I"
#endif

#ifndef OCTAVE_CONF_LIBCRUFT
#define OCTAVE_CONF_LIBCRUFT "-lcruft"
#endif

#ifndef OCTAVE_CONF_LIBEXT
#define OCTAVE_CONF_LIBEXT "a"
#endif

#ifndef OCTAVE_CONF_LIBFLAGS
#define OCTAVE_CONF_LIBFLAGS "-L.."
#endif

#ifndef OCTAVE_CONF_LIBOCTAVE
#define OCTAVE_CONF_LIBOCTAVE "-loctave"
#endif

#ifndef OCTAVE_CONF_LIBOCTINTERP
#define OCTAVE_CONF_LIBOCTINTERP "-loctinterp"
#endif

#ifndef OCTAVE_CONF_LIBPLPLOT
#define OCTAVE_CONF_LIBPLPLOT %OCTAVE_CONF_LIBPLPLOT%
#endif

#ifndef OCTAVE_CONF_LIBS
#define OCTAVE_CONF_LIBS "-liberty -lm -lpthread -lgfortran -llapack -lgdi32 -lws2_32 -luser32 -lkernel32 -lgdi32 -lws2_32 -luser32 -lkernel32"
#endif

#ifndef OCTAVE_CONF_LN_S
#define OCTAVE_CONF_LN_S "cp -pR"
#endif

#ifndef OCTAVE_CONF_MAGICK_CPPFLAGS
#define OCTAVE_CONF_MAGICK_CPPFLAGS "-IC:/OctaveB/OctaveLibs/include/GraphicsMagick  "
#endif

#ifndef OCTAVE_CONF_MAGICK_LDFLAGS
#define OCTAVE_CONF_MAGICK_LDFLAGS "-LC:/OctaveB/OctaveLibs/lib  "
#endif

#ifndef OCTAVE_CONF_MAGICK_LIBS
#define OCTAVE_CONF_MAGICK_LIBS "-lGraphicsMagick++ -lGraphicsMagick  "
#endif

#ifndef OCTAVE_CONF_MKOCTFILE_DL_LDFLAGS
#define OCTAVE_CONF_MKOCTFILE_DL_LDFLAGS "-shared -Wl,--export-all-symbols -Wl,--enable-auto-import -Wl,--enable-runtime-pseudo-reloc"
#endif

#ifndef OCTAVE_CONF_OCTAVE_LINK_DEPS
#define OCTAVE_CONF_OCTAVE_LINK_DEPS ""
#endif

#ifndef OCTAVE_CONF_OCTAVE_LINK_OPTS
#define OCTAVE_CONF_OCTAVE_LINK_OPTS ""
#endif

#ifndef OCTAVE_CONF_OCTINCLUDEDIR
#define OCTAVE_CONF_OCTINCLUDEDIR "/c/OctaveB/octave-3.6.4/include/octave-3.6.4/octave"
#endif

#ifndef OCTAVE_CONF_OCTLIBDIR
#define OCTAVE_CONF_OCTLIBDIR "/c/OctaveB/octave-3.6.4/lib/octave/3.6.4"
#endif

#ifndef OCTAVE_CONF_OCT_LINK_DEPS
#define OCTAVE_CONF_OCT_LINK_DEPS ""
#endif

#ifndef OCTAVE_CONF_OCT_LINK_OPTS
#define OCTAVE_CONF_OCT_LINK_OPTS "-L/c/OctaveB/gplibs/lib -L/c/OctaveB/OctaveLibs/lib -L/c/OctaveB/GnuWin32/lib -Wl,--allow-multiple-definition -Wl,--enable-auto-import -Wl,--enable-runtime-pseudo-reloc-v2 "
#endif

#ifndef OCTAVE_CONF_OPENGL_LIBS
#define OCTAVE_CONF_OPENGL_LIBS "-LC:/OctaveB/gplibs/lib -lfontconfig   -lopengl32 -lglu32"
#endif

#ifndef OCTAVE_CONF_PREFIX
#define OCTAVE_CONF_PREFIX "/c/OctaveB/octave-3.6.4"
#endif

#ifndef OCTAVE_CONF_PTHREAD_CFLAGS
#define OCTAVE_CONF_PTHREAD_CFLAGS ""
#endif

#ifndef OCTAVE_CONF_PTHREAD_LIBS
#define OCTAVE_CONF_PTHREAD_LIBS "-lpthread"
#endif

#ifndef OCTAVE_CONF_QHULL_CPPFLAGS
#define OCTAVE_CONF_QHULL_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_QHULL_LDFLAGS
#define OCTAVE_CONF_QHULL_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_QHULL_LIBS
#define OCTAVE_CONF_QHULL_LIBS "-lqhull"
#endif

#ifndef OCTAVE_CONF_QRUPDATE_CPPFLAGS
#define OCTAVE_CONF_QRUPDATE_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_QRUPDATE_LDFLAGS
#define OCTAVE_CONF_QRUPDATE_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_QRUPDATE_LIBS
#define OCTAVE_CONF_QRUPDATE_LIBS "-lqrupdate"
#endif

#ifndef OCTAVE_CONF_RANLIB
#define OCTAVE_CONF_RANLIB "ranlib"
#endif

#ifndef OCTAVE_CONF_RDYNAMIC_FLAG
#define OCTAVE_CONF_RDYNAMIC_FLAG ""
#endif

#ifndef OCTAVE_CONF_READLINE_LIBS
#define OCTAVE_CONF_READLINE_LIBS "-lreadline"
#endif

#ifndef OCTAVE_CONF_REGEX_LIBS
#define OCTAVE_CONF_REGEX_LIBS "-lpcre"
#endif

#ifndef OCTAVE_CONF_SED
#define OCTAVE_CONF_SED "/bin/sed"
#endif

#ifndef OCTAVE_CONF_SHARED_LIBS
#define OCTAVE_CONF_SHARED_LIBS ""
#endif

#ifndef OCTAVE_CONF_SHLEXT
#define OCTAVE_CONF_SHLEXT "dll"
#endif

#ifndef OCTAVE_CONF_SHLEXT_VER
#define OCTAVE_CONF_SHLEXT_VER "dll.3.6.4"
#endif

#ifndef OCTAVE_CONF_SH_LD
#define OCTAVE_CONF_SH_LD "g++ -shared-libgcc"
#endif

#ifndef OCTAVE_CONF_SH_LDFLAGS
#define OCTAVE_CONF_SH_LDFLAGS "-shared -Wl,--export-all-symbols -Wl,--enable-auto-import -Wl,--enable-auto-image-base"
#endif

#ifndef OCTAVE_CONF_SONAME_FLAGS
#define OCTAVE_CONF_SONAME_FLAGS "-Wl,--out-implib=oct-conf.h.a"
#endif

#ifndef OCTAVE_CONF_STATIC_LIBS
#define OCTAVE_CONF_STATIC_LIBS ""
#endif

#ifndef OCTAVE_CONF_TERM_LIBS
#define OCTAVE_CONF_TERM_LIBS "-lncurses"
#endif

#ifndef OCTAVE_CONF_UGLY_DEFS
#define OCTAVE_CONF_UGLY_DEFS "-DPACKAGE_NAME=\"GNU Octave\" -DPACKAGE_TARNAME=\"octave\" -DPACKAGE_VERSION=\"3.6.4\" -DPACKAGE_STRING=\"GNU Octave 3.6.4\" -DPACKAGE_BUGREPORT=\"http://octave.org/bugs.html\" -DPACKAGE_URL=\"http://www.gnu.org/software/octave/\" -DPACKAGE=\"octave\" -DVERSION=\"3.6.4\" -DOCTAVE_SOURCE=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_DARWIN_C_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DSEPCHAR=';' -DSEPCHAR_STR=\";\" -DOCTAVE_IDX_TYPE=int -D__NO_MATH_INLINES=1 -DCXX_NEW_FRIEND_TEMPLATE_DECL=1 -DCXX_ISO_COMPLIANT_LIBRARY=1 -DHAVE_ALLOCA=1 -DHAVE_GETCWD=1 -DHAVE_BTOWC=1 -DHAVE_ISBLANK=1 -DHAVE_ISWCTYPE=1 -DHAVE_MBSRTOWCS=1 -DHAVE_WMEMCHR=1 -DHAVE_WMEMCPY=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MBSINIT=1 -DHAVE_MBRTOWC=1 -DHAVE_MPROTECT=1 -DHAVE_STRDUP=1 -DHAVE_TZSET=1 -DHAVE_SNPRINTF=1 -DHAVE_ISWCNTRL=1 -DDOUBLE_SLASH_IS_DISTINCT_ROOT=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DIRENT_H=1 -DHAVE_WCTYPE_H=1 -DHAVE_GETOPT_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_MATH_H=1 -DHAVE_WCHAR_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_DECL_STRERROR_R=0 -DHAVE_DECL_FCHDIR=0 -DHAVE_WORKING_O_NOATIME=0 -DHAVE_WORKING_O_NOFOLLOW=0 -DHAVE_DECL_STRMODE=0 -DHAVE_MBSTATE_T=1 -DHAVE_DECL_FSEEKO=0 -DHAVE_DECL_FTELLO=0 -DHAVE_DECL_GETCWD=1 -DHAVE_DECL_GETLOGIN_R=0 -DHAVE_DECL_GETLOGIN=0 -DHAVE_GETOPT_H=1 -DHAVE_GETOPT_LONG_ONLY=1 -D__GETOPT_PREFIX=rpl_ -DHAVE_DECL_GETENV=1 -Drestrict=__restrict -DHAVE_WINSOCK2_H=1 -DHAVE_RAW_DECL_GETTIMEOFDAY=1 -DDBL_EXPBIT0_WORD=1 -DDBL_EXPBIT0_BIT=20 -DFLT_EXPBIT0_WORD=0 -DFLT_EXPBIT0_BIT=23 -DHAVE_DECL_GETC_UNLOCKED=0 -DHAVE_STDLIB_H=1 -DMALLOC_0_IS_NONNULL=1 -DHAVE_UNSIGNED_LONG_LONG_INT=1 -DHAVE_LONG_LONG_INT=1 -DHAVE_DECL_MEMRCHR=0 -DHAVE_WINSOCK2_H=1 -DHAVE_WINSOCK2_H=1 -DWINDOWS_SOCKETS=1 -DPROMOTED_MODE_T=int -DHAVE_SIGSET_T=1 -Duid_t=int -Dgid_t=int -DHAVE_WS2TCPIP_H=1 -DHAVE__BOOL=1 -DHAVE_WCHAR_T=1 -DHAVE_DECL_STRDUP=1 -DHAVE_DECL_TZNAME=1 -DHAVE_TZNAME=1 -DHAVE_RAW_DECL_STRDUP=1 -DHAVE_RAW_DECL_STRNCAT=1 -DHAVE_RAW_DECL_STRPBRK=1 -DHAVE_RAW_DECL_STRCASECMP=1 -DHAVE_RAW_DECL_STRNCASECMP=1 -DHAVE_DECL_LOCALTIME_R=0 -DHAVE_WINT_T=1 -DHAVE_INTTYPES_H_WITH_UINTMAX=1 -DHAVE_STDINT_H_WITH_UINTMAX=1 -DHAVE_INTMAX_T=1 -DHAVE_SNPRINTF=1 -DHAVE_WCSLEN=1 -DHAVE_MBRTOWC=1 -DHAVE_WCRTOMB=1 -DHAVE_DECL__SNPRINTF=1 -DHAVE_SNPRINTF_RETVAL_C99=1 -DGNULIB_CANONICALIZE_LGPL=1 -DGNULIB_TEST_CANONICALIZE_FILE_NAME=1 -DGNULIB_TEST_REALPATH=1 -DGNULIB_TEST_CHDIR=1 -DGNULIB_TEST_CLOEXEC=1 -DHAVE_WINSOCK2_H=1 -DGNULIB_TEST_CLOSE=1 -DHAVE_CLOSEDIR=1 -DGNULIB_TEST_CLOSEDIR=1 -DGNULIB_TEST_COPYSIGN=1 -DGNULIB_TEST_COPYSIGNF=1 -DD_INO_IN_DIRENT=1 -DHAVE_RAW_DECL_CLOSEDIR=1 -DHAVE_RAW_DECL_OPENDIR=1 -DHAVE_RAW_DECL_READDIR=1 -DHAVE_RAW_DECL_REWINDDIR=1 -DHAVE_DECL_DIRFD=0 -DGNULIB_TEST_DIRFD=1 -DDOUBLE_SLASH_IS_DISTINCT_ROOT=1 -DGNULIB_TEST_DUP=1 -DHAVE_DUP2=1 -DGNULIB_TEST_DUP2=1 -DREPLACE_FCHDIR=1 -DREPLACE_OPEN_DIRECTORY=1 -DGNULIB_TEST_FCHDIR=1 -DGNULIB_TEST_FCLOSE=1 -DGNULIB_TEST_FCNTL=1 -DHAVE_DECL_FDOPENDIR=0 -DGNULIB_TEST_FDOPENDIR=1 -DGNULIB_FDOPENDIR=1 -DGNULIB_FFLUSH=1 -DGNULIB_TEST_FFLUSH=1 -DGNULIB_TEST_FLOOR=1 -Dfnmatch=posix_fnmatch -DHAVE_DECL_ISBLANK=1 -DFOPEN_TRAILING_SLASH_BUG=1 -DGNULIB_TEST_FOPEN=1 -DHAVE_DECL_FPURGE=0 -DGNULIB_TEST_FPURGE=1 -DGNULIB_TEST_FSEEK=1 -DGNULIB_TEST_FSEEKO=1 -DGNULIB_TEST_FSTAT=1 -DGNULIB_FSTATAT=1 -DGNULIB_TEST_FSTATAT=1 -DGNULIB_TEST_FTELL=1 -DGNULIB_TEST_FTELLO=1 -DHAVE_MINIMALLY_WORKING_GETCWD=1 -DGNULIB_GETCWD=1 -DGNULIB_TEST_GETCWD=1 -DGNULIB_TEST_GETCWD=1 -DGNULIB_TEST_GETDTABLESIZE=1 -DHAVE_WINSOCK2_H=1 -DHOST_NAME_MAX=256 -DGNULIB_TEST_GETHOSTNAME=1 -DGNULIB_TEST_GETLOGIN_R=1 -DGNULIB_TEST_GETOPT_GNU=1 -D__GETOPT_PREFIX=rpl_ -DGETTIMEOFDAY_TIMEZONE=void -DGNULIB_TEST_GETTIMEOFDAY=1 -DGNULIB_TEST_ISATTY=1 -DHAVE_ISNAND_IN_LIBC=1 -DHAVE_ISNANF_IN_LIBC=1 -DLDBL_EXPBIT0_WORD=2 -DLDBL_EXPBIT0_BIT=0 -DGNULIB_TEST_LINK=1 -DLSEEK_PIPE_BROKEN=1 -DGNULIB_TEST_LSEEK=1 -DGNULIB_TEST_LSTAT=1 -DGNULIB_TEST_MALLOC_POSIX=1 -DHAVE_RAW_DECL_ACOSF=1 -DHAVE_RAW_DECL_ACOSL=1 -DHAVE_RAW_DECL_ASINF=1 -DHAVE_RAW_DECL_ASINL=1 -DHAVE_RAW_DECL_ATANF=1 -DHAVE_RAW_DECL_ATANL=1 -DHAVE_RAW_DECL_CEILF=1 -DHAVE_RAW_DECL_CEILL=1 -DHAVE_RAW_DECL_COPYSIGN=1 -DHAVE_RAW_DECL_COPYSIGNF=1 -DHAVE_RAW_DECL_COPYSIGNL=1 -DHAVE_RAW_DECL_COSF=1 -DHAVE_RAW_DECL_COSL=1 -DHAVE_RAW_DECL_COSHF=1 -DHAVE_RAW_DECL_EXPF=1 -DHAVE_RAW_DECL_EXPL=1 -DHAVE_RAW_DECL_FABSF=1 -DHAVE_RAW_DECL_FLOORF=1 -DHAVE_RAW_DECL_FLOORL=1 -DHAVE_RAW_DECL_FMA=1 -DHAVE_RAW_DECL_FMAF=1 -DHAVE_RAW_DECL_FMAL=1 -DHAVE_RAW_DECL_FMODF=1 -DHAVE_RAW_DECL_FREXPF=1 -DHAVE_RAW_DECL_FREXPL=1 -DHAVE_RAW_DECL_LDEXPF=1 -DHAVE_RAW_DECL_LDEXPL=1 -DHAVE_RAW_DECL_LOGB=1 -DHAVE_RAW_DECL_LOGF=1 -DHAVE_RAW_DECL_LOGL=1 -DHAVE_RAW_DECL_LOG10F=1 -DHAVE_RAW_DECL_MODFF=1 -DHAVE_RAW_DECL_POWF=1 -DHAVE_RAW_DECL_RINT=1 -DHAVE_RAW_DECL_RINTF=1 -DHAVE_RAW_DECL_RINTL=1 -DHAVE_RAW_DECL_ROUND=1 -DHAVE_RAW_DECL_ROUNDF=1 -DHAVE_RAW_DECL_ROUNDL=1 -DHAVE_RAW_DECL_SINF=1 -DHAVE_RAW_DECL_SINL=1 -DHAVE_RAW_DECL_SINHF=1 -DHAVE_RAW_DECL_SQRTF=1 -DHAVE_RAW_DECL_SQRTL=1 -DHAVE_RAW_DECL_TANF=1 -DHAVE_RAW_DECL_TANL=1 -DHAVE_RAW_DECL_TANHF=1 -DHAVE_RAW_DECL_TRUNC=1 -DHAVE_RAW_DECL_TRUNCF=1 -DHAVE_RAW_DECL_TRUNCL=1 -DMBRTOWC_RETVAL_BUG=1 -DGNULIB_TEST_MBRTOWC=1 -DGNULIB_TEST_MBSINIT=1 -DGNULIB_TEST_MBSRTOWCS=1 -DGNULIB_TEST_MEMCHR=1 -DGNULIB_TEST_MEMPCPY=1 -DGNULIB_TEST_MEMRCHR=1 -DFUNC_MKDIR_DOT_BUG=1 -DGNULIB_TEST_MKFIFO=1 -DGNULIB_MKOSTEMP=1 -DGNULIB_TEST_MKOSTEMP=1 -DGNULIB_TEST_MKSTEMP=1 -DGNULIB_TEST_MKTIME=1 -DGNULIB_TEST_NANOSLEEP=1 -DHAVE_SYS_PARAM_H=1 -DGNULIB_TEST_OPEN=1 -DGNULIB_OPENAT=1 -DGNULIB_TEST_OPENAT=1 -DHAVE_OPENDIR=1 -DGNULIB_TEST_OPENDIR=1 -DHAVE_DECL_PROGRAM_INVOCATION_NAME=0 -DHAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME=0 -DHAVE_RAISE=1 -DGNULIB_TEST_RAISE=1 -DHAVE_READDIR=1 -DGNULIB_TEST_READDIR=1 -DGNULIB_TEST_READLINK=1 -DGNULIB_TEST_REALLOC_POSIX=1 -DRENAME_TRAILING_SLASH_DEST_BUG=1 -DRENAME_DEST_EXISTS_BUG=1 -DGNULIB_TEST_RENAME=1 -DHAVE_REWINDDIR=1 -DGNULIB_TEST_REWINDDIR=1 -DGNULIB_TEST_RMDIR=1 -DHAVE_DECL_ROUND=1 -DGNULIB_TEST_ROUND=1 -DHAVE_DECL_ROUNDF=1 -DGNULIB_TEST_ROUNDF=1 -DGNULIB_TEST_SELECT=1 -DGNULIB_TEST_SIGACTION=1 -DGNULIB_TEST_SIGNBIT=1 -DGNULIB_TEST_SIGPROCMASK=1 -DHAVE_STDINT_H=1 -DHAVE_DECL_SLEEP=0 -DGNULIB_TEST_SLEEP=1 -DHAVE_WINSOCK2_H=1 -DWINDOWS_SOCKETS=1 -DREPLACE_FUNC_STAT_DIR=1 -DGNULIB_TEST_STAT=1 -DHAVE_RAW_DECL_GETS=1 -DHAVE_RAW_DECL_PCLOSE=1 -DHAVE_RAW_DECL_POPEN=1 -DHAVE_RAW_DECL_SNPRINTF=1 -DHAVE_RAW_DECL_TMPFILE=1 -DHAVE_RAW_DECL_VSNPRINTF=1 -DHAVE_RAW_DECL__EXIT=1 -DHAVE_RAW_DECL_ATOLL=1 -DHAVE_RAW_DECL_STRTOD=1 -DHAVE_RAW_DECL_STRTOLL=1 -DHAVE_RAW_DECL_STRTOULL=1 -DHAVE_STRCASECMP=1 -DHAVE_STRNCASECMP=1 -DHAVE_DECL_STRNCASECMP=1 -DGNULIB_TEST_STRDUP=1 -DGNULIB_STRERROR=1 -DGNULIB_TEST_STRERROR=1 -DHAVE_WINSOCK2_H=1 -Dmy_strftime=nstrftime -DGNULIB_TEST_STRPTIME=1 -DGNULIB_TEST_SYMLINK=1 -DHAVE_WINSOCK2_H=1 -DHAVE_STRUCT_SOCKADDR_STORAGE=1 -DHAVE_STRUCT_SOCKADDR_STORAGE_SS_FAMILY=1 -DHAVE_WINSOCK2_H=1 -Dnlink_t=int -DHAVE_RAW_DECL_FSTAT=1 -DHAVE_RAW_DECL_STAT=1 -DGNULIB_TEST_TIME_R=1 -DGNULIB_TEST_TMPFILE=1 -DHAVE_DECL_TRUNC=1 -DGNULIB_TEST_TRUNC=1 -DHAVE_DECL_TRUNCF=1 -DGNULIB_TEST_TRUNCF=1 -DHAVE_RAW_DECL_CHDIR=1 -DHAVE_RAW_DECL_DUP=1 -DHAVE_RAW_DECL_DUP2=1 -DHAVE_RAW_DECL_FTRUNCATE=1 -DHAVE_RAW_DECL_GETCWD=1 -DHAVE_RAW_DECL_ISATTY=1 -DHAVE_RAW_DECL_LSEEK=1 -DHAVE_RAW_DECL_RMDIR=1 -DHAVE_RAW_DECL_UNLINK=1 -DHAVE_RAW_DECL_USLEEP=1 -DGNULIB_TEST_UNLINK=1 -DGNULIB_TEST_VASPRINTF=1 -DHAVE_RAW_DECL_BTOWC=1 -DHAVE_RAW_DECL_WCTOB=1 -DHAVE_RAW_DECL_MBSINIT=1 -DHAVE_RAW_DECL_MBRTOWC=1 -DHAVE_RAW_DECL_MBRLEN=1 -DHAVE_RAW_DECL_MBSRTOWCS=1 -DHAVE_RAW_DECL_WCRTOMB=1 -DHAVE_RAW_DECL_WCSRTOMBS=1 -DHAVE_RAW_DECL_WMEMCHR=1 -DHAVE_RAW_DECL_WMEMCMP=1 -DHAVE_RAW_DECL_WMEMCPY=1 -DHAVE_RAW_DECL_WMEMMOVE=1 -DHAVE_RAW_DECL_WMEMSET=1 -DHAVE_RAW_DECL_WCSLEN=1 -DHAVE_RAW_DECL_WCSCPY=1 -DHAVE_RAW_DECL_WCSNCPY=1 -DHAVE_RAW_DECL_WCSCAT=1 -DHAVE_RAW_DECL_WCSNCAT=1 -DHAVE_RAW_DECL_WCSCMP=1 -DHAVE_RAW_DECL_WCSNCMP=1 -DHAVE_RAW_DECL_WCSCOLL=1 -DHAVE_RAW_DECL_WCSXFRM=1 -DHAVE_RAW_DECL_WCSDUP=1 -DHAVE_RAW_DECL_WCSCHR=1 -DHAVE_RAW_DECL_WCSRCHR=1 -DHAVE_RAW_DECL_WCSCSPN=1 -DHAVE_RAW_DECL_WCSSPN=1 -DHAVE_RAW_DECL_WCSPBRK=1 -DHAVE_RAW_DECL_WCSSTR=1 -DHAVE_RAW_DECL_WCSTOK=1 -DHAVE_TOWLOWER=1 -DHAVE_RAW_DECL_WCTYPE=1 -DHAVE_RAW_DECL_ISWCTYPE=1 -DHAVE_RAW_DECL_WCTRANS=1 -DHAVE_RAW_DECL_TOWCTRANS=1 -DHAVE_STDINT_H=1 -DHAVE_PTHREAD=1 -DFLOAT_TRUNCATE=volatile -DHAVE_LIBM=1 -DF77_FUNC(name,NAME)=name ## _ -DF77_FUNC_(name,NAME)=name ## _ -DHAVE_IEEE754_DATA_FORMAT=1 -DHAVE_CXX_COMPLEX_SETTERS=1 -DHAVE_CXX_COMPLEX_REFERENCE_ACCESSORS=1 -DHAVE_LIBQHULL_LIBQHULL_H=1 -DHAVE_QHULL=1 -DHAVE_PCRE_H=1 -DHAVE_PCRE_COMPILE=1 -DHAVE_ZLIB_H=1 -DHAVE_Z=1 -DHAVE_HDF5_H=1 -DHAVE_HDF5=1 -DHAVE_FFTW3_H=1 -DHAVE_FFTW3=1 -DHAVE_FFTW3_H=1 -DHAVE_FFTW3F=1 -DHAVE_GLPK_H=1 -DHAVE_GLPK=1 -DHAVE_CURL_CURL_H=1 -DHAVE_CURL=1 -DHAVE_MAGICK=1 -DHAVE_WINDOWS_H=1 -DHAVE_GL_GL_H=1 -DHAVE_GL_GLU_H=1 -DHAVE_OPENGL=1 -DHAVE_FREETYPE=1 -DHAVE_FONTCONFIG=1 -DHAVE_FLTK=1 -DLT_OBJDIR=\".libs/\" -DHAVE_QRUPDATE=1 -DHAVE_QRUPDATE_LUU=1 -DHAVE_SUITESPARSE_AMD_H=1 -DHAVE_AMD=1 -DHAVE_SUITESPARSE_CAMD_H=1 -DHAVE_CAMD=1 -DHAVE_SUITESPARSE_COLAMD_H=1 -DHAVE_COLAMD=1 -DHAVE_SUITESPARSE_CCOLAMD_H=1 -DHAVE_CCOLAMD=1 -DHAVE_SUITESPARSE_CHOLMOD_H=1 -DHAVE_CHOLMOD=1 -DHAVE_SUITESPARSE_CS_H=1 -DHAVE_CXSPARSE=1 -DHAVE_SUITESPARSE_UMFPACK_H=1 -DHAVE_UMFPACK=1 -DUMFPACK_SEPARATE_SPLIT=1 -DHAVE_ARPACK=1 -Duid_t=int -Dgid_t=int -DHAVE_DEV_T=1 -DHAVE_INO_T=1 -DHAVE_LONG_LONG_INT=1 -DHAVE_UNSIGNED_LONG_LONG_INT=1 -DSIZEOF_SHORT=2 -DSIZEOF_INT=4 -DSIZEOF_LONG=4 -DSIZEOF_LONG_LONG=8 -DHAVE_ALLOCA=1 -DHAVE_PLACEMENT_DELETE=1 -DHAVE_DYNAMIC_AUTO_ARRAYS=1 -DHAVE_FAST_INT_OPS=1 -DSIZEOF_LONG_DOUBLE=12 -DHAVE_DIRENT_H=1 -DHAVE_CURSES_H=1 -DHAVE_DIRECT_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_LOCALE_H=1 -DHAVE_MEMORY_H=1 -DHAVE_NCURSES_H=1 -DHAVE_PTHREAD_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_TERMCAP_H=1 -DHAVE_SSTREAM=1 -DHAVE_TR1_UNORDERED_MAP=1 -DUSE_UNORDERED_MAP_WITH_TR1=1 -DHAVE_CONIO_H=1 -DHAVE_BASENAME=1 -DHAVE_CHMOD=1 -DHAVE_DUP2=1 -DHAVE_EXECVP=1 -DHAVE_EXPM1=1 -DHAVE_EXPM1F=1 -DHAVE_GETPID=1 -DHAVE__KBHIT=1 -DHAVE_LGAMMA=1 -DHAVE_LGAMMAF=1 -DHAVE_LOG1P=1 -DHAVE_LOG1PF=1 -DHAVE_PUTENV=1 -DHAVE_ROUNDL=1 -DHAVE_SETLOCALE=1 -DHAVE_SETVBUF=1 -DHAVE_TEMPNAM=1 -DHAVE_TGAMMAF=1 -DHAVE_UMASK=1 -DHAVE_UTIME=1 -DHAVE__CHMOD=1 -DHAVE_DECL_EXP2=1 -DHAVE_DECL_ROUND=1 -DHAVE_DECL_TGAMMA=1 -DHAVE_EXP2=1 -DHAVE_ROUND=1 -DHAVE_TGAMMA=1 -DHAVE_MKSTEMPS=1 -D_WIN32_WINNT=0x0403 -DHAVE_LOADLIBRARY_API=1 -DENABLE_DYNAMIC_LINKING=1 -DHAVE_CMATH_ISNAN=1 -DHAVE_CMATH_ISNANF=1 -DHAVE_CMATH_ISINF=1 -DHAVE_CMATH_ISINFF=1 -DHAVE_CMATH_ISFINITE=1 -DHAVE_CMATH_ISFINITEF=1 -DHAVE_FINITE=1 -DHAVE_ISNAN=1 -DHAVE_SIGNBIT=1 -DHAVE__FINITE=1 -DHAVE__ISNAN=1 -DHAVE_DECL_SIGNBIT=1 -DHAVE_ACOSH=1 -DHAVE_ACOSHF=1 -DHAVE_ASINH=1 -DHAVE_ASINHF=1 -DHAVE_ATANH=1 -DHAVE_ATANHF=1 -DHAVE_ERF=1 -DHAVE_ERFF=1 -DHAVE_ERFC=1 -DHAVE_ERFCF=1 -DHAVE_EXP2F=1 -DHAVE_LOG2=1 -DHAVE_LOG2F=1 -DHAVE_HYPOTF=1 -DHAVE_CBRT=1 -DHAVE_CBRTF=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DHAVE_DECL_TZNAME=1 -DHAVE_TZNAME=1 -DUSE_READLINE=1 -DHAVE_DECL_SYS_SIGLIST=0"
#endif

#ifndef OCTAVE_CONF_UMFPACK_CPPFLAGS
#define OCTAVE_CONF_UMFPACK_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_UMFPACK_LDFLAGS
#define OCTAVE_CONF_UMFPACK_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_UMFPACK_LIBS
#define OCTAVE_CONF_UMFPACK_LIBS "-lumfpack"
#endif

#ifndef OCTAVE_CONF_USE_64_BIT_IDX_T
#define OCTAVE_CONF_USE_64_BIT_IDX_T "false"
#endif

#ifndef OCTAVE_CONF_ENABLE_DYNAMIC_LINKING
#define OCTAVE_CONF_ENABLE_DYNAMIC_LINKING "true"
#endif

#ifndef OCTAVE_CONF_X11_INCFLAGS
#define OCTAVE_CONF_X11_INCFLAGS ""
#endif

#ifndef OCTAVE_CONF_X11_LIBS
#define OCTAVE_CONF_X11_LIBS ""
#endif

#ifndef OCTAVE_CONF_XTRA_CFLAGS
#define OCTAVE_CONF_XTRA_CFLAGS "-mieee-fp"
#endif

#ifndef OCTAVE_CONF_XTRA_CXXFLAGS
#define OCTAVE_CONF_XTRA_CXXFLAGS "-mieee-fp  -IC:/OctaveB/gplibs/include/freetype2 -IC:/OctaveB/gplibs/include   -IC:/OctaveB/gplibs/include  "
#endif

#ifndef OCTAVE_CONF_YACC
#define OCTAVE_CONF_YACC "bison -y"
#endif

#ifndef OCTAVE_CONF_YFLAGS
#define OCTAVE_CONF_YFLAGS ""
#endif

#ifndef OCTAVE_CONF_Z_CPPFLAGS
#define OCTAVE_CONF_Z_CPPFLAGS ""
#endif

#ifndef OCTAVE_CONF_Z_LDFLAGS
#define OCTAVE_CONF_Z_LDFLAGS ""
#endif

#ifndef OCTAVE_CONF_Z_LIBS
#define OCTAVE_CONF_Z_LIBS "-lz"
#endif

#ifndef OCTAVE_CONF_config_opts
#define OCTAVE_CONF_config_opts "'--enable-float-truncate' '--prefix=/c/OctaveB/octave-3.6.4' '--disable-docs' 'LAPACK_LIBS=-llapack' 'CC=gcc -shared-libgcc' 'LDFLAGS=-L/c/OctaveB/gplibs/lib -L/c/OctaveB/OctaveLibs/lib -L/c/OctaveB/GnuWin32/lib -Wl,--allow-multiple-definition -Wl,--enable-auto-import -Wl,--enable-runtime-pseudo-reloc-v2' 'LIBS=-lgfortran -llapack' 'CPPFLAGS=-I/c/OctaveB/gplibs/include -I/c/OctaveB/OctaveLibs/include -I/c/OctaveB/GnuWin32/include' 'CXX=g++ -shared-libgcc' 'F77=gfortran -shared-libgcc'"
#endif

#endif
