/*
 * @(#)matmult_dz_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:30 2004
 *
 *		built from:	matmult_dz_rt.c
 */

#ifndef matmult_dz_rt_h
#define matmult_dz_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_MatMult_DZ(
    creal_T *y,
    const real_T  *A,
    const creal_T *B,
    const int dims[3]);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* matmult_dz_rt_h */
