/*
 * @(#)sort_qk_val_r_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:33 2004
 *
 *		built from:	sort_qk_val_r_rt.c
 */

#ifndef sort_qk_val_r_rt_h
#define sort_qk_val_r_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_Sort_Qk_Val_R(real32_T *dataArray, int_T i, int_T j );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* sort_qk_val_r_rt_h */
