function prefspanel
%PREFSPANEL Registers a serial port object preferences control panel.
%
%   PREFSPANEL registers a Preferences Control panel for the serial port
%   object with the MATLAB IDE.
%

%   MP 11-03-01
%   Copyright 1999-2004 The MathWorks, Inc. 
%   $Revision: 1.2.4.5 $  $Date: 2004/01/16 20:04:36 $


% Register Object-based context menus items in the Workspace Browser.

%   Methods of MatlabObjectMenuRegistry are unsupported.  Calls to these
%   methods will become errors in future releases.

% Define Serial Port Context menu
com.mathworks.mlwidgets.workspace.MatlabCustomClassRegistry.registerClassCallbacks(...
    {'serial'},...
    'Explore',...
    {'Display Summary', ...
	'Call Property Inspector',...
	'-',...
	'Serial Help'},...
    {'display($1)', ...
	'inspect($1);', ...
	'',...
	'help serial/Contents.m'});
