function this = fmincon(Project)
% Creates FMINCON optimizer for specified project.

% Copyright 1986-2004 The MathWorks, Inc.
% $Revision: 1.1.6.7 $ $Date: 2004/04/11 00:46:37 $
this = ResponseOptimizer.fmincon;

% Check OPTIM is on the path
if ~license('test','Optimization_Toolbox')
   error('Simulink Response Optimization requires the Optimization Toolbox.')
end

% Initialize properties
this.initialize(Project);

% Set options
ProjOptions = Project.OptimOptions;
% PhaseOneTotalScaling: see g197045
% NoStopIfFlatInfeas : see g195943
% RelLineSrchBnd: limits |dx| to 2*max(|x|,|typicalX|) during line search
this.Options = optimset(optimset('fmincon'),...
   'GradObj','on',...
   'GradConstr','on',...
   'LargeScale','off',...
   'NoStopIfFlatInfeas','on',...
   'PhaseOneTotalScaling','on',...
   'RelLineSrchBnd',3,...
   'RelLineSrchBndDuration',Inf,...
   'Display',ProjOptions.Display,...
   'MaxIter',ProjOptions.MaxIter,...
   'MaxFunEvals',Inf,...
   'TolCon',ProjOptions.TolCon,...
   'TolFun',ProjOptions.TolFun,...
   'TolX',ProjOptions.TolX);

