/*
 * @(#)fft_scaledata_dz_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:21 2004
 *
 *		built from:	fft_scaledata_dz_rt.c
 */

#ifndef fft_scaledata_dz_rt_h
#define fft_scaledata_dz_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_ScaleData_DZ(
    creal_T     *cplxData,
    int_T        cnt,
    const real_T scaleFactor
    );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* fft_scaledata_dz_rt_h */
