/*
 * @(#)fft_r2dit_tbls_z_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:20 2004
 *
 *		built from:	fft_r2dit_tbls_z_rt.c
 */

#ifndef fft_r2dit_tbls_z_rt_h
#define fft_r2dit_tbls_z_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_R2DIT_TBLS_Z(
    creal_T      *y,
    int_T         nChans,
    const int_T   nRows,
    const int_T   fftLen,
    const real_T *twiddleTable,
    const int_T   twiddleStep,
    const int_T   isInverse
    );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* fft_r2dit_tbls_z_rt_h */
