/*
 * @(#)ifft_dbllen_trig_zbr_zbr_oop_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:22 2004
 *
 *		built from:	ifft_dbllen_trig_zbr_zbr_oop_rt.c
 */

#ifndef ifft_dbllen_trig_zbr_zbr_oop_rt_h
#define ifft_dbllen_trig_zbr_zbr_oop_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_Ifft_DblLen_TRIG_Zbr_Zbr_Oop(
    creal_T       *y,
    const creal_T *x,
    const int_T    fftLen
    );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* ifft_dbllen_trig_zbr_zbr_oop_rt_h */
