function tags = analysistags
%ANALYSISTAGS Returns a cell array of strings containing the tags for the analysis
%             toolbar buttons and menus.  Called by render_menus and render_toolbar.

%   Copyright 1988-2002 The MathWorks, Inc.
%   $Revision: 1.5 $  $Date: 2002/04/14 23:47:45 $ 

% Generate tags for the analysis menu items, and corresponding 
% toolbar items
tags = {...
        'fullviewanalysis',...
        'filterresponsespecs',...
        'magresp',...
        'phaseresp',...
        'magnphaseresp',...
        'groupdelay',...
        'impresp',...
        'stepresp',...
        'pzplot',...
        'filtercoeffs',...
        'whatsthis'};

%        'mcode',...

% [EOF]
