function fig = xpctargetscfigure
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.


%   Copyright 1999-2002 The MathWorks, Inc.
%   $Revision: 1.4.2.1 $  $Date: 2004/04/08 21:04:45 $

%load xpctargetscfigure
set(0,'ShowHiddenHandles','off');
h0 = figure('Color',[0.752941 0.752941 0.752941], ...
            'HandleVisibility','off', ...
            'MenuBar','none', ...
            'Name','xPC Target: Target Manager', ...
            'NumberTitle','off', ...
            'IntegerHandle', 'off', ...
            'PaperType','a4letter', ...
            'Position',[551 470 480 275], ...
            'Renderer', 'zbuffer', ...
            'Tag','tgscfigure');
setxpcfont(h0,8,9);
h1 = uimenu('Parent',h0, ...
            'Label','File', ...
            'Tag','tgmenu1');
h2 = uimenu('Parent',h1, ...
            'Label','New Scope', ...
            'Tag','tgfilemenu1');
h2 = uimenu('Parent',h1, ...
            'Label','Load Scope', ...
            'Separator','on', ...
            'Tag','tgfilemenu3');
h2 = uimenu('Parent',h1, ...
            'Label','Save Scope', ...
            'Tag','tgfilemenu4');
h2 = uimenu('Parent',h1, ...
            'Label','Close all Properties', ...
            'Separator','on', ...
            'Tag','tgfilemenu5');
h2 = uimenu('Parent',h1, ...
            'Label','Delete all Scopes', ...
            'Separator','on', ...
            'Tag','tgfilemenu6');
h2 = uimenu('Parent',h1, ...
            'Label','Close Target Manager', ...
            'Separator','on', ...
            'Tag','tgfilemenu2');
h1 = uicontrol('Parent',h0, ...
               'ListboxTop',0, ...
               'Position',[15 145 90 40], ...
               'String','TargetScope 1', ...
               'Tag','tgscpb1', ...
               'UserData',1);
h1 = uicontrol('Parent',h0, ...
               'ListboxTop',0, ...
               'Position',[135 145 90 40], ...
               'String','TargetScope 2', ...
               'Tag','tgscpb2', ...
               'UserData',2);
h1 = uicontrol('Parent',h0, ...
               'ListboxTop',0, ...
               'Position',[255 145 90 40], ...
               'String','TargetScope 3', ...
               'Tag','tgscpb3', ...
               'UserData',3);
h1 = uicontrol('Parent',h0, ...
               'ListboxTop',0, ...
               'Position',[375 145 90 40], ...
               'String','TargetScope 4', ...
               'Tag','tgscpb4', ...
               'UserData',4);
h1 = uicontrol('Parent',h0, ...
               'ListboxTop',0, ...
               'Position',[15 85 90 40], ...
               'String','TargetScope 5', ...
               'Tag','tgscpb5', ...
               'UserData',5);
h1 = uicontrol('Parent',h0, ...
               'ListboxTop',0, ...
               'Position',[135 85 90 40], ...
               'String','TargetScope 6', ...
               'Tag','tgscpb6', ...
               'UserData',6);
h1 = uicontrol('Parent',h0, ...
               'ListboxTop',0, ...
               'Position',[255 85 90 40], ...
               'String','TargetScope 7', ...
               'Tag','tgscpb7', ...
               'UserData',7);
h1 = uicontrol('Parent',h0, ...
               'ListboxTop',0, ...
               'Position',[375 85 90 40], ...
               'String','TargetScope 8', ...
               'Tag','tgscpb8', ...
               'UserData',8);
h1 = uicontrol('Parent',h0, ...
               'ListboxTop',0, ...
               'Position',[15 25 90 40], ...
               'String','TargetScope 9', ...
               'Tag','tgscpb9', ...
               'UserData',9);
h1 = uicontrol('Parent',h0, ...
               'ListboxTop',0, ...
               'Position',[135 25 90 40], ...
               'String','TargetScope 10', ...
               'Tag','tgscpb10', ...
               'UserData',10);
h1 = uicontrol('Parent',h0, ...
               'ListboxTop',0, ...
               'Position',[255 25 90 40], ...
               'String','TargetScope 11', ...
               'Tag','tgscpb11', ...
               'UserData',11);
h1 = uicontrol('Parent',h0, ...
               'ListboxTop',0, ...
               'Position',[375 25 90 40], ...
               'String','TargetScope 12', ...
               'Tag','tgscpb12', ...
               'UserData',12);
h1 = uicontrol('Parent',h0, ...
               'ListboxTop',0, ...
               'Position',[205 225 70 30], ...
               'String','Multiple', ...
               'Tag','multiplepb');
% Needed for the patches
h1 = axes('Parent',h0, ...
          'Units','pixels', ...
          'CameraUpVector',[0 1 0], ...
          'CameraUpVectorMode','manual', ...
          'Color',[1 1 1], ...
          'Position',[4 4 474 269], ...
          'Tag','tgaxis', ...
          'Visible','off', ...
          'XColor',[0 0 0], ...
          'YColor',[0 0 0], ...
          'ZColor',[0 0 0]);

if nargout > 0, fig = h0; end
guidata(fig, guihandles(fig));
set(0,'ShowHiddenHandles','on');
