function libs = commliblist
% COMMLIBLIST Return list of Communications Blockset libraries.
%
%   See also COMM_LINKS.

% Copyright 1996-2003 The MathWorks, Inc.
% $Revision: 1.17.4.2 $ $Date: 2003/06/03 15:51:00 $

% Comm 1.5:
libs.comm15 = {'commsource','commsink','commsrccod', ...
      'commblkcod','commcnvcod', ...
      'commdigbbnd','commdigpbnd','commanabbnd','commanapbnd', ...
      'commchan','commsync','commutil'};

% Comm 2.5: Obsoleted ones
libs.comm25 = {'commcontsrc2', 'commanabbnd2', 'comminteg2',...
      'commdigpbndam2','commdigpbndpm2','commdigpbndfm2','commdigpbndcpm2'};

% Comm 3.0:
libs.comm3 = {'commrandsrc2', 'commnoisgen2', 'commseqgen2',...
      'commsink2', 'commsrccod2', ...
      'commcrc2', 'commblkcod2', 'commcnvcod2', ...
      'commblkintrlv2', 'commcnvintrlv2', ...
      'commdigbbndam2', 'commdigbbndpm2', 'commdigbbndfm2', 'commdigbbndcpm2', 'commdigbbndtcm2' ...
      'commanapbnd2',...
      'commfilt2', 'commchan2', 'commrflib2',...
      'commsynccomp2', 'commphrec2', 'commtimrec2',...
      'commeq2', 'commsequence2', 'commutil2', ...  
	  'commblksprivate'};

% [EOF]
