function [Props,AsgnVals] = pnames(sys,flag)
%PNAMES  All public properties and their assignable values
%
%   See also  GET, SET.

%       Author(s): P. Gahinet, 7-8-97
%       Copyright 1986-2003 The MathWorks, Inc.
%       $Revision: 1.1.6.2 $  $Date: 2004/04/10 23:12:33 $

% Public properties 
Props = {'InputName' ; 'OutputName' ; 'InputGroup' ; 'OutputGroup' ; ...
      'Name' ; 'Notes' ; 'UserData'};
if nargout>1
   AsgnVals = {...
         'Nu-by-1 cell array of strings';...
         'Ny-by-1 cell array of strings'; ...
         'structure with one field per channel group.';...
         'structure with one field per channel group.';...
         'String';...
         'Text'; ...
         'Arbitrary'};
end

