// keithley.idl : IDL source for keithley.dll
// $Revision: 1.1.6.2 $
// $Date: 2003/12/04 18:39:44 $

// Copyright 2002-2003 The MathWorks, Inc. 
// Coded by OPTI-NUM solutions

// This file will be processed by the MIDL tool to
// produce the type library (keithley.tlb) and marshalling code.
// All GUIDs MUST BE MODIFIED by the adaptor programmer.

import "oaidl.idl";
import "ocidl.idl";
import "daqmex.idl";

	[
		object,
		uuid(881AF6CD-75CD-4eee-9359-2B131270E5BB),
		dual,
		helpstring("IKeithleyAIn Interface"),
		pointer_default(unique)
	]
	interface IKeithleyAIn : IDispatch	// IDispatch interface is not currently implemented
	{};									// for the Keithley adaptor

	[
		object,
		uuid(77F4DFDF-3E26-47de-8321-D44224F05A26),
		dual,
		helpstring("IKeithleyAOut Interface"),
		pointer_default(unique)
	]
	interface IKeithleyAOut : IDispatch
	{};		
	
	[
		object,
		uuid(42C73F21-2251-4106-A198-D8FA99E8D8DB),
		//dual,
		helpstring("IKeithleyDIO Interface"),
		pointer_default(unique)
	]
	interface IKeithleyDIO : IUnknown// IDispatch
	{};							
					

//uuid for adaptor type library.
[
	uuid(2E43588F-706E-4069-B4AB-36221C02ACC9),
	version(1.0),
	helpstring("keithley 1.0 Type Library")
]

library KEITHLEYLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(719A7527-2758-473f-A530-583E823C40B7),
		helpstring("keithleyadapt Class")
	]
	coclass keithleyadapt
	{
		[default] interface ImwAdaptor;
	};

	[
		uuid(DF084B52-04D6-4e6e-B448-CE2D511BDC24),
		helpstring("KeithleyAIn Class")
	]
	coclass keithleyain
	{
		[default] interface IKeithleyAIn;
		interface ImwDevice;
		interface ImwInput;
	};


	[
		uuid(64604F25-F644-43bf-8DCC-968788EDF01B),
		helpstring("KeithleyAOut Class")
	]
	coclass keithleyaout
	{
		[default] interface IKeithleyAOut;
		interface ImwDevice;
		interface ImwOutput;
	};

	[
		uuid(E674596A-2840-429d-9AC6-664A1E781CD3),
		helpstring("KeithleyDIO Class")
	]
	coclass keithleydio
	{
		[default] interface IKeithleyDIO;
		interface ImwDevice;
		interface ImwDIO;
	};
};
