/*
 * @(#)cic_int_lat_3208_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:16 2004
 *
 *		built from:	cic_int_lat_3208_rt.c
 */

#ifndef cic_int_lat_3208_rt_h
#define cic_int_lat_3208_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_CICIntLat3208(
    int            R,
    int            N,
    int            nChans,
    int            nFrames,
    const int32_T *inp,
    int8_T        *out,
    int32_T       *states,
    int            statesPerChanSize,
    const int32_T *stgInpWLs,
    int32_T        finalOutShiftVal,
    int            phase,
    int            ioStride);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* cic_int_lat_3208_rt_h */
