/*
 * @(#)cic_dec_lat_3232_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:15 2004
 *
 *		built from:	cic_dec_lat_3232_rt.c
 */

#ifndef cic_dec_lat_3232_rt_h
#define cic_dec_lat_3232_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_CICDecLat3232(
    int            R,
    int            N,
    int            nChans,
    int            nFrames,
    const int32_T *inp,
    int32_T       *out,
    int32_T       *states,
    int            statesPerChanSize,
    const int32_T *stgInpWLs,
    const int32_T *stgShifts,
    int            phase,
    int            ioStride);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* cic_dec_lat_3232_rt_h */
