function ax = axes(varargin)
%AXES 
%
%  AXES is a subclass of the HG Axes object. The axes is a viewer for the
%  mapmodel.mapmodel object, MODEL.

%   Copyright 1996-2003 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2003/08/01 18:12:52 $

ax = MapGraphics.axes(varargin{:});

set(ax,...
    'DataAspectRatioMode','manual',...
    'DataAspectRatio',[1 1 1],...
    'PlotBoxAspectRatioMode','auto',...
    'NextPlot','Add',...
    'ALimMode','manual',...
    'CLimMode','manual',...
    'XLimMode','manual',...
    'YLimMode','manual',...
    'ZLimMode','manual');
