function value = isGeoTiff(proj)
%ISGEOTIFF True for a GeoTIFF projection structure.
%
%   VALUE = ISGEOTIFF(PROJ) returns 1 if PROJ contains GeoTIFF projection
%   fields, 0 otherwise.
%
%   See also ISMSTRUCT, ISVALIDPROJ.

%   Copyright 1996-2003 The MathWorks, Inc.
%   $Revision: 1.1.6.1 $  $Date: 2003/08/01 18:24:20 $

fieldNames = {'CornerCoords', ...
              'CTProjection', ...
              'Ellipsoid', ...
              'GeoTIFFCodes', ...
              'PM', ...
              'PMLongToGreenwich', ...
              'ProjParm', ...
              'SemiMajor', ...
              'SemiMinor', ...
              'Zone'};
value = isValidProj(proj, fieldNames);
