function out=getinfo(c)
%GETINFO returns a structure with information about the component

%   Copyright 1997-2004 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2004/04/15 00:21:17 $

out=getprotocomp(c);

out.Name = xlate('System Filter');
out.Type = 'SL';
out.Desc = xlate('Executes subcomponents only for certain systems.');
out.ValidChildren={logical(1)};

out.att=struct('minNumBlocks',0,...
   'minNumSubSystems',0,...
   'isMask','either');

out.attx.minNumBlocks=struct(...
   'String','if number of blocks in system >=',...
   'NumberRange',[0 inf]);

out.attx.minNumSubSystems=struct(...
   'String','if number of subsystems >=',...
   'NumberRange',[0 inf]);

out.attx.isMask=struct('String','if system is',...
   'enumValues',{{'yes','no','either'}},...
   'enumNames',{{'masked' ...
         'unmasked' ...
         'either masked or unmasked'}},...
   'UIcontrol','radiobutton');
