% WPPLOTCF    ウェーブレットパケットカラー係数のプロット表示
%
% WPPLOTCF(TREE,DATA)、または、WPPLOTCF(TREE,DATA,COLORMODE)、または、WPPLOTCF
% (TREE,DATA,COLORMODE,AXE)、または、WPPLOTCF(TREE,DATA,COLORMODE,AXE,NB_COLORS)
%



% $Revision: 1.1 $
% Copyright 1995-2002 The MathWorks, Inc.
