/*
 * @(#)vfdly_clip_r_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:37 2004
 *
 *		built from:	vfdly_clip_r_rt.c
 */

#ifndef vfdly_clip_r_rt_h
#define vfdly_clip_r_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* vfdly_clip_r_rt_h */
