/*
 * @(#)vfdly_lin_r_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:37 2004
 *
 *		built from:	vfdly_lin_r_rt.c
 */

#ifndef vfdly_lin_r_rt_h
#define vfdly_lin_r_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_Vfdly_Lin_R(
     const real32_T * const buffptr, 
     const int_T            buflen, 
     real32_T             **yptr, 
     int_T                  ti,
     const int_T            buffstart, 
     const real32_T         frac);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* vfdly_lin_r_rt_h */
