/*
 * @(#)vfdly_lin_d_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:37 2004
 *
 *		built from:	vfdly_lin_d_rt.c
 */

#ifndef vfdly_lin_d_rt_h
#define vfdly_lin_d_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_Vfdly_Lin_D(
     const real_T * const buffptr, 
     const int_T          buflen, 
     real_T             **yptr, 
     int_T                ti,
     const int_T          buffstart, 
     const real_T         frac);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* vfdly_lin_d_rt_h */
