/*
 * @(#)lpc2ac_d_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:34 2004
 *
 *		built from:	lpc2ac_d_rt.c
 */

#ifndef lpc2ac_d_rt_h
#define lpc2ac_d_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_Lpc2Ac_D(
        const real_T *lpc,     /* pointer to input port which points to LP coefficients */
        const real_T *perr,    /* pointer to input port pointing to prediction error */
        real_T       *ac,      /* pointer to output port pointing to the autocorrelation coefficients */
        real_T       *L,       /* Vector L which contains LPC of order 1 ... M , padded with zeros. */ 
        const int_T   M        /* Order of LPC polynomial */
       );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* lpc2ac_d_rt_h */
