/*
 * @(#)acf_fd_r_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:10 2004
 *
 *		built from:	acf_fd_r_rt.c
 */

#ifndef acf_fd_r_rt_h
#define acf_fd_r_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_ACF_FD_R(
    const real32_T *inPtr,
    int_T           inRows,
    real32_T       *outPtr,
    int_T           outRows,
    int_T           outChans,
    int_T           N,
    creal32_T      *buff,
    const real32_T *twid_tbl
);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* acf_fd_r_rt_h */
