/*
 * @(#)allpole_tdf_zz_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:12 2004
 *
 *		built from:	allpole_tdf_zz_rt.c
 */

#ifndef allpole_tdf_zz_rt_h
#define allpole_tdf_zz_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_AllPole_TDF_ZZ(const creal_T         *u,
                          creal_T               *y,
                          creal_T * const       mem_base,
                          const int_T           numDelays,
                          const int_T           sampsPerChan,
                          const int_T           numChans,
                          const creal_T * const den,
                          const int_T           ordDEN,
                          const boolean_T       one_fpf);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* allpole_tdf_zz_rt_h */
