function out=getinfo(c)
%GETINFO returns a structure containing information about the component
%   I=GETINFO(COUTLINE)
%
%   I.Name - component informal name
%   I.Type - component general category 2-letter code
%   I.Desc - short description of the component
%   I.ValidChildren - shows whether or not component can have children
%          ValidChildren={logical(0)} for no children
%          ValidChildren={logical(1)} if children are allowed
%   I.att - component attributes
%   I.attx - information about component attributes
%   I.ref - reference structure
%   I.x - temporary attribute page handle structure

%   Copyright 1997-2004 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2004/04/15 00:10:24 $

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

out=getprotocomp(c);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

out.Name = xlate('Report Options');
out.Type = 'None';
out.Desc = xlate('This component writes the output file and runs the outline.');

out.ValidChildren={logical(1)};
out.ValidParents={logical(0)};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

out.att=struct('DirectoryType','setfile',...
   'DirectoryName','',...
   'FilenameType','setfile',...
   'FilenameName','index',...
   'isIncrementFilename',logical(0),...
   'Format','HTML',...
   'Stylesheet','',...
   'isView',logical(1),... %launch viewing application when done
   'isRegenerateImages',logical(1),...
   'isAutoSaveOnGenerate',logical(0),...
   'PostGenerateFcn','',...
   'isDebug',logical(0),...
   'Description',{xlate('A report')});

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

out.attx.DirectoryType=struct('String','Directory:',...
   'enumValues',{{'setfile' 'pwd' 'other'}},...
   'enumNames',{{'Same as setup file','Present working directory','Other'}},...
   'UIcontrol','radiobutton');

out.attx.DirectoryName=struct('String','',...
   'UIcontrol','edit',...
   'isParsedText',logical(1));

out.attx.FilenameType=struct('String','Filename:',...
   'enumValues',{{'setfile' 'other'}},...
   'enumNames',{{'Same as setup file','Other'}},...
   'UIcontrol','radiobutton');

out.attx.FilenameName=struct('String','',...
   'UIcontrol','edit',...
   'isParsedText',logical(1));

out.attx.isIncrementFilename=struct(...
   'String','If report already exists, increment to prevent overwriting',...
   'Type','LOGICAL',...
   'UIcontrol','checkbox');

out.attx.isView=struct(...
   'String','View report after generating',...
   'Type','LOGICAL',...
   'UIcontrol','checkbox');

out.attx.isRegenerateImages=struct(...
   'String',xlate('Re-generate Simulink & Stateflow images'),...
   'Type','LOGICAL',...
   'UIcontrol','checkbox');

out.attx.isAutoSaveOnGenerate=struct(...
   'String','Save setup file on generation',...
   'Type','LOGICAL',...
   'UIcontrol','checkbox');

out.attx.Format=struct(...
   'Type','ENUM',...
   'String','',...
   'UIcontrol','popupmenu');

out.attx.Stylesheet=struct(...
   'Type','ENUM',...   
   'String','',...
   'UIcontrol','popupmenu');

out.attx.Description=struct(...
   'String','Description',...
   'UIcontrol','multiedit');

