function g=buildui(g)
%BUILDUI creates the Setup File Editor
%   G=BUILDUI(G) where G is an RPTGUI object.

%   Copyright 1997-2004 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2004/04/15 00:16:53 $

g=LocMakeUI(g);
g=savecursor(g,logical(0));
g=updateui(g,'UpdateAll');

set(g.h.fig,...
   'resizefcn',['updateui(',g.ref.grud,',''Resize'');'],...
   'KeyPressFcn',['doguiaction(',g.ref.grud,',''KeyPress'');'],...
   'closerequestfcn',['doguiaction(',g.ref.grud,',''Exit'');']);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%        LocMakeUI          %%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function g=LocMakeUI(g)

h.fig = figure('Colormap',[],...
   'CreateFcn','',...
   'DoubleBuffer','on',...
   'Units',g.hg.all.Units,...
   'HandleVisibility',g.hg.all.HandleVisibility,...
   'Interruptible','on',...
   'IntegerHandle','off',...
   'MenuBar','none', ...
   'Name','Setup File Editor - report.rpt', ...
   'PaperPositionMode','auto',...
   'Visible','off',...
   'NumberTitle','off', ...
   'Position',LocInitFigPos(g), ...
   'Tag','Setup File Editor');

g=LocInitializeLayout(g);

g.hg.all.Parent=h.fig;
g.hg.all.BackgroundColor=get(0,'DefaultUIcontrolBackgroundColor');
g.hg.all.ForegroundColor=get(0,'DefaultUIcontrolForegroundColor');
set(h.fig,'Color',g.hg.all.BackgroundColor);

%-----------Create Menus ---------------
h.FileMenu=LocMakeFileMenu(h.fig,g.ref.grud);
h.EditMenu=LocMakeEditMenu(h.fig,g.ref.grud);
h.WindowMenu.Parent = uimenu('Parent',h.fig, ...
   'Label','&Window', ...
   'Tag','WindowMenu');
h.HelpMenu=LocMakeHelpMenu(h.fig,g.ref.grud);
h.OutlineContext=LocMakeOutlineMenu(h.fig,g.ref.grud);

%----------Create Figure Uicontrols
figCData=getcdata(rptcomponent);
g.ref.CData.questionsmall=figCData.questionsmall;
h.Main=LocMakeMainControls(g.hg.all,g.ref.grud,figCData);
h.Main.outline=outlinehandle(g.s,g.hg.all,g.ref.grud);

set(h.Main.outline,...
   'UIContextMenu',h.OutlineContext.Parent);

h.AttTab.ErrorMessage=uicontrol(g.hg.all,...
   'style','text',...
   'String','Options page too small: resize to see page',...
   'Visible','off');
h.AttTab=LocMakeAttControls(g.hg.all);
h.AddTab=LocMakeAddControls(g.hg.all,g.ref.grud,figCData);
h.GenTab=LocMakeGenControls(g.hg.all,g.ref.grud);

set(h.GenTab.statuspop,'Value',g.s.Setfile.EchoDetail+1);

g.h=h;


%-----------object browser code -----------

g.ref.ObjectBrowserHandle=[];

%try
%   if javaMethod('isMLDesktopExists', 'com.mathworks.ide.desktop.MLDesktop')
%      g.ref.ObjectBrowserHandle=com.mathworks.toolbox.rptgen.RptgenObject.RptgenObject({});
%   end
%end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function ipos=LocInitFigPos(g)

barht=layoutbarht(g);

minwid=480*barht/15.3;
minht=331.5*barht/15.3;

prevunits=get(0,'Units');
set(0,'Units','Points');
screen=get(0,'ScreenSize');
set(0,'Units',prevunits);

hoffset=50;
titleht=60;
voffset=50;

screenwid=screen(3);
screenht=screen(4);

if screenwid<minwid+hoffset;
   hoffset=0;
   %elseif screen(3)>2*minwid
   %   minwid=minwid*1.25;
end

if screenht<minht+voffset+titleht;
   voffset=0;
   %elseif screen(4)>2*minht
   %   minht=minht*1.25;
end

ipos=[hoffset, screen(4)-voffset-minht-titleht, ...
      minwid, minht];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function menuFields=LocMakeFileMenu(uiFig,getRptguiObj)

menuFields.Parent = uimenu('Parent',uiFig, ...
   'Callback',...
   ['doguiaction(',getRptguiObj,',''InitializeMenu'',''FileMenu'');'],...
   'HandleVisibility','off',...
   'Label','&File', ...
   'Tag','FileMenu');

mLabels={'&New Setup File'
   '&Open Setup File...'
   '&Save Setup File'
   'Save Setup File &as...'
   'Save A&ll'
   '&Report' %'A&uto-Save on Generate'
   'Create Lo&g File'
   '&Close'
   'E&xit'};
mAccelerator={'n'
   'o'
   's'
   ''
   ''
   'r' %''
   ''
   'w'
   ''};
mSep={'off'
   'off'
   'off'
   'off'
   'off'
   'on' %'off'
   'off'
   'on'
   'off'};

mCallbacks={['doguiaction(',getRptguiObj,',''OpenFile'',''NEW'');']
   ['doguiaction(',getRptguiObj,',''OpenFile'','''');']
   ['doguiaction(',getRptguiObj,',''SaveAs'',logical(0));']
   ['doguiaction(',getRptguiObj,',''SaveAs'',logical(1));']
   ['doguiaction(',getRptguiObj,',''SaveAll'');']
   ['doguiaction(',getRptguiObj,',''GenerateReport'');']
   ['doguiaction(',getRptguiObj,',''MakeLogFile'',logical(1));']
   ['doguiaction(',getRptguiObj,',''CloseSetfile'');']
   ['doguiaction(',getRptguiObj,',''Exit'');']};

%   ['doguiaction(',getRptguiObj,',''ChangeAutoSave'');']


mField={'fNew'
   'fOpen'
   'fSave'
   'fSaveAs'
   'fSaveAll'
   'fGenerate' %'fAutoSave'
   'fLogFile'
   'fClose'
   'fExit'};

for i=1:length(mField)
   menuFields=setfield(menuFields,mField{i},...
      uimenu('Parent',menuFields.Parent,...
      'HandleVisibility','off',...
      'Label',mLabels{i},...
      'Accelerator',mAccelerator{i},...
      'Separator',mSep{i},...
      'Callback',mCallbacks{i}));
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function menuFields=LocMakeEditMenu(uiFig,getRptguiObj)

menuFields.Parent = uimenu('Parent',uiFig, ...
   'HandleVisibility','off',...
   'Callback',['doguiaction(',getRptguiObj,',''InitializeMenu'',''EditMenu'');'],...
   'Label','&Edit', ...
   'Tag','EditMenu');

mAccelerator={'z'
   'x'
   'c'
   'v'
   ''
   ''
   ''};
mLabels={
   '&Undo'
   'Cu&t Component'
   '&Copy Component'
   '&Paste Component'
   '&Activate/Deactivate Component' 
   '&Delete Component'
   'View &Report Options'
};
mSep={'off' 'on' 'off' 'off' 'on' 'off' 'on'};
mCallbacks={
   ['doguiaction(',getRptguiObj,',''Undo'');']
   ['doguiaction(',getRptguiObj,',''Cut'');']
   ['doguiaction(',getRptguiObj,',''Copy'');']
   ['doguiaction(',getRptguiObj,',''Paste'');']
   ['doguiaction(',getRptguiObj,',''AcDeactivate'');']
   ['doguiaction(',getRptguiObj,',''DeleteComponent'');']
   ['doguiaction(',getRptguiObj,',''SelectOutline'',''open'',1);']
};

mField={'Undo'
   'Cut'
   'Copy'
   'Paste'
   'ActivateDeactivate'
   'DeleteComponent'
   'ViewReportOptionsTab'};

for i=1:length(mField)
   menuFields=setfield(menuFields,mField{i},...
      uimenu('Parent',menuFields.Parent,...
      'Label',mLabels{i},...
      'HandleVisibility','off',...
      'Accelerator',mAccelerator{i},...
      'Separator',mSep{i},...
      'Callback',mCallbacks{i}));
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function menuFields=LocMakeOutlineMenu(uiFig,getRptguiObj);

menuFields.Parent=uicontextmenu(...   
   'HandleVisibility','off',...
   'Callback',['doguiaction(',getRptguiObj,',''InitializeMenu'',''OutlineContext'');'],...
   'Parent',uiFig, ...
   'Tag','OutlineContext');

mLabels={xlate('View Report Options')
   xlate('View Component Options')
   xlate('Cut Component')
   xlate('Copy Component')
   xlate('Paste Component')
   xlate('Activate/Deactivate Component')
   xlate('Collapse/Expand Component')
   xlate('Delete Component')};

mSep={'off' %view report options
   'off' %view component options
   'on' %cut
   'off' %copy
   'off' %paste
   'on' %ac/deac
   'off' %collapse
   'off' %delete
};

mCallbacks={
   ['doguiaction(',getRptguiObj,',''SelectOutline'',''open'',1);']
   ['dotabselect(',getRptguiObj,',1,logical(1));']
   ['doguiaction(',getRptguiObj,',''Cut'');']
   ['doguiaction(',getRptguiObj,',''Copy'');']
   ['doguiaction(',getRptguiObj,',''Paste'');']   
   ['doguiaction(',getRptguiObj,',''AcDeactivate'');']
   ['doguiaction(',getRptguiObj,',''Collapse'');']
   ['doguiaction(',getRptguiObj,',''DeleteComponent'');']
};

mField={'ViewReportOptionsTab'
   'ViewOptionsTab'
   'Cut'
   'Copy'
   'Paste'
   'ActivateDeactivate'
   'CollapseExpand'
   'DeleteComponent'
};

for i=1:length(mField)
   menuFields=setfield(menuFields,mField{i},...
      uimenu('Parent',menuFields.Parent,...
      'HandleVisibility','off',...
      'Label',mLabels{i},...
      'Separator',mSep{i},...
      'Callback',mCallbacks{i}));
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function menuFields=LocMakeHelpMenu(uiFig,getRptguiObj)

menuFields.Parent = uimenu('Parent',uiFig, ...
   'HandleVisibility','off',...
   'Label','&Help', ...
   'Tag','HelpMenu');

mLabels={
   'Setup File &Editor Help'
    'Report Generator &Help'
   '&About Report Generator...'
};
mSep={'off' 'off' 'on'};
mCallbacks={
   'helpview(rptparent,''setedit'',''product'');'
   'doc rptgen/'
   ['helpdlg({''MATLAB Report Generator'';',...
         ''''';',...
         '''Copy' 'right The MathWorks, Inc. 1998''},',...
         '''About the Report Generator'');']
};
mField={
   'hHelpRptgen'
   'hHelpSetedit'
   'hAbout'
};

for i=1:length(mField)
   menuFields=setfield(menuFields,mField{i},...
      uimenu('Parent',menuFields.Parent,...
      'HandleVisibility','off',...
      'Label',mLabels{i},...
      'Separator',mSep{i},...
      'Callback',mCallbacks{i}));
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function hFields=LocMakeMainControls(allProps,getRptguiObj,figCData);

img{3}=struct('ui',figCData.demoteup,...
   'di',figCData.demotedn,...
   'no',figCData.demoteno);

%vestigial third "out" button
%img{3}=struct('uo',figCData.promoteup,...
%   'do',figCData.promotedn,...
%   'no',figCData.promoteno);
img{2}=struct('ds',figCData.movedn,...
   'no',figCData.movednno,...
   'do',figCData.promotedn);
img{1}=struct('us',figCData.moveup,...
   'no',figCData.moveupno,...
   'uo',figCData.promoteup);

for i=length(img):-1:1
   movbtn(i)=uicontrol(allProps,...
      'Style','pushbutton',...
      'UserData',img{i},...
      'BackgroundColor',get(0,'DefaultUIcontrolBackgroundColor'),...
      'ButtonDownFcn',['doguiaction(',getRptguiObj,',''FlipNavDirection'',',num2str(i),');'],...
      'Callback',['doguiaction(',getRptguiObj,',''MoveComponent'',',num2str(i),');']);
end


hFields=struct('movbtn',movbtn,...
   'deacbtn',uicontrol(allProps,...
   'Style','togglebutton',...
   'UserData',struct('ac',figCData.active,...
   'BackgroundColor',get(0,'DefaultUIcontrolBackgroundColor'),...
   'in',figCData.inactive,...
   'no',figCData.deacno),...
   'TooltipString','Activate/Deactivate Component',...
   'Callback',...
   ['doguiaction(',getRptguiObj,',''AcDeactivate'');']),...
   'rembtn',uicontrol(allProps,...
   'Style','pushbutton',...
   'BackgroundColor',get(0,'DefaultUIcontrolBackgroundColor'),...
   'UserData',struct('ok',figCData.remok,'no',figCData.remno),...
   'Callback',...
   ['doguiaction(',getRptguiObj,',''DeleteComponent'');']),...
   'resizeline',uicontrol(allProps,...
   'Enable','off',...
   'Tag','RptgenHorizontalResize',...
   'ToolTipString','Change width of outline and tabs',...
   'Style','frame',...
   'ForegroundColor',allProps.BackgroundColor,...
   'ButtonDownFcn',...
   ['doguiaction(',getRptguiObj,',''HorizResize'',''start'');']),...
   'GenerateBtn',uicontrol(allProps,...
   'Interruptible','on',...
   'Style','pushbutton',...
   'BackgroundColor',get(0,'DefaultUIcontrolBackgroundColor'),...
   'String',xlate('Report'),...
   'TooltipString','Generate a report from the current setup file',...
   'Callback',...
   ['doguiaction(',getRptguiObj,',''GenerateReport'');']),...
   'statusbar',uicontrol(allProps,...
   'HorizontalAlignment','left', ...
   'Style','edit', ...
   'Enable','inactive',...
   'Tag','TextStatusBar'));

   %'tab',axes('Parent',allProps.Parent,...
   %   'HandleVisibility',allProps.HandleVisibility,...
   %   'Units',allProps.Units,...   
   %   'ButtonDownFcn','',...
   %   'Color',allProps.BackgroundColor,...
   %   'Box','on',...
   %   'Xtick',[],...
   %   'Ytick',[],...
   %   'XTickLabelMode','manual',...
   %   'YTickLabelMode','manual',...
   %   'XTickLabel',[],...
   %   'YTickLabel',[]),...


%hacked tab dialog ---------------------
btnString={'Options' 'Add Components' 'Generation Status'};
btnTag={'catab' 'artab' 'getab'};

for i=1:length(btnTag);
   hFields=setfield(hFields,btnTag{i},...
      uicontrol(allProps,...
      'HorizontalAlignment','center', ...
      'SelectionHighlight','off',...
      'enable','inactive',...
      'String',btnString{i}, ...
      'ButtonDownFcn',['dotabselect(',getRptguiObj,',' num2str(i) ');'],...
      'Style','pushbutton', ...
      'Tag','RptgenTabhackButton'));
end

ltg=brighten(allProps.BackgroundColor,.5); %light grey
dkg=brighten(allProps.BackgroundColor,-.5); %dark grey

edgecolor={ltg 'black' 'black' ltg dkg dkg};
for i=length(edgecolor):-1:1
   tabedge(i)=uicontrol(allProps,...
      'style','frame',...
      'HitTest','off',...
      'backgroundcolor',edgecolor{i},...
      'foregroundcolor',edgecolor{i});   
end
%tabedge(4) is the leftmost horizontal tab
%set(tabedge(4),'ButtonDownFcn',...
%   ['doguiaction(',getRptguiObj,',''HorizResize'',''start'');']);


hFields.tabedge=tabedge;


hFields.tabpatch=uicontrol(allProps,...
   'ForegroundColor',allProps.BackgroundColor,...
   'UserData',1,...
   'Style','frame', ...
   'Tag','catab');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function hFields=LocMakeAttControls(allProps)

h=axes('Parent',allProps.Parent,...
   'Units',allProps.Units,...
   'HandleVisibility','off',...
   'Visible','off',...
   'Tag','',...
   'Box','on',...
   'Color','none',...
   'DrawMode','fast',...
   'Xcolor',[0 0 0],...
   'Xlim',[0 1],...
   'Xtick',[],...
   'Ycolor',[0 0 0],...
   'Ylim',[0 1],...
   'Ytick',[]);

aP.Parent=h;
aP.HandleVisibility='off';
aP.Visible='off';
aP.Clipping='on';
%aP.Tag='ComponentAttributesPageObject';

arrowWidth=.1;
arrowLength=.1;
lineOffset=.2;

h(end+1)=line(aP,...
   'XData',[arrowLength 1-arrowLength],...
   'YData',[lineOffset lineOffset]);

h(end+1)=line(aP,...
   'XData',[1-lineOffset 1-lineOffset],...
   'YData',[arrowLength 1-arrowLength]);

h(end+1)=patch(aP,...
   'XData',[0 arrowLength arrowLength],...
   'YData',[lineOffset lineOffset-arrowWidth/2 lineOffset+arrowWidth/2]);

h(end+1)=patch(aP,...
   'XData',[1 1-arrowLength 1-arrowLength],...
   'YData',[lineOffset lineOffset-arrowWidth/2 lineOffset+arrowWidth/2]);

h(end+1)=patch(aP,...
   'XData',[1-lineOffset 1-lineOffset-arrowWidth/2 1-lineOffset+arrowWidth/2],...
   'YData',[0 arrowLength arrowLength]);

h(end+1)=patch(aP,...
   'XData',[1-lineOffset 1-lineOffset-arrowWidth/2 1-lineOffset+arrowWidth/2],...
   'YData',[1 1-arrowLength 1-arrowLength]);

errString={'Options page'
   'too small.'
   ' '
   'Resize to'
   'see options.'};

h(end+1)=text(aP,...
   'String',errString,...
   'Position',[.5-lineOffset/2 .5+lineOffset/2],...
   'HorizontalAlignment','center',...
   'VerticalAlignment','middle');


hFields.ErrorMessage=h;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function hFields=LocMakeAddControls(allProps,getRptguiObj,figCData);

hFields.addbtn=uicontrol(allProps,...
   'Style','pushbutton',...
   'BackgroundColor',get(0,'DefaultUIcontrolBackgroundColor'),...
   'CData',figCData.addno,...
   'UserData',struct('ok',figCData.addok,'no',figCData.addno),...
   'Enable','off',...
   'Tag','Add',...
   'Callback',['doguiaction(',getRptguiObj,',''AddComponent'');']);

hFields.helpbtn=uicontrol(allProps,...
   'Style','pushbutton',...
   'BackgroundColor',get(0,'DefaultUIcontrolBackgroundColor'),...
   'Cdata',figCData.question,...
   'Enable','off',... %enable turned on after buildcomplist
   'BusyAction','cancel',...
   'Tag','Add',...
   'Callback',['doguiaction(',getRptguiObj,',''ComponentHelp'');']);

waitString='Searching the MATLAB path for Report Generator components ....';

hFields.complist = uicontrol(allProps,...
   'BackgroundColor',[1 1 1], ...
   'Callback',['doguiaction(',getRptguiObj,',''SelectComplist'');'],...
   'UserData',1,... %this indicates that the add tab has never been visited
   'String',waitString,...
   'FontAngle','italic',...
   'Enable','inactive',...
   'Style','listbox', ...
   'Tag','ComponentListbox', ...
   'Value',1);

hFields.compinfo = uicontrol(allProps,...
   'HorizontalAlignment','left',...
   'String','',...
   'Style','text');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function hFields=LocMakeGenControls(allProps,getRptguiObj)

hFields.statustext=uicontrol(allProps,...
   'HorizontalAlignment','left',...
   'String','Show status updates:',...
   'Style','text');

statustypes={'0) No messages'
   '1) Error messages only'
   '2) Warning messages'
   '3) Important messages (running a loop)'
   '4) Standard messages (running a component)'
   '5) Low-level messages (running a nested component)'
   '6) All messages'};

hFields.statuspop= uicontrol(allProps,...
   'BackgroundColor',[1 1 1], ...
   'HorizontalAlignment','left',...
   'String',statustypes, ...
   'Callback',['doguiaction(',getRptguiObj,',''ChangeEchoDetail'');'],...
   'Style','popupmenu');

hFields.statuslist=uicontrol(allProps,...
   'Style','listbox',...
   'Tag','StatusReport',...
   'Max',2,'Min',0,'Value',[],...
   'Selected','off',...
   'Enable','inactive',...
   'String',{},...
   'UserData',[],...
   'BackgroundColor',[1 1 1]);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function g=LocInitializeLayout(g);

BS=25;
PD=5;

bH=layoutbarht(g);

l.statbarht=bH;
l.tabht=bH*4/3;
l.padding=bH/3;
l.btnside=pointsperpixel(rptparent)*(25+3)*1.2;

l.minOutlineWidth=8*bH*3/7;
l.minTabBodyWidth=8*bH;

l.minTabBodyHt=7*l.btnside+4*l.padding;