% MAKEMENU   メニュー構造の作成
% 
% MAKEMENU(FIG, LABELS, CALLS)は、文字列行列 LABELS 内の順序に従って、
% FIG で識別されるfigureにメニュー構造体を作成します。カスケード型の
% メニューは、行列 LABELS 内で '>' キャラクタで表わされます。CALLS は、
% コールバックを含んでいる文字列行列です。これは、LABELS と同じ行数です。
% '>'キャラクタの後に任意数の '-' キャラクタが続く LABELS の行は、セパ
% レータ行を適切な位置に配置させます。
%
% MAKEMENU(FIG, LABELS, CALLS, TAGS)は、各々のuimenuアイテムの 'Tag'
% プロパティを割り当てる文字列行列 TAGS を使用します。
%
% LABELS, CALLS, TAGS は、同じ行数でなければなりません。
%
% H = MAKEMENU( ... ) は、作成したすべてのuimenuオブジェクトのハンドル
% 番号を含むベクトルを出力します。
%
% 例題:
% 
%  labels = str2mat( ...
%    '&File', ...
%    '>&New^n', ...
%    '>&Open', ...
%    '>>Open &document^d', ...
%    '>>Open &graph^g', ...
%    '>-------', ...
%    '>&Save^s', ...
%    '&Edit', ...
%    '&View', ...
%    '>&Axis^a', ...
%    '>&Selection region^r' ...
%    );
%       calls = str2mat( ...
%    '', ...
%    'disp(''New'')', ...
%    '', ...
%    'disp(''Open doc'')', ...
%    'disp(''Open graph'')', ...
%    '', ...
%    'disp(''Save'')', ...
%    '', ...
%    '', ...
%    'disp(''View axis'')', ...
%    'disp(''View selection region'')' ...
%    );
%  handles = makemenu(gcf, labels, calls);


%  Steven L. Eddins, 27 May 1994
%  Copyright 1984-2002 The MathWorks, Inc.
%  $Revision: 1.8.4.1 $  $Date: 2004/04/28 02:08:24 $
