function [fittypes,fitcategories,fitnames] = getfittypes()

%   Copyright 2001-2004 The MathWorks, Inc. 
%   $Revision: 1.11.2.1 $  $Date: 2004/02/01 21:42:05 $


fittypes = char('custom',...
   'smoothingspline', 'cubicspline',...
   'linearinterp','pchipinterp','splineinterp','nearestinterp',...
   'exp1','exp2',...
   'rat01','rat02','rat03','rat04','rat05',...
   'rat11','rat12','rat13','rat14','rat15',...
   'rat21','rat22','rat23','rat24','rat25',...
   'rat31','rat32','rat33','rat34','rat35',...
   'rat41','rat42','rat43','rat44','rat45',...
   'rat51','rat52','rat53','rat54','rat55',...
   'gauss1','gauss2','gauss3','gauss4',...
   'gauss5','gauss6','gauss7','gauss8',...
   'sin1','sin2','sin3','sin4',...
   'sin5','sin6','sin7','sin8','sin9',...
   'weibull','power1','power2',...
   'poly1','poly2','poly3','poly4','poly5','poly6','poly7','poly8','poly9',...
   'fourier1','fourier2','fourier3','fourier4','fourier5','fourier6',...
   'fourier7','fourier8');

if nargout > 1
   numfittypes = size(fittypes,1);
   fitcategories = char(repmat(32,numfittypes,11)); % char array of blanks
   fitcategories(1,1:6) = 'custom';
   fitcategories(2:3,1:6) = repmat('spline',2,1);
   fitcategories(4:7,1:11) = repmat('interpolant',4,1);
   fitcategories(8:numfittypes,1:7) = repmat('library',numfittypes-8+1,1);
   if nargout > 2
      numoftypes = size(fittypes,1);
      numofletters = size(fittypes,2);
      fitnames = char('Model',...
         xlate('Smoothing spline'), xlate('Cubic interpolating spline'),...
         xlate('Linear interpolant'),xlate('Shape-preserving (pchip) interpolant'),xlate('Cubic spline interpolant'),...
         xlate('Nearest neighbor interpolant'));
      fitnames(8:numoftypes,1) = upper(fittypes(8:numoftypes,1));
      fitnames(8:numoftypes,2:numofletters) = fittypes(8:numoftypes,2:numofletters);
   end
end
