/*
 * @(#)burg_ak_r_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:14 2004
 *
 *		built from:	burg_ak_r_rt.c
 */

#ifndef burg_ak_r_rt_h
#define burg_ak_r_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_Burg_AK_R(const int_T     N,             /* Input array length */
                     const int_T     order,         /* Order of estimation */
                     const real32_T *u,           /* Input pointer */
                           real32_T *ef,          /* Intermediate variable */
                           real32_T *eb,          /* Intermediate variable */
                           real32_T *anew,        /* Intermediate AR coeffients */
                           real32_T *Acoef,       /* A - Output pointer */
                           real32_T *Kcoef,       /* A - Output pointer */
                           real32_T *Error
                     );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* burg_ak_r_rt_h */
