/*
 * @(#)burg_k_d_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:14 2004
 *
 *		built from:	burg_k_d_rt.c
 */

#ifndef burg_k_d_rt_h
#define burg_k_d_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_Burg_K_D(const int_T   N,             /* Input array length */
                    const int_T   order,         /* Order of estimation */
                    const real_T *u,             /* Input pointer */
                          real_T *ef,            /* Intermediate variable */
                          real_T *eb,            /* Intermediate variable */
                          real_T *Kcoef,         /* A - Output pointer */
                          real_T *Error
                    );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* burg_k_d_rt_h */
