function p=getprotocomp(c)
%GETPROTOCOMP returns a prototype structure for a component

%   Copyright 1997-2004 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2004/04/15 00:11:06 $

%this method returns the prototype background for a 
%component's "getinfo" method.  Getinfo overwrites this prototype.

p=struct('Name','',...
   'Type','',...
   'Desc','',...
   'ValidChildren',{{logical(0)}},...
   'ValidParents',{{logical(1)}},...
   'comp',struct('Class','',...
   'Active',logical(1)),...
   'att',[],...
   'attx',[],...
   'ref',struct('ID',[],'OutlineIndex',[]),...
   'x',struct('all',[]));