/*
 * @(#)qrcompqy_c_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:31 2004
 *
 *		built from:	qrcompqy_c_rt.c
 */

#ifndef qrcompqy_c_rt_h
#define qrcompqy_c_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_qrCompqyC (
    int_T	n,
    int_T	j,
    creal32_T	*qr,
    creal32_T	*qrauxj,
    creal32_T	*y
    );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* qrcompqy_c_rt_h */
