/*
 * @(#)qrcompqy_mixd_z_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:31 2004
 *
 *		built from:	qrcompqy_mixd_z_rt.c
 */

#ifndef qrcompqy_mixd_z_rt_h
#define qrcompqy_mixd_z_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_qrCompqyMixdZ(
    int_T	n,
    int_T	j,
    real_T	*qr,
    real_T	*qrauxj,
    creal_T	*y
    );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* qrcompqy_mixd_z_rt_h */
