/*
 * @(#)qre_z_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:32 2004
 *
 *		built from:	qre_z_rt.c
 */

#ifndef qre_z_rt_h
#define qre_z_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_QRE_Z(int_T m, int_T n, creal_T *q, creal_T *r, real_T *e,
        creal_T *qraux, creal_T *work, int_T *jpvt, creal_T *s);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* qre_z_rt_h */
