/*
 * @(#)qre_c_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:32 2004
 *
 *		built from:	qre_c_rt.c
 */

#ifndef qre_c_rt_h
#define qre_c_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_QRE_C(int_T m, int_T n, creal32_T *q, creal32_T *r, real32_T *e,
        creal32_T *qraux, creal32_T *work, int_T *jpvt, creal32_T *s);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* qre_c_rt_h */
