function frameStruct=controlsframe(c,frameTitle)
%CONTROLSFRAME returns handles to a uicontrol frame
%   S=CONTROLSFRAME(C,'FrameTitle') creates a border frame
%   for use on attribute pages and returns a structure S with fields:
%
%   S.FrameName = a handle to the text UICONTROL displaying FrameTitle
%   S.Frame = a 2x1 vector containing handles to the frame axes
%   S.FrameContent = initially empty and the only part of the
%       S structure which should be modified by the user.  It follows
%       the same rules as c.x.LayoutManager and is used by
%       CONTROLSRESIZE to lay out the frame contents.
%
%   See also: CONTROLSMAKE, CONTROLSRESIZE, CONTROLSUPDATE

%   Copyright 1997-2004 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2004/04/15 00:10:53 $

x=subsref(c,substruct('.','x'));

colors={brighten(x.all.BackgroundColor, -.8),...
      brighten(x.all.BackgroundColor, .8)};

%the light-colored frame should be drawn first
%for visual reasons.

for i=2:-1:1
   fmBox(i)=axes('Parent',x.all.Parent,...
      'Units',x.all.Units,...
      'Tag',x.all.Tag,...
      'HandleVisibility',x.all.HandleVisibility,...
      'Visible',x.all.Visible,...
      'Box', 'on',...
      'Color', 'none',...
      'Xcolor',colors{i},...
      'Ycolor',colors{i},...
      'XTick',[],...
      'YTick',[],...
      'ZTick',[]);
end
   
fmTitle=uicontrol(x.all,...
   'String',xlate(frameTitle),...
   'ForegroundColor',[0 0 0],... %'FontAngle','italic',...
   'Style','text');

frameStruct=struct('Frame',fmBox,...
   'FrameName',fmTitle,...
   'FrameContent',{{}});

