function SavedPrefs = save(Prefs)
%SAVE  Creates backup of SISO Tool preferences.
%
%   See also SISOTOOL.

%   Author(s): P. Gahinet
%   Copyright 1986-2002 The MathWorks, Inc. 
%   $Revision: 1.4 $  $Date: 2002/04/10 05:07:08 $

SavedPrefs = struct(...
    'FrequencyUnits',Prefs.FrequencyUnits,...
    'FrequencyScale',Prefs.FrequencyScale,...
    'MagnitudeUnits',Prefs.MagnitudeUnits,...
    'MagnitudeScale',Prefs.MagnitudeScale,...
    'PhaseUnits',Prefs.PhaseUnits,...
    'Grid',Prefs.Grid,...
    'TitleFontSize',Prefs.TitleFontSize,...
    'TitleFontWeight',Prefs.TitleFontWeight,...
    'TitleFontAngle',Prefs.TitleFontAngle,...
    'XYLabelsFontSize',Prefs.XYLabelsFontSize,...
    'XYLabelsFontWeight',Prefs.XYLabelsFontWeight,...
    'XYLabelsFontAngle',Prefs.XYLabelsFontAngle,...
    'AxesFontSize',Prefs.AxesFontSize,...
    'AxesFontWeight',Prefs.AxesFontWeight,...
    'AxesFontAngle',Prefs.AxesFontAngle,...
    'AxesForegroundColor',Prefs.AxesForegroundColor,...
    'CompensatorFormat',Prefs.CompensatorFormat,...
    'ShowSystemPZ',Prefs.ShowSystemPZ,...
    'LineStyle',Prefs.LineStyle);

