%COMMSTARTUP Default Simulink model settings for Communications Blockset.
%   Changes the default Simulink model settings to values
%   more appropriate for communication system models.
%
%   Include a call to this script in your own startup.m
%   file in order to automatically install these defaults
%   each time you run MATLAB.
%
%   See the Model Parameters section of the Using Simulink
%   manual for more information on model parameter settings.

%   Copyright 1996-2004 The MathWorks, Inc.
%   $Revision: 1.4.4.4 $ $Date: 2004/04/12 23:01:59 $

set_param(0, ...
    'SingleTaskRateTransMsg','error', ...
    'Solver',                'VariableStepDiscrete', ...
    'SolverMode',            'SingleTasking', ...
    'MaxStep',               'auto', ...               
    'StartTime',             '0.0', ...
    'StopTime',              'inf', ...
    'FixedStep',             'auto', ...
    'SaveTime',              'off', ...
    'SaveOutput',            'off', ...
    'AlgebraicLoopMsg',      'error', ...
    'RTWInlineParameters',   'on', ...
    'BooleanDataType',       'off', ...
    'InheritedTsInSrcMsg',   'none');

fprintf('\nChanged default Simulink settings for communication system models (commstartup.m).\n\n');

% [EOF]
