/*
 * @(#)fsub_nu_rc_c_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:18 2004
 *
 *		built from:	fsub_nu_rc_c_rt.c
 */

#ifndef fsub_nu_rc_c_rt_h
#define fsub_nu_rc_c_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_FSub_NU_RC_C(
        const real32_T  *pL,
        const creal32_T *pb,
              creal32_T  *x,
        const int_T       N,
        const int_T       P
        );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* fsub_nu_rc_c_rt_h */
