/*
 * @(#)corr_td_cr_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:17 2004
 *
 *		built from:	corr_td_cr_rt.c
 */

#ifndef corr_td_cr_rt_h
#define corr_td_cr_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_Corr_TD_CR(
    const creal32_T *inPtrA,
    int_T           nRowsA,
    boolean_T       multiChanA,
    const real32_T  *inPtrB,
    int_T           nRowsB,
    boolean_T       multiChanB,
    creal32_T       *outPtr,
    int_T           nRowsY,
    int_T           nChansY
);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* corr_td_cr_rt_h */
