#*****************************************************************************
#*****************************************************************************
#
#               WMAKE makefile wrapper that calls NMAKE
#
#               $Revision: 1.1.6.2 $
#               $Date: 2004/01/31 00:14:06 $
#               $Author: batserve $
#
#   		Copyright 1998-2003 HUMUSOFT s.r.o.
#
#*****************************************************************************
#*****************************************************************************


# at Humusoft the compiler environment is already set
!IFNEQ %buildsite humusoft
VCVARS32 = vsvars32 &&
!ENDIF

# pass DEBUG and LISTING settings to child makefile
!IFDEF DEBUG
MAKEARGS = DEBUG=$(DEBUG)
!ENDIF
!IFDEF LISTING
MAKEARGS = $+ $(MAKEARGS) LISTING=$(LISTING)
!ENDIF

# call the child makefile
all : .SYMBOLIC
	$(VCVARS32) nmake -nologo -f makefile.nmk $(MAKEARGS)

clean : .SYMBOLIC
	$(VCVARS32) nmake -nologo -f makefile.nmk $(MAKEARGS) clean
