/*
 * @(#)fft_dbllen_tbl_c_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:19 2004
 *
 *		built from:	fft_dbllen_tbl_c_rt.c
 */

#ifndef fft_dbllen_tbl_c_rt_h
#define fft_dbllen_tbl_c_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_DblLen_TBL_C(
    creal32_T      *y,
    const int_T     nRows,
    const real32_T *twiddleTable,
    const int_T     twiddleStep
    );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* fft_dbllen_tbl_c_rt_h */
