/*
 * @(#)fft_dblsig_z_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:20 2004
 *
 *		built from:	fft_dblsig_z_rt.c
 */

#ifndef fft_dblsig_z_rt_h
#define fft_dblsig_z_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_DblSig_Z(
    creal_T    *y,
    int_T       nChans,
    const int_T nRows
    );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* fft_dblsig_z_rt_h */
