/*
 * @(#)ifft_addcssignals_c_cbr_oop_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:21 2004
 *
 *		built from:	ifft_addcssignals_c_cbr_oop_rt.c
 */

#ifndef ifft_addcssignals_c_cbr_oop_rt_h
#define ifft_addcssignals_c_cbr_oop_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_Ifft_AddCSSignals_C_Cbr_OOP(
    creal32_T *y,
    const creal32_T *u,
    const int_T   nChans,
    const int_T   nRows
    );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* ifft_addcssignals_c_cbr_oop_rt_h */
