function answer=xpcmngrsigSelect(fpos,sigInfo)
%XPCMNGRSIGSELECT siginal Selector
%   XPCMNGRSIGSELECT is a selector to specify elements of wide signals to
%   add to an xPC Target scope from the xPC Manager UI.

%   Copyright 1996-2003 The MathWorks, Inc.
%   $Revision: 1.1.6.3 $

pos=[fpos(1)+100 fpos(2)+ (fpos(4)-fpos(2))/3 400 300 ];
info.rows=[];
info.cols=[];
dim=sigInfo.dim;

f=figure('Menubar','none',...
    'position',pos,...
    'WindowStyle','Modal',...
    'Name',['Signal Selector: ',sigInfo.blkName],...
    'NumberTitle','off',...
    'Tag','WidesigSelect',...
    'UserData',info,...
    'Color',get(0,'DefaultUicontrolBackgroundColor'));

h=uicontrol(f,...
   'style','frame',...
   'String','Selector',...
   'position',[10,pos(4)-100,pos(3)-20,100-10]);

h=uicontrol(f,...
    'style','Text',...
    'HorizontalAlignment','left',...
    'String','Selector',...
    'position',[20,pos(4)-15,45,12]);

str=['Select the specified elements of the signal to add to a scope.',...
     sprintf('\n'),'y=u(rows) if signal is a vector.',sprintf('\n'),...
     'y=u(rows,cols) if signal is a matrix.',sprintf('\n'),...
     'The elements, rows and columns may not exceed 10 signals.'];

h=uicontrol(f,...
    'style','Text',...  
    'HorizontalAlignment','left',...
    'String',str,...
    'position',[20,pos(4)-90,pos(3)-40,100-30]);

h=uicontrol(f,...
    'style','Text',...
    'HorizontalAlignment','left',...
    'String',['Rows: (Elements up to ',num2str(dim(1)),')'],...
    'position',[20,pos(4)-150,pos(3)-40,20]);

hrow=uicontrol(f,...
    'style','Edit',...
    'HorizontalAlignment','left',...
    'BackGroundColor','w',...
    'String','',...
    'position',[20,pos(4)-170,pos(3)-40,20]);
if dim(2) > 1
   vis='on'; 
   strVal='';
else
   vis='off';
   strVal='1';
end
h=uicontrol(f,...
    'style','Text',...
    'HorizontalAlignment','left',...
    'Visible',vis,...
    'String',['Columns: (Elements up to ',num2str(dim(2)),')'],...
    'position',[20,pos(4)-200,pos(3)-40,20]);

hcol=uicontrol(f,...
    'style','Edit',...
    'HorizontalAlignment','left',...
    'BackGroundColor','w',...
    'String',strVal,...
    'Visible',vis,...
    'position',[20,pos(4)-220,pos(3)-40,20]);

h=uicontrol(f,...
    'style','PushButton',...
    'HorizontalAlignment','left',...    
    'String','OK',...
    'Callback',{@pressOk,[hrow,hcol],dim},...
    'position',[150,20,50,20]);

h=uicontrol(f,...
    'style','PushButton',...
    'HorizontalAlignment','left',...    
    'String','Cancel',...
    'callback',@pressCancel,...
    'position',[210,20,50,20]);

uiwait(f)

figH=findobj(0,'Type','figure','Tag','WidesigSelect');
if isempty(figH)
    answer=[];
    return
end

if ishandle(f)
    answer=get(f,'Userdata');
    delete(f);    
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function pressCancel(src,evt)
figH=get(src,'Parent');
set(figH,'UserData',[]);
uiresume(figH);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function pressOk(src,evt,parH,dim)
figH=get(src,'Parent');
rowH=parH(1);
colH=parH(2);
rowText=get(rowH,'String');
colText=get(colH,'String');

if isempty(rowText) | isempty(colText)
   errordlg('No signal elements specified') 
   return    
end
rowIdx=str2num(rowText);
colIdx=str2num(colText);
if isempty(rowIdx) | isempty(colIdx)
   errordlg('Elements must be numeric values.') 
   set(rowH,'String',' ')
   set(colH,'String',' ')
   return    
end
if ~isempty(find(rowIdx > dim(1)))
   errordlg('Row Element(s) out of Range') 
   return
end
if ~isempty(find(colIdx > dim(2)))
   errordlg('Column Element(s) out of Range') 
   return
end
if strcmpi(get(colH,'Visible'),'on')
    colText=get(colH,'String');
    colIdx=str2num(colText);
else
    colIdx=str2num(colText);
end
info.rows=rowIdx;
info.cols=colIdx;
set(figH,'userdata',info)
uiresume(figH)





