/*
 * @(#)randsrc_u_z_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:34 2004
 *
 *		built from:	randsrc_u_z_rt.c
 */

#ifndef randsrc_u_z_rt_h
#define randsrc_u_z_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_RandSrc_U_Z(creal64_T *y,    /* output signal */ 
                       const real64_T *min,   /* vector of mins */
                       int_T minLen,    /* length of min vector */
                       const real64_T *max,   /* vector of maxs */
                       int_T maxLen,    /* length of max vector */
                       real64_T *state, /* state vectors */
                       int_T nChans,    /* number of channels */
                       int_T nSamps);    /* number of samples per channel */

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* randsrc_u_z_rt_h */
