function usertarget_activatecallback(model)
%   Copyright 2002 The MathWorks, Inc.
%   $Revision: 1.1.4.1 $  $Date: 2004/04/12 23:50:01 $
  
  disp(['*** Activate callback triggered:', sprintf('\n'), ...
        '  Current activte configuration set for model ', ...
        get_param(model, 'Name'), ' is ', ...
        get(getActiveConfigSet(model), 'Name'), ...
        '.  The system target file is ', ...
        get_param(getActiveConfigSet(model), 'SystemTargetFile')]);
