function fcnProps = rtwmath_base_fcn_name_list
%BASE_FCN_NAME_LIST -  List of all possible functions that can
% stored in the math library

% Copyright 2002-2003 The MathWorks, Inc.

fcnProps =  {   'ten_u','abs','acos','acosh','asin','asinh','atan','atan2', ...
                'atanh','ceil','conj','cos','cosh','exp','fix','floor','fmod' ...
                'hermitian','hypot','ldexp','ln','log','log10','mag_square','max','min','mod', ...
                'pow','power','raw_atan2','reciprocal','rem','round', ...
                'saturate','sign','sin','sinh','sqrt','square', ...
                'tan','tanh','transpose','initnonfinite','rtIsInf','rtIsNan', ...
                'rtInf','rtMinusInf','rtNaN','E','EPS','EPSILON','LN_10', ...
                'LOG10E','MAX_VAL','MIN_VAL','PI','RT_E','RT_LOG10E', ...
                'RT_LN_10','RT_PI' ...
            };