/*
 * @(#)ldl_c_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:28 2004
 *
 *		built from:	ldl_c_rt.c
 */

#ifndef ldl_c_rt_h
#define ldl_c_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_LDL_C(
                 creal32_T  *A,    /* Output Matrix */
                 creal32_T  *V,    /* Intermediate array */
                 int_T       n,    /* Number of square matrix rows (or columns)*/ 
                 boolean_T  *state /* Boolean signaling positive definiteness */
                 );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* ldl_c_rt_h */
