function out = emptyfixptsimrange;
%EMPTYSIMRANGE is for internal use only by the Fixed Point Blockset

%
%    Create empty version of structure used in FixPtSimRanges
%

% Copyright 1994-2002 The MathWorks, Inc.
% $Revision: 1.7 $  
% $Date: 2002/04/10 18:58:02 $

out = struct(...
            'Name',[],...
            'DataType',[],...
            'ExpBits',[],...
            'MantBits',[],...
            'FixExp',[],...
            'Slope',[],...
            'Bias',[],...
            'MinValue',[],...
            'TimeOfMin',[],...
            'MaxValue',[],...
            'TimeOfMax',[]);
