/*
 * @(#)polyval_dd_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:31 2004
 *
 *		built from:	polyval_dd_rt.c
 */

#ifndef polyval_dd_rt_h
#define polyval_dd_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_polyval_DD(
    const real_T *u,            /* Input pointer */
          real_T *y,            /* Output pointer */ 
    const real_T *pCoeffs,      /* Pointer to coefficients */
    const int_T   N,            /* Number of coefficients */
    const int_T   n             /* Width of INPORT1*/ 
    );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* polyval_dd_rt_h */
