/*
 * @(#)unwrap_r_rips_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:36 2004
 *
 *		built from:	unwrap_r_rips_rt.c
 */

#ifndef unwrap_r_rips_rt_h
#define unwrap_r_rips_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_Unwrap_R_RIPS(      real32_T  *y, 
                               real32_T  *prev,
                               real32_T  *pcumsum,
                         const real32_T   cutoff,                          
                               int_T      numChans,
                               boolean_T *firstime
                        );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* unwrap_r_rips_rt_h */
