function h = render(this,layerName,legend,ax,visibility)
%RENDER Render the GriddedComponent.
% 
%   H = RENDER(LAYERNAME,LEGEND,AX,VISIBILITY) renders all features
%   as a Surface, into the axes AX, using the symbolization
%   defined in the legend, LEGEND, for the layer defined by LAYERNAME.
%   The indexed image visibility is defined by VISIBILITY.

%   Copyright 1996-2004 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2004/02/01 21:56:11 $

R = this.ReferenceMatrix;

if (~isempty(R))
  [this.Xdata, this.Ydata] = pixcenters(R,size(this.GriddedData));  
% $$$   h = size(this.GriddedData,1);
% $$$   w = size(this.GriddedData,2);
% $$$   
% $$$   [this.Xdata,dummy] = pix2map(R,ones(1,w),1:w);
% $$$   [dummy,this.Ydata] = pix2map(R,1:h,ones(1,h));
end
%[this.Xdata,this.Ydata] = meshgrid(this.Xdata,this.Ydata);

prevClim = get(ax,'CLim');
if strcmp(lower(this.DisplayType),'mesh')
  fc = get(ax,'Color');
  h = MapGraphics.Surface(layerName,...
                          'Parent',ax,...
                          'Xdata',this.Xdata,...
                          'Ydata',this.Ydata,...
                          'Zdata',zeros(size(this.GriddedData)),...
                          'Cdata',this.GriddedData,...
                          'CDataMapping','scaled',...
                          'FaceColor',fc...
                          );
% $$$                           'EdgeColor','flat',...
% $$$                           'FaceLighting','none',...
% $$$                           'EdgeLighting','flat'...
% $$$                           );
else %surf
  h = MapGraphics.Surface(layerName,...
                          'Parent',ax,...
                          'Xdata',this.Xdata,...
                          'Ydata',this.Ydata,...
                          'Zdata',zeros(size(this.GriddedData)),...
                          'Cdata',this.GriddedData,...
                          'CDataMapping','scaled',...
                          'EdgeColor','none',...
                          'FaceColor','flat'...
                          );
end
fig = get(ax,'Parent');
ch = findall(ax,'Type','surface');
cmap = this.ColorMap;
clim = [min(this.GriddedData(:)) max(this.GriddedData(:))];

if length(ch) > 1
  clim = [min([prevClim, clim]) max([prevClim, clim])];
  cmap = demcmap(clim);
end

set(fig,'Colormap',cmap);
set(ax,'CLim',clim);  
set(h,'Visible',visibility);
