/*
 * @(#)pad_pre_rows_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:30 2004
 *
 *		built from:	pad_pre_rows_rt.c
 */

#ifndef pad_pre_rows_rt_h
#define pad_pre_rows_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_PadPreAlongRows(
    const byte_T *u,         /* pointer to input array  (any data type, any complexity) */
    byte_T       *y,         /* pointer to output array (any data type, any complexity) */
    byte_T       *padValue,  /* pointer to value to pad output array
                              * (complexity must match complexity of y)
                              */
    int_T totalInputBytes,   /* total number of bytes in the input array */
    int_T totalSampsToPad,   /* total number of samples to pad */
    int_T bytesPerElement    /* number of bytes in each sample */
    );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* pad_pre_rows_rt_h */
