function includePaths = getIncludePaths (h)
% return include paths for targeting

% $RCSfile: getIncludePaths.m,v $
% $Revision: 1.1.6.3 $ $Date: 2004/04/20 23:20:31 $
% Copyright 2003-2004 The MathWorks, Inc.

mlroot = feval ('matlabroot');
includePaths = ['-i"' '." '...
                '-i"' mlroot '\toolbox\rtw\targets\tic2000\tic2000\include" '...
                '-i"' mlroot '\simulink\include" '...
                '-i"' mlroot '\extern\include" '...
                '-i"' mlroot '\rtw\c\src" '...            
                '-i"' mlroot '\rtw\c\libsrc" '...
                '-i"' mlroot '\toolbox\dspblks\include" '...
                '-i"' mlroot '\toolbox\rtw\targets\tic2000\tic2000\rtlib\include" '...
                '-i"' mlroot '\toolbox\rtw\dspblks\c" '];
           
% [EOF] getIncludePaths.m
