function searchPaths = getSearchPaths(h)
% Returns list of directories in which to search for source
% files that are to be included in the generated CCS project.

% $RCSfile: getSearchPaths.m,v $
% $Revision: 1.1.6.2 $ $Date: 2004/04/08 21:06:36 $
% Copyright 2003-2004 The MathWorks, Inc.

searchPaths = {pwd, ...
                [matlabroot '\toolbox\rtw\targets\tic2000\tic2000\rtlib'], ...
                [matlabroot '\toolbox\rtw\targets\tic2000\tic2000\src'], ...
                [matlabroot '\rtw\c\src'], ...
                [matlabroot '\rtw\c\libsrc'], ...               
                [matlabroot '\toolbox\comm\commshr\src\legacy'], ...
                [matlabroot '\toolbox\commblks\sim\sfun'], ...
                [matlabroot '\toolbox\commblks\sim\src\legacy'], ...
                [matlabroot '\toolbox\fixpoint'], ...
                [matlabroot '\toolbox\fuzzy\fuzzy\src'], ...
                [matlabroot '\simulink\src'] ...
               };

% [EOF] getSearchPaths.m
