/*
 * @(#)lpc2rc_d_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:35 2004
 *
 *		built from:	lpc2rc_d_rt.c
 */

#ifndef lpc2rc_d_rt_h
#define lpc2rc_d_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_Lpc2Rc_D(
        const real_T *lpc,     /* pointer to input port which points to LP coefficients */
        real_T       *rc,      /* pointer to output port pointing to the reflection coefficients */
        const int_T   P        /* Order of LPC polynomial */
       );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* lpc2rc_d_rt_h */
