/*
 * @(#)is_little_endian_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:17 2004
 *
 *		built from:	is_little_endian_rt.c
 */

#ifndef is_little_endian_rt_h
#define is_little_endian_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN int_T isLittleEndian(void);

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* is_little_endian_rt_h */
