/*
 * @(#)srt_qkrec_c_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:33 2004
 *
 *		built from:	srt_qkrec_c_rt.c
 */

#ifndef srt_qkrec_c_rt_h
#define srt_qkrec_c_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_SrtQkRecC(const creal32_T *qid_array, int_T *qid_index, real32_T *sort,
                        int_T i, int_T j );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* srt_qkrec_c_rt_h */
