/*
 * @(#)levdurb_ap_d_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:29 2004
 *
 *		built from:	levdurb_ap_d_rt.c
 */

#ifndef levdurb_ap_d_rt_h
#define levdurb_ap_d_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_LevDurb_AP_D(
    const real_T *u,   /* *u   Input pointer */ 
          real_T *y_A, /* *y_A A output pointer */ 
          real_T *y_P, /* *y_P P output pointer  */ 
    const int_T   N    /* N    Input array length */ 
    );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* levdurb_ap_d_rt_h */
