/*
 * @(#)lpc2cc_r_rt.h    generated by: makeheader 4.21  Tue Mar 30 16:43:29 2004
 *
 *		built from:	lpc2cc_r_rt.c
 */

#ifndef lpc2cc_r_rt_h
#define lpc2cc_r_rt_h

#ifdef __cplusplus
    extern "C" {
#endif

EXPORT_FCN void MWDSP_Lpc2Cc_R(
        const real32_T *lpc,     /* pointer to input port which points to LP coefficients */
        real32_T       *cc,      /* pointer to output port pointing to the cepstrum coefficients */
        const int_T     Np,      /* Order of LPC polynomial (Length - 1) */
        const int_T     Ncc      /* Length of output CC polynomial */
       );

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* lpc2cc_r_rt_h */
