function h = AnnotationLayer(masterAxes)
%AnnotationLayer Overlay Axes
%
%   AnnotationLayer(MASTERAXES) creates an invisible axes on top of
%   MASTERAXES. The XLim, YLim and Position properties of the AnnotationLayer
%   will always be set to the XLim, YLim and Position properties of
%   MASTERAXES. These properties of the AnnotationLayer will update if the
%   properties change on MASTERAXES.

%   Copyright 1996-2003 The MathWorks, Inc.
%   $Revision: 1.1.6.2 $  $Date: 2004/02/01 21:56:23 $

h = MapViewer.AnnotationLayer('DataAspectRatioMode','Manual',...
                              'DataAspectRatio',get(masterAxes,'DataAspectRatio'),...
                              'PlotBoxAspectRatioMode','Manual',...
                              'PlotBoxAspectRatio',get(masterAxes,'PlotBoxAspectRatio'),...
                              'XLimMode','Manual',...
                              'YLimMode','Manual',...
                              'NextPlot','Add',...
                              'Parent',get(masterAxes,'Parent'),...
                              'Xlim',get(masterAxes,'Xlim'),...
                              'Ylim',get(masterAxes,'Ylim'),...
                              'Ydir',get(masterAxes,'Ydir'),...
                              'Units',get(masterAxes,'Units'),...
                              'Position',get(masterAxes,'Position'),...
                              'Box','off',...
                              'HitTest','off',...
                              'Visible','off',...
                              'HandleVisibility','off');

h.MasterAxes = handle(masterAxes);

h.XLimListener = handle.listener(masterAxes,h.MasterAxes.findprop('Xlim'),...
                                 'PropertyPostSet',{@limUpdate h});
h.YLimListener = handle.listener(masterAxes,h.MasterAxes.findprop('Ylim'),...
                                 'PropertyPostSet',{@limUpdate h});

h.PositionListener = handle.listener(masterAxes,...
                                     h.MasterAxes.findprop('Position'),...
                                     'PropertyPostSet',{@limUpdate h});

function limUpdate(hSrc,event,this)
set(this,hSrc.Name,event.NewValue);


