function xpcscwin(varargin)

% XPCSCWIN - XPCSCOPE Helper Function

% Copyright 1996-2003 The MathWorks, Inc.
% $Revision: 1.19.6.1 $ $Date: 2004/04/08 21:05:11 $

colornorm=[0.752941,0.752941,0.752941];
scrsize=get(0,'ScreenSize');

if nargin > 0, flag        = varargin{1}; end
if nargin > 1, scopenumber = varargin{2}; end

if flag == 0

  usrdata.edit.modelname=xpcgate('getname');
  usrdata.edit.scopenumber=scopenumber;

  set(0,'ShowHiddenHandles','on');
  h_main=get(0, 'Children');
  opened=strmatch('xPC Target: Host Manager', get(h_main, 'Name'));
  set(0,'ShowHiddenHandles','off');

  scopemanager=get(h_main(opened), 'UserData');
  usrdata.scopemanager.figure=scopemanager.figure;

  usrdata.edit.scrsize=scrsize;
  usrdata.figure.signalframes=[];

  usrdata.edit.color.used=zeros(7,1);

  usrdata.apiqueue={};

  usrdata.edit.subfigures.signals=-1;
  usrdata.edit.subfigures.trigger=-1;
  usrdata.figures.axis=-1;
  usrdata.figures.export=-1;
  usrdata.edit.figure.scope.position=...
      [(scrsize(3)-630)*0.1,(scrsize(4)-430)*0.2,630,430];
  usrdata.edit.subfigure.signals.position=...
      [(scrsize(3)-500)*0.93,(scrsize(4)-360)*0.88 500 360];
  usrdata.edit.subfigure.trigger.position=...
      [(scrsize(3)-260)*0.55,(scrsize(4)-260)*0.2,260,260];
  usrdata.edit.trigger.mode=...
      xpcgate('getsctriggermode',usrdata.edit.scopenumber)+1;
  usrdata.edit.trigger.slope=...
      xpcgate('getsctriggerslope',usrdata.edit.scopenumber)+1;
  usrdata.edit.trigger.level=...
      xpcgate('getsctriggerlevel',usrdata.edit.scopenumber);
  usrdata.edit.mode.samples=xpcgate('getscnosamples',usrdata.edit.scopenumber);
  usrdata.edit.mode.prepostsamples=xpcgate('getscnoprepostsamples',usrdata.edit.scopenumber);
  usrdata.edit.mode.interleave=...
      xpcgate('getscinterleave',usrdata.edit.scopenumber);
  usrdata.edit.scope.grid='off';
  usrdata.edit.scope.axis.auto='on';
  usrdata.edit.scope.axis.manual='off';
  usrdata.edit.scope.viewmode.graphical='on';
  usrdata.edit.scope.viewmode.numerical='off';
  usrdata.edit.scope.yaxis.max=1;
  usrdata.edit.scope.yaxis.min=-1;
  usrdata.edit.scope.dataplot=...
      ['scope',num2str(usrdata.edit.scopenumber),'_data'];
  usrdata.edit.scope.timeplot=...
      ['scope',num2str(usrdata.edit.scopenumber),'_time'];

  usrdata.dataplot=0;
  usrdata.timeplot=0;
  usrdata.export=0;
  % names=getbio(usrdata.edit.modelname);
  names=xpcgate('getbio',usrdata.edit.modelname);
  names=regexprep(names,'^\s','');
  usrdata.S=getsignals(names,usrdata.edit.modelname);
  if isfield(usrdata.S.model,'error') , return; end;
  usrdata.S.modelpath='';

  usrdata.figures.scope = ...
      figure('Color',[0.8 0.8 0.8], ...
             'Name',['xPC Target: Scope ', ...
                     num2str(usrdata.edit.scopenumber)], ...
             'NumberTitle','off', ...
             'IntegerHandle', 'off', ...
             'MenuBar', 'none', ...
             'Color',colornorm, ...
             'Position',usrdata.edit.figure.scope.position, ...
             'Renderer','zbuffer',...
             'CloseRequestFcn', 'xpcscwin(-3,1)', ...
             'Tag','xPCHostScopeFigure');

  setxpcfont(usrdata.figures.scope,8,9);

  scopesontarget=xpcgate('getscopes','host');
  signalsontarget=xpcgate('getscsignals',usrdata.edit.scopenumber);
  if usrdata.edit.trigger.mode==3
    triggerontarget=xpcgate('getsctriggersignal',usrdata.edit.scopenumber);
  elseif usrdata.edit.trigger.mode==4
    triggerontarget=xpcgate('getsctriggerscope',usrdata.edit.scopenumber);
  else
    triggerontarget=[];
  end;

  trace=[];
  color=[];
  colornum=[];

  usrdata.edit.signals2trace={};
  usrdata.edit.api.signals2trace={[], [], []};
  if xpcgate('getsctriggermode',usrdata.edit.scopenumber)==1
    usrdata.edit.trigger.signal='Software';
  else
    usrdata.edit.trigger.signal='FreeRun';
  end;
  usrdata.edit.api.triggersignal={};

  if ~isempty(signalsontarget)
    for j=1:length(signalsontarget)
      signalname=xpcgate('showsig',usrdata.edit.modelname,signalsontarget(j));
      signalname=getsignal(signalname);

      usrdata.edit.signals2trace{j}=signalname;

      trace(j)=signalsontarget(j);

      [usrdata,newcolor,newcolornum]=getcolor(usrdata);
      [lengthcolor, nop]=size(color);
      color(lengthcolor+1,:)=newcolor;
      colornum(length(colornum)+1)=newcolornum;

      usrdata.edit.api.signals2trace{1,1}=trace;
      usrdata.edit.api.signals2trace{1,2}=color;
      usrdata.edit.api.signals2trace{1,3}=colornum;

      usrdata=setcolorframe(usrdata);
    end;
  end;

  if ~isempty(triggerontarget) & ~isempty(signalsontarget)
    if usrdata.edit.trigger.mode==3
      triggername=xpcgate('showsig',usrdata.edit.modelname,triggerontarget);
      triggername=getsignal(triggername);

      usrdata.edit.trigger.signal=triggername;
      usrdata.edit.api.triggersignal{1,1}=triggerontarget;

      if ~isempty(usrdata.edit.api.signals2trace)
        signalnum=find(usrdata.edit.api.triggersignal{1,1} == ...
                       usrdata.edit.api.signals2trace{1,1});
        delcolor=usrdata.edit.api.signals2trace{1,3};
        usrdata.edit.color.used(delcolor(signalnum))=0;
      end;

      [usrdata,color,colornum]=getcolor(usrdata);

      usrdata.edit.api.triggersignal{1,2}=color;
      usrdata.edit.api.triggersignal{1,3}=colornum;

      usrdata=setcolorframe(usrdata);
    end;
    if usrdata.edit.trigger.mode==4

      usrdata.edit.trigger.signal=['.Scope_',num2str(triggerontarget)];
      usrdata.edit.api.triggersignal{1,1}=triggerontarget;

      [usrdata,color,colornum]=getcolor(usrdata);

      usrdata.edit.api.triggersignal{1,2}=color;
      usrdata.edit.api.triggersignal{1,3}=colornum;

      usrdata=setcolorframe(usrdata);
    end;
  end;

  usrdata.figure.scope.menu_plot = uimenu('Parent',usrdata.figures.scope, ...
                                          'Label','Plot', ...
                                          'Accelerator', 'p', ...
                                          'Tag','menu_plot');

  usrdata.figure.scope.menu_export = ...
      uimenu('Parent',usrdata.figure.scope.menu_plot, ...
             'Label','Variable Name for Export', ...
             'Callback', 'xpcscwin(-12)', ...
             'Tag','menu_export');

  usrdata.figure.scope.menu_y_axis = ...
      uimenu('Parent',usrdata.figure.scope.menu_plot, ...
             'Label','Y-Axis', ...
             'Separator','on', ...
             'Tag','menu_y_axis');

  usrdata.figure.scope.menu_axis_auto = ...
      uimenu('Parent',usrdata.figure.scope.menu_y_axis, ...
             'Label','Auto', ...
             'Checked', usrdata.edit.scope.axis.auto,...
             'Callback', 'xpcscwin(-10)', ...
             'Tag','menu_axis_auto');

  usrdata.figure.scope.menu_axis_manual = ...
      uimenu('Parent',usrdata.figure.scope.menu_y_axis, ...
             'Label','Manual', ...
             'Checked', usrdata.edit.scope.axis.manual,...
             'Callback', 'xpcscwin(-4)', ...
             'Tag','menu_axis_manual');

  usrdata.figure.scope.menu_viewmode = ...
      uimenu('Parent',usrdata.figure.scope.menu_plot, ...
             'Label','View Mode', ...
             'Separator','on', ...
             'Tag','menu_viewmode');

  usrdata.figure.scope.menu_viewmode_graphical = ...
      uimenu('Parent',usrdata.figure.scope.menu_viewmode, ...
             'Label','Graphical', ...
             'Checked', usrdata.edit.scope.viewmode.graphical,...
             'Callback', 'xpcscwin(-20)', ...
             'Tag','menu_viewmode_graphical');

  usrdata.figure.scope.menu_viewmode_numerical = ...
      uimenu('Parent',usrdata.figure.scope.menu_viewmode, ...
             'Label','Numerical', ...
             'Checked', usrdata.edit.scope.viewmode.numerical,...
             'Callback', 'xpcscwin(-21)', ...
             'Tag','menu_viewmode_numerical');

  usrdata.figure.scope.menu_grid = ...
      uimenu('Parent',usrdata.figure.scope.menu_plot, ...
             'Label','Grid', ...
             'Separator','on', ...
             'Accelerator', 'g', ...
             'Checked', usrdata.edit.scope.grid,...
             'Callback', 'xpcscwin(-5)', ...
             'Tag','menu_grid');

  usrdata.figure.scope.menu_close = ...
      uimenu('Parent',usrdata.figure.scope.menu_plot, ...
             'Label','Close', ...
             'Separator','on', ...
             'Callback', 'xpcscwin(-3,1)', ...
             'Tag','menu_close');

  %-----------------------------------
  %Handling Frame
  %-----------------------------------

  usrdata.figure.scope.frm_handling = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'Position',[0.82 0.01 0.17 0.15], ...
                'Style','frame', ...
                'Tag','frm_handling');

  usrdata.figure.scope.ftl_handling = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'Position',[0.825 0.135 0.11 0.04], ...
                'String','HANDLING', ...
                'Style','text', ...
                'Tag','ftl_handling');


  usrdata.figure.scope.pb_start = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'Position',[0.83 0.055 0.07 0.06], ...
                'CallBack', 'xpcscwin(-8)', ...
                'String','Start', ...
                'Tag','pb_start');

  usrdata.figure.scope.pb_close = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'Position',[0.91 0.055 0.07 0.06], ...
                'String','Close', ...
                'CallBack', 'xpcscwin(-3,1)', ...
                'Tag','pb_close');

  %-----------------------------------
  %Trigger Frame
  %-----------------------------------

  usrdata.figure.scope.frm_trigger = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'Position',[0.17 0.01 0.46 0.15], ...
                'Style','frame', ...
                'Tag','frm_trigger');

  usrdata.figure.scope.ftl_trigger = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'Position',[0.175 0.135 0.1 0.04], ...
                'String','TRIGGER', ...
                'Style','text', ...
                'Tag','ftl_trigger');

  usrdata.figure.scope.txt_triggersignal1 = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'HorizontalAlignment','left', ...
                'Position',[0.18 0.08 0.12 0.05], ...
                'String','Trigger Signal:', ...
                'Style','text', ...
                'Tag','txt_triggersignal1');

  trigger=usrdata.edit.trigger.signal;
  trigger(find(trigger=='.'))='/';
  if ~isempty(usrdata.edit.api.triggersignal)
    color=usrdata.edit.api.triggersignal{1,2};
  else
    color=[0 0 0];
  end;

  usrdata.figure.scope.txt_triggersignal2 = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'ForegroundColor',color, ...
                'HorizontalAlignment','left', ...
                'Position',[0.3 0.08 0.32 0.05], ...
                'String',trigger, ...
                'Style','text', ...
                'Tag','txt_triggersignal2');

  usrdata.figure.scope.pb_definetrigger = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'Position',[0.21 0.025 0.15 0.05], ...
                'String','Define Trigger', ...
                'CallBack', 'xpcscwin(-2)', ...
                'Tag','pb_definetrigger');

  usrdata.figure.scope.pb_softtrig = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'Enable', 'off', ...
                'Position',[0.44 0.025 0.15 0.05], ...
                'String','Software Trigger', ...
                'CallBack', 'xpcscwin(-17)', ...
                'Tag','pb_softtrig');

  %-----------------------------------
  % TRACING Frame
  %-----------------------------------

  usrdata.figure.scope.frm_mode = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'Position',[0.64 0.01 0.17 0.15], ...
                'Style','frame', ...
                'Tag','frm_mode');

  usrdata.figure.scope.ftl_mode = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'Position',[0.645 0.135 0.1 0.04], ...
                'String','TRACING', ...
                'Style','text', ...
                'Tag','ftl_mode');

  usrdata.figure.scope.txt_interleave = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'HorizontalAlignment','left', ...
                'Position',[0.65 0.03 0.1 0.04], ...
                'String','Interleave', ...
                'Style','text', ...
                'Tag','txt_interleave');

  usrdata.figure.scope.txt_samples = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'HorizontalAlignment','left', ...
                'Position',[0.65 0.08 0.1 0.04], ...
                'String','Samples', ...
                'Style','text', ...
                'Tag','txt_samples');

  usrdata.figure.scope.ed_interleave = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'BackgroundColor',[1 1 1], ...
                'HorizontalAlignment','left', ...
                'Position',[.73 .035 .075 .045], ...
                'String', num2str(usrdata.edit.mode.interleave), ...
                'Style','edit', ...
                'Callback', 'xpcscwin(-6)', ...
                'Tag','ed_interleave');

  usrdata.figure.scope.ed_samples = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'BackgroundColor',[1 1 1], ...
                'HorizontalAlignment','left', ...
                'Position',[.72 .085 .085 .045], ...
                'String', convsample(usrdata.edit.mode.prepostsamples,usrdata.edit.mode.samples), ...
                'Style','edit', ...
                'Callback', 'xpcscwin(-7)', ...
                'Tag','ed_samples');

  %-----------------------------------
  % SIGNAL Frame
  %-----------------------------------

  usrdata.figure.scope.frm_signal = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'Position',[0.01 0.01 0.15 0.15], ...
                'Style','frame', ...
                'Tag','frm_signal');

  usrdata.figure.scope.ftl_signals = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'Position',[0.015 0.135 0.1 0.04], ...
                'String','SIGNALS', ...
                'Style','text', ...
                'Tag','ftl_signals');

  usrdata.figure.scope.pb_add_remove = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'Position',[0.02 0.02 0.13 0.05], ...
                'String','Add/Remove', ...
                'CallBack', 'xpcscwin(-1)', ...
                'Tag','pb_add_remove');

  usrdata.figure.scope.pb_export = ...
      uicontrol('Parent',usrdata.figures.scope, ...
                'Units','normalized', ...
                'Position',[0.02 0.08 0.13 0.05], ...
                'String','Export', ...
                'CallBack', 'xpcscwin(-11)', ...
                'Tag','pb_export');

  for i=1:15
    usrdata.figure.scope.txt_numerical(i) = ...
        uicontrol('Parent',usrdata.figures.scope, ...
                  'Units','normalized', ...
                  'HorizontalAlignment','right', ...
                  'Position',[0.2 0.3 0.1 0.04], ...
                  'String','0.0000000', ...
                  'Style','text', ...
                  'Visible','off',...
                  'BackgroundColor', [1 1 1],...
                  'Tag','txt_numerical');
  end

  %-----------------------------------
  %create Plot
  %-----------------------------------

  usrdata.figure.scope.plot = axes('Parent',usrdata.figures.scope, ...
                                   'Units','normalized', ...
                                   'CameraUpVector',[0 1 0], ...
                                   'Color',[1 1 1], ...
                                   'Position',[.1 .27 .87 .67], ...
                                   'Tag','plot', ...
                                   'XGrid',usrdata.edit.scope.grid,...
                                   'YGrid',usrdata.edit.scope.grid,...
                                   'XColor',[0 0 0], ...
                                   'YColor',[0 0 0],...
                                   'XLimMode','manual',...
                                   'YLimMode','auto');

  for i=1:15
    usrdata.figure.scope.txt_numerical(i) = ...
        text('Parent',usrdata.figure.scope.plot, ...
             'Units','normalized', ...
             'HorizontalAlignment','right', ...
             'Position',[0.2 0.3 0], ...
             'String','0.0000000', ...
             'Visible','off',...
             'FontSize',12,...
             'Tag','txt_numerical');
  end

  for i=1:15
    usrdata.line_plot(i)=line(0,0);
  end;

  set(usrdata.figure.scope.plot,'HandleVis','off');
  set(usrdata.figures.scope,'HandleVis','off');

  set(usrdata.figures.scope, 'userdata', usrdata);
  %scopemanager.scopes=-1;
  scopemanager.scopes(usrdata.edit.scopenumber)=usrdata.figures.scope;

  set(usrdata.scopemanager.figure, 'UserData', scopemanager);

  if xpcgate('getscstate',usrdata.edit.scopenumber)~=4
    if ~isempty(usrdata.edit.signals2trace)
      if usrdata.edit.trigger.mode==2
        set(usrdata.figure.scope.pb_softtrig, 'Enable','on');
        set(usrdata.figure.scope.pb_start, ...
            'String','Stop','CallBack','xpcscwin(-9)');
        set(gcbf,'UserData',usrdata);
      else
        set(usrdata.figure.scope.pb_start, ...
            'String','Stop','CallBack','xpcscwin(-9)');
        set(gcbf,'UserData',usrdata);
        if isempty(scopemanager.handles.scopestart)
          scopemanager.handles.scopestart(1)=usrdata.figures.scope;
        else
          if isempty(find(scopemanager.handles.scopestart == ...
                          usrdata.figures.scope))
            scopemanager.handles.scopestart(length(scopemanager.handles.scopestart)+1)=usrdata.figures.scope;
          end;
        end;

        usrdata=exec_queue(usrdata);

        xpcgate('scstart',usrdata.edit.scopenumber);
        if usrdata.edit.trigger.mode==2
          xpcgate('softtrig',usrdata.edit.scopenumber);
        end;

        defxpctimer(3,100,'xpcscope');
      end;
    end;
  end;

  set(usrdata.figures.scope, 'userdata', usrdata);
  set(usrdata.scopemanager.figure, 'UserData', scopemanager);

  %-----------------------------------
  %push button Add/Remove Signal
  %-----------------------------------

else
  if (nargin > 2)
    figH = varargin{3};
  else
    figH = gcbf;
  end
  usrdata=get(figH, 'userdata');

  if flag == -1

    if usrdata.edit.subfigures.signals==-1
      xpcscsignalwin(usrdata.figures.scope);
    else
      figure(usrdata.edit.subfigures.signals);
    end;


    %-----------------------------------
    %push button Define Trigger
    %-----------------------------------

  elseif flag == -2

    if usrdata.edit.subfigures.trigger==-1
      xpcsctriggerwin(0,0);
    else
      figure(usrdata.edit.subfigures.trigger);
    end;


    %-----------------------------------
    %Deletefcn
    %-----------------------------------

  elseif flag==-3
    %----------------------------------------------------------------------  
    % determine the Object where delete event came from to process the
    % delete request.
    if strcmp(get(gcbf,'name'),'xPC Target Remote Control Tool') %came from rctool
      scopnumcell=get(get(gco,'userdata'),'userdata');
      scopeval=get(get(gco,'userdata'),'value');
      scnumstr=scopnumcell{scopeval};
      scwinstr=['xPC Target: Scope ',scnumstr(1:find(scnumstr==' ')-1)];
      fvisibiltystat=get(0,'showhiddenhandles');
      set(0,'showhiddenhandles','on');
      h_gcbf=findobj(0,'type','figure','Name',scwinstr);
      set(0,'showhiddenhandles',fvisibiltystat);
    else% From xpcscwin fig window
      h_gcbf=gcbf;
    end
    %----------------------------------------------------------------------
    if scopenumber==0
      scopemanager=get(h_gcbf, 'UserData');
      usrdata=get(scopemanager.scopetodelete, 'userdata');
    elseif scopenumber==2
      set(0,'ShowHiddenHandles','on');
      h_main=get(0, 'Children');
      opened=strmatch('xPC Target: Host Manager', get(h_main, 'Name'));
      set(0,'ShowHiddenHandles','off');
      scopemanager=get(h_main(opened), 'UserData');
      usrdata=get(scopemanager.scopetodelete, 'userdata');
    elseif scopenumber==1
      usrdata=get(h_gcbf, 'userdata');
      scopemanager=get(usrdata.scopemanager.figure, 'UserData');
    end;

    for i=1:length(scopemanager.scopes)
      if scopemanager.scopes(i)~=-1 & scopemanager.scopes(i) ~= 0
        data=get(scopemanager.scopes(i),'UserData');
        if ~isempty(data.edit.api.triggersignal)
          if data.edit.api.triggersignal{1,1}==usrdata.edit.scopenumber & data.edit.trigger.mode==4
            %delete old color
            if (~isempty(data.edit.api.triggersignal) & ...
                xpcgate('getsctriggermode',data.edit.scopenumber)==3)
              data.edit.color.used(data.edit.api.triggersignal{1,3})=0;
            end;
            if data.edit.subfigures.trigger~=-1
              set(data.subfigure.trigger.ed_triggerlevel, 'Enable', 'off');
              set(data.subfigure.trigger.pop_triggerslope, 'Enable', 'off');
              set(data.subfigure.trigger.txt_triggersignal2, 'Enable', 'off');
              set(data.subfigure.trigger.lb_signallist, ...
                  'String', '','Enable', 'off');
              set(data.subfigure.trigger.pop_triggermode, 'Value',1);
              set(data.subfigure.trigger.txt_triggersignal1, ...
                  'String', 'Signal:');
              set(data.subfigure.trigger.txt_triggersignal2, ...
                  'String', data.edit.trigger.signal,...
                  'ForegroundColor',[0 0 0]);
            end;
            data.edit.trigger.mode=1;

            if (~isempty(data.edit.api.signals2trace) & ...
                ~isempty(data.edit.api.triggersignal))
              signalnum=find(data.edit.api.triggersignal{1,1} == ...
                             data.edit.api.signals2trace{1,1});
              delcolor=data.edit.api.signals2trace{1,3};
              data.edit.color.used(delcolor(signalnum))=1;
            end;
            data=setcolorframe(data);

            data.edit.api.triggersignal={};
            data.edit.trigger.signal='FreeRun';
            set(data.figure.scope.txt_triggersignal1, ...
                'String', 'Trigger Signal:');
            set(data.figure.scope.txt_triggersignal2, ...
                'String', data.edit.trigger.signal,'ForegroundColor',[0 0 0]);

            data=add_queue(data,'xpcgate(''setsctriggermode'',usrdata.edit.scopenumber,0)');
            data=exec_queue(data);
            set(scopemanager.scopes(i),'UserData',data);
          end;
        end;
      end;
    end;
    if scopemanager.scopes(usrdata.edit.scopenumber)~=-1
      scopemanager.scopetodelete=usrdata.figures.scope;
      set(usrdata.scopemanager.figure,'UserData',scopemanager);
      eval('xpcgate(''delscope'',usrdata.edit.scopenumber)');
      xpcscope(-8);
    end;
    if usrdata.edit.subfigures.trigger~=-1,
      delete(usrdata.edit.subfigures.trigger);
    end;
    if usrdata.edit.subfigures.signals~=-1,
      delete(usrdata.edit.subfigures.signals);
    end
    if usrdata.figures.axis~=-1,
      delete(usrdata.figures.axis);
    end;
    if usrdata.figures.export~=-1,
      delete(usrdata.figures.export);
    end;
    delete(usrdata.figures.scope);
    xpcscope(-11);

    %-----------------------------------
    %Menu Y-Axis manual
    %-----------------------------------

  elseif flag == -4

    ylim=get(usrdata.figure.scope.plot,'YLim');
    ymin=num2str(ylim(1));
    ymax=num2str(ylim(2));

    if usrdata.figures.axis==-1

      usrdata.figures.axis = ...
          figure('Color',[0.8 0.8 0.8], ...
                 'Name','Define Y-Axis Scaling', ...
                 'NumberTitle','off', ...
                 'MenuBar', 'none', ...
                 'Color',colornorm, ...
                 'Units','points',...
                 'HandleVisibility','off',...
                 'IntegerHandle', 'off', ...
                 'CloseRequestFcn', 'xpcscwin(-14)', ...
                 'Position',[scrsize(3)/2-150,scrsize(4)/2-100,150,100], ...
                 'Tag','YAxisFigure');
      setxpcfont(usrdata.figures.axis,8,9);
      set(usrdata.figures.axis,'Userdata',usrdata.figures.scope);


      usrdata.figure.axis.txt_ymax = ...
          uicontrol('Parent',usrdata.figures.axis, ...
                    'Units','normalized', ...
                    'HorizontalAlignment','left', ...
                    'Position',[0.1 0.7 0.3 0.15], ...
                    'String','Y_max:', ...
                    'Style','text', ...
                    'Tag','txt_ymax');

      usrdata.figure.axis.ed_ymax = ...
          uicontrol('Parent',usrdata.figures.axis, ...
                    'Units','normalized', ...
                    'BackgroundColor',[1 1 1], ...
                    'HorizontalAlignment','right', ...
                    'Position',[.5 .73 .4 .15], ...
                    'String', ymax, ...
                    'Style','edit', ...
                    'Callback', 'xpcscwin(-13)', ...
                    'Tag','ed_ymax');

      usrdata.figure.axis.txt_ymin = ...
          uicontrol('Parent',usrdata.figures.axis, ...
                    'Units','normalized', ...
                    'HorizontalAlignment','left', ...
                    'Position',[0.1 0.45 0.3 0.15], ...
                    'String','Y_min:', ...
                    'Style','text', ...
                    'Tag','txt_ymin');

      usrdata.figure.axis.ed_ymin = ...
          uicontrol('Parent',usrdata.figures.axis, ...
                    'Units','normalized', ...
                    'BackgroundColor',[1 1 1], ...
                    'HorizontalAlignment','right', ...
                    'Position',[.5 .48 .4 .15], ...
                    'String', ymin, ...
                    'Style','edit', ...
                    'Callback', 'xpcscwin(-13)', ...
                    'Tag','ed_ymin');

      usrdata.figure.axis.pb_apply = ...
          uicontrol('Parent',usrdata.figures.axis, ...
                    'Units','normalized', ...
                    'Position',[0.1 0.05 0.35 0.25], ...
                    'String','Apply', ...
                    'CallBack', 'xpcscwin(-13)', ...
                    'Tag','pb_apply');

      usrdata.figure.axis.pb_close = ...
          uicontrol('Parent',usrdata.figures.axis, ...
                    'Units','normalized', ...
                    'Position',[0.55 0.05 0.35 0.25], ...
                    'String','Close', ...
                    'CallBack', 'xpcscwin(-14)', ...
                    'Tag','pb_close');

      set(usrdata.figures.scope,'UserData',usrdata);

    else
      figure(usrdata.figures.axis);
    end;

    %-----------------------------------
    %Menu Y-Axis auto
    %-----------------------------------

  elseif flag == -10

    set(usrdata.figure.scope.plot,'YLimMode','auto');
    set(usrdata.figure.scope.menu_axis_auto,'Checked','on');
    set(usrdata.figure.scope.menu_axis_manual,'Checked','off');
    usrdata.edit.scope.axis.auto='on';
    usrdata.edit.scope.axis.manual='off';

    set(gcbf,'UserData',usrdata);

    %-----------------------------------
    %Menu Grid
    %-----------------------------------

  elseif flag == -5

    if strcmp('off', get(usrdata.figure.scope.menu_grid,'Checked'))
      set(usrdata.figure.scope.menu_grid,'Checked','on');
      set(usrdata.figure.scope.plot,'XGrid','on','YGrid','on');
      usrdata.edit.scope.grid='on';
    else
      set(usrdata.figure.scope.menu_grid,'Checked','off');
      set(usrdata.figure.scope.plot,'XGrid','off','YGrid','off');
      usrdata.edit.scope.grid='off';
    end;

    set(gcbf,'UserData',usrdata);

    %-----------------------------------
    %CallBack Interleave
    %-----------------------------------

  elseif flag == -6

    if isempty(str2num(get(usrdata.figure.scope.ed_interleave, 'String')))
      errordlg('Interleave must be a number');
      set(usrdata.figure.scope.ed_interleave, ...
          'String', num2str(usrdata.edit.mode.interleave));
    elseif str2num(get(usrdata.figure.scope.ed_interleave, 'String'))<=0
      errordlg('Interleave must be greater then 0');
      set(usrdata.figure.scope.ed_interleave, ...
          'String', num2str(usrdata.edit.mode.interleave));
    else
      state=get(usrdata.figure.scope.pb_start,'String');
      if strcmp(state,'Start')
        interleave=get(usrdata.figure.scope.ed_interleave, 'String');
        usrdata.edit.mode.interleave=interleave;
        set(gcbf,'UserData',usrdata);
        xpcgate('setscinterleave',...
                usrdata.edit.scopenumber,str2num(usrdata.edit.mode.interleave));
      end;
    end;

    %-----------------------------------
    %CallBack Samples
    %-----------------------------------

  elseif flag == -7

    [prepostsamples,samples]=convsample(get(usrdata.figure.scope.ed_samples, 'String'));
    if isempty(samples)
      errordlg('Samples must be a number');
      set(usrdata.figure.scope.ed_samples,...
          'String', convsample(usrdata.edit.mode.prepostsamples,usrdata.edit.mode.samples));
    elseif samples<=2
      errordlg('Samples must be greater than 2');
      set(usrdata.figure.scope.ed_samples,...
          'String', convsample(usrdata.edit.mode.prepostsamples,usrdata.edit.mode.samples));
    else
      state=get(usrdata.figure.scope.pb_start,'String');
      if strcmp(state,'Start')
        samples=get(usrdata.figure.scope.ed_samples, 'String');
        [prepostsamples,samples]=convsample(samples);
        usrdata.edit.mode.samples=samples;
        usrdata.edit.mode.prepostsamples=prepostsamples;
        set(gcbf,'UserData',usrdata);
        xpcgate('setscnosamples',...
                usrdata.edit.scopenumber,usrdata.edit.mode.samples);
        xpcgate('setscnoprepostsamples',...
                usrdata.edit.scopenumber,usrdata.edit.mode.prepostsamples);
      end;
    end;

    %-----------------------------------
    %CallBack Start
    %-----------------------------------

  elseif flag == -8

    if ~isempty(usrdata.edit.signals2trace)
      if usrdata.edit.trigger.mode==2
        set(usrdata.figure.scope.pb_softtrig, 'Enable','on');
        set(usrdata.figure.scope.pb_start,...
            'String','Stop','CallBack','xpcscwin(-9)');
        set(figH, 'UserData',usrdata);
      else
        set(usrdata.figure.scope.pb_start, ...
            'String','Stop','CallBack','xpcscwin(-9)');
        set(figH, 'UserData',usrdata);
        xpcscope(-9, figH);
      end;
    end;

    %-----------------------------------
    %CallBack Stop
    %-----------------------------------

  elseif flag == -9

    set(usrdata.figure.scope.pb_softtrig, 'Enable','off');
    set(usrdata.figure.scope.pb_start, ...
        'String','Start','CallBack','xpcscwin(-8)');
    set(figH, 'UserData',usrdata);
    xpcscope(-10, figH);

    %-----------------------------------
    %CallBack SoftTrig
    %-----------------------------------

  elseif flag == -17

    set(usrdata.figure.scope.pb_softtrig, 'Enable','off');
    set(gcbf,'UserData',usrdata);
    xpcscope(-9, []);

    %-----------------------------------
    %CallBack Export Data
    %-----------------------------------

  elseif flag == -11
    startstate=get(usrdata.figure.scope.pb_start,'String');
    softtrig1=get(usrdata.figure.scope.pb_softtrig, 'Enable');
    if strcmp(startstate,'Stop') & strcmp(softtrig1,'off')
      usrdata.export=1;
    else
      %if xpcgate('isscfinished',usrdata.edit.scopenumber)
      yexport=[];
      for i=1:15
        if strcmp(get(usrdata.line_plot(i),'Visible'),'on')
          yexport=[yexport,(get(usrdata.line_plot(i),'YData'))'];
        end
      end
      texport=(get(usrdata.line_plot(1),'XData'))';
      %yexport=xpcgate('getscdata',usrdata.edit.scopenumber);
      %texport=(0:(xpcgate('getscnosamples',...
      %                    usrdata.edit.scopenumber)-1))*...
      %        xpcgate('getts')*...
      %        xpcgate('getscinterleave',usrdata.edit.scopenumber);
      assignin('base',usrdata.edit.scope.dataplot,yexport);
      assignin('base',usrdata.edit.scope.timeplot,texport');
    end;
    set(gcbf,'UserData',usrdata);


    %-----------------------------------
    %Menu Export Variable Name
    %-----------------------------------

  elseif flag==-12

    if usrdata.figures.export==-1

      usrdata.figures.export = ...
          figure('Color',[0.8 0.8 0.8], ...
                 'Name','Variable Name for Export', ...
                 'NumberTitle','off', ...
                 'MenuBar', 'none', ...
                 'Color',colornorm, ...
                 'Units','points',...
                 'HandleVisibility','off',...
                 'IntegerHandle', 'off', ...
                 'CloseRequestFcn', 'xpcscwin(-16)', ...
                 'Position',[scrsize(3)/2-150,scrsize(4)/2-100,150,100], ...
                 'Tag','ExportFigure');

      setxpcfont(usrdata.figures.export,8,9);
      set(usrdata.figures.export,'Userdata',usrdata.figures.scope);


      usrdata.figure.export.txt_var = ...
          uicontrol('Parent',usrdata.figures.export, ...
                    'Units','normalized', ...
                    'HorizontalAlignment','left', ...
                    'Position',[0.1 0.7 0.3 0.15], ...
                    'String','Data:', ...
                    'Style','text', ...
                    'Tag','txt_var');

      usrdata.figure.export.ed_var = ...
          uicontrol('Parent',usrdata.figures.export, ...
                    'Units','normalized', ...
                    'BackgroundColor',[1 1 1], ...
                    'HorizontalAlignment','right', ...
                    'Position',[.5 .73 .4 .15], ...
                    'String', usrdata.edit.scope.dataplot, ...
                    'Style','edit', ...
                    'Callback', 'xpcscwin(-15)', ...
                    'Tag','ed_var');

      usrdata.figure.export.txt_time = ...
          uicontrol('Parent',usrdata.figures.export, ...
                    'Units','normalized', ...
                    'HorizontalAlignment','left', ...
                    'Position',[0.1 0.45 0.3 0.15], ...
                    'String','Time:', ...
                    'Style','text', ...
                    'Tag','txt_time');

      usrdata.figure.export.ed_time = ...
          uicontrol('Parent',usrdata.figures.export, ...
                    'Units','normalized', ...
                    'BackgroundColor',[1 1 1], ...
                    'HorizontalAlignment','right', ...
                    'Position',[.5 .48 .4 .15], ...
                    'String', usrdata.edit.scope.timeplot, ...
                    'Style','edit', ...
                    'Callback', 'xpcscwin(-15)', ...
                    'Tag','ed_time');

      usrdata.figure.export.pb_apply = ...
          uicontrol('Parent',usrdata.figures.export, ...
                    'Units','normalized', ...
                    'Position',[0.1 0.05 0.35 0.25], ...
                    'String','Apply', ...
                    'CallBack', 'xpcscwin(-15)', ...
                    'Tag','pb_apply');

      usrdata.figure.export.pb_close = ...
          uicontrol('Parent',usrdata.figures.export, ...
                    'Units','normalized', ...
                    'Position',[0.55 0.05 0.35 0.25], ...
                    'String','Close', ...
                    'CallBack', 'xpcscwin(-16)', ...
                    'Tag','pb_close');

      set(usrdata.figures.scope,'UserData',usrdata);

    else
      figure(usrdata.figures.export);
    end;

    %-----------------------------------
    %Define-Axis Ymax Ymin
    %-----------------------------------

  elseif flag==-13

    usrdata=get(get(gcbf,'UserData'),'UserData');

    if (str2num(get(usrdata.figure.axis.ed_ymax,'String')) <= ...
        str2num(get(usrdata.figure.axis.ed_ymin,'String')));
      errordlg('Ymax must be greater then Ymin');
      set(usrdata.figure.axis.ed_ymax,...
          'String', num2str(usrdata.edit.scope.yaxis.max));
      set(usrdata.figure.axis.ed_ymin,...
          'String', num2str(usrdata.edit.scope.yaxis.min));
      return;
    end;

    usrdata.edit.scope.yaxis.max=...
        str2num(get(usrdata.figure.axis.ed_ymax,'String'));
    usrdata.edit.scope.yaxis.min=...
        str2num(get(usrdata.figure.axis.ed_ymin,'String'));

    set(usrdata.figure.scope.plot,'YLimMode','manual');
    set(usrdata.figure.scope.plot,...
        'YLim',[usrdata.edit.scope.yaxis.min,usrdata.edit.scope.yaxis.max]);

    set(usrdata.figure.scope.menu_axis_auto,'Checked','off');
    set(usrdata.figure.scope.menu_axis_manual,'Checked','on');
    usrdata.edit.scope.axis.auto='off';
    usrdata.edit.scope.axis.manual='on';

    set(get(gcbf,'UserData'),'UserData',usrdata);

    %-----------------------------------
    %Close Define-Axis Window
    %-----------------------------------

  elseif flag==-14

    usrdata=get(get(gcbf,'UserData'),'UserData');
    delete(usrdata.figures.axis);
    usrdata.figures.axis=-1;
    set(usrdata.figures.scope,'UserData',usrdata);

    %-----------------------------------
    %Define Export-Variable
    %-----------------------------------

  elseif flag==-15

    usrdata=get(get(gcbf,'UserData'),'UserData');

    if (isempty(get(usrdata.figure.export.ed_var, 'String')) |...
        isempty(get(usrdata.figure.export.ed_time, 'String')))
      errordlg('Variable Name must be a String');
      set(usrdata.figure.export.ed_var,'String', usrdata.edit.scope.dataplot);
      set(usrdata.figure.export.ed_time,'String', usrdata.edit.scope.timeplot);
    else
      usrdata.edit.scope.dataplot=get(usrdata.figure.export.ed_var,'String');
      usrdata.edit.scope.timeplot=get(usrdata.figure.export.ed_time,'String');
    end;

    set(get(gcbf,'UserData'),'UserData',usrdata);

    %-----------------------------------
    %Close Export Window
    %-----------------------------------

  elseif flag==-16

    usrdata=get(get(gcbf,'UserData'),'UserData');
    delete(usrdata.figures.export);
    usrdata.figures.export=-1;
    set(usrdata.figures.scope,'UserData',usrdata);


    %-----------------------------------
    %Menu View Mode Graphical
    %-----------------------------------

  elseif flag == -20

    %set(usrdata.figure.scope.plot,'YLimMode','auto');
    set(usrdata.figure.scope.menu_y_axis,'Enable','on');
    set(usrdata.figure.scope.menu_grid,'Enable','on');
    set(usrdata.figure.scope.menu_viewmode_graphical,'Checked','on');
    set(usrdata.figure.scope.menu_viewmode_numerical,'Checked','off');
    usrdata.edit.scope.viewmode.graphical='on';
    usrdata.edit.scope.viewmode.numerical='off';

    set(gcbf,'UserData',usrdata);

    %-----------------------------------
    %Menu View Mode Numerical
    %-----------------------------------

  elseif flag == -21

    %set(usrdata.figure.scope.plot,'YLimMode','auto');
    set(usrdata.figure.scope.menu_y_axis,'Enable','off');
    set(usrdata.figure.scope.menu_grid,'Enable','off');
    set(usrdata.figure.scope.menu_grid,'Checked','off');
    set(usrdata.figure.scope.plot,'XGrid','off','YGrid','off');
    usrdata.edit.scope.grid='off';
    set(usrdata.figure.scope.menu_viewmode_graphical,'Checked','off');
    set(usrdata.figure.scope.menu_viewmode_numerical,'Checked','on');
    usrdata.edit.scope.viewmode.graphical='off';
    usrdata.edit.scope.viewmode.numerical='on';

    set(gcbf,'UserData',usrdata);


  end;
end;

%% EOF xpcscwin.m
